project:
  type: book
  output-dir: docs
  execute-dir: project
  resources:
    - styles.css
    - outputs/
    - outputs/**/*.csv
    - outputs/**/*.txt
    - outputs/**/*.tex
    - outputs/**/*.pdf
    - outputs/**/*.png
    - outputs/**/*.rds
    - outputs/**/*.tre

book:
  title: "Mate-choice copying in non-human animals: an update of two meta-analyses"
  subtitle: "Online Supplementary Materials (Reproducible Workflow & Full Outputs)"
  author: "Eduardo S. A. Santos & Collaborators"
  
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/esantos2ua/mate_choice_meta
        aria-label: GitHub
        
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    
  chapters:
    - index.qmd
    - scripts/0_literature_screening/literature_screening.qmd
    - scripts/1_effect_size_calculation_pipeline/overall_effect.qmd
    - scripts/1_effect_size_calculation_pipeline/publication_bias.qmd
    - scripts/3_original_dataset_crosscheck/extraction_validation.qmd
    - scripts/1_effect_size_calculation_pipeline/sensitivity_analysis.qmd
    - scripts/1_effect_size_calculation_pipeline/moderator_analysis.qmd
    - references.qmd

number-sections: false
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    code-fold: true
    code-summary: "Show R code"
    highlight-style:
      light: github
      dark: dracula
    fontsize: 1.05em
    linestretch: 1.35
    toc: true
    toc-depth: 3
    toc-location: left
    code-tools: true
    code-copy: true
    link-external-newwindow: true
    smooth-scroll: true
    citeproc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1400px  
      margin-width: 200px
      gutter-width: 1.5rem
      
execute:
  freeze: auto
  warning: false
  message: false
