project:
  type: default
  output-dir: _site
  render:
    - index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "On this page"
    number-sections: false
    fontsize: 1.05em
    linestretch: 1.5
    code-fold: true
    code-tools: false
    code-summary: "Show code"
    embed-resources: true
    smooth-scroll: true
    link-external-newwindow: true
    tbl-cap-location: top
    fig-cap-location: bottom

execute:
  freeze: false
  warning: false
  message: false
  echo: true
