{
  "hash": "3e22bf7030a5280bfaed77c74ecb0b7f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cross-Dataset Extraction Validation\"\nsubtitle: \"Davies et al. (2020) vs Jones & DuVal (2019) — shared effect sizes\"\nauthor: \"Eduardo S. A. Santos & Collaborators\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n    code-fold: true\n    code-summary: \"Show R code\"\n---\n\n\n\n## What this document validates\n\nWe are updating a mate-choice-copying meta-analysis built on **two existing\ndatasets that overlap in the primary studies they cover but report different\neffect-size metrics**:\n\n* **Davies et al. (2020)** — Hedges' *d*\n* **Jones & DuVal (2019)** — log odds ratio (lnOR)\n\nBoth are *standardized effect sizes*: different numerical scales for the same\nunderlying quantity — how strongly an observer's mate preference shifts toward\nthe male it saw being chosen — and one scale can be converted into the other.\n\nBefore pooling them we need to know: *for the studies both teams extracted, do\nthe effect sizes agree once placed on a common scale?* This is a\n**method-comparison** problem (two \"instruments\" measuring the same underlying\neffects), so — unlike a single-team re-extraction audit — we can apply formal\nagreement statistics (correlation, Bland–Altman limits of agreement) on top of\nthe per-study qualitative review.\n\nThe matching itself (study-level crosswalk + within-study optimal effect-size\nassignment) is performed by\n[`crosscheck_davies_jones.py`](crosscheck_davies_jones.py); this report reads\nits output and assesses agreement. Key methodological points carried over:\n\n* **Scale conversion.** Jones lnOR is mapped to Hedges' *d* via the\n  logistic-to-normal approximation $d = \\text{lnOR}\\times\\sqrt{3}/\\pi$\n  (≈ 0.5513; Borenstein et al. 2009).\n* **Absolute magnitudes.** The two datasets use opposite sign conventions\n  (Davies' non-directional *d* carries the raw mean-difference sign; Jones'\n  lnOR sign encodes copying direction), so agreement is assessed on $|d|$.\n  Sign concordance is reported separately as a diagnostic.\n\n**How this document is organised.** The analysis runs in five steps: (1) *match\nstudies* — find the studies both datasets extracted and pair up their individual\neffect sizes; (2) *measure agreement* — quantify how closely the paired values\nagree once on a common scale; (3) *classify disagreements* — for pairs that do\nnot agree, label *why*; (4) *re-extract the worst cases* — return to the original\nPDFs and recompute the effect size from the raw data; and (5) *conclude*.\nThroughout, \"Jones\" and \"Davies\" name the two source **datasets**, not the\nprimary studies they drew from. A *pair* is a single Jones effect size lined up\nwith the one Davies effect size that most plausibly measures the same thing in\nthe same study (the pairing is done automatically, choosing the alignment that\nminimises the magnitude difference within each study).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resolve the outputs dir whether rendered standalone (cwd = this file's dir)\n# or as part of the book (cwd = project root, via execute-dir: project).\nout_dir <- \"outputs/3_original_dataset_crosscheck\"\nif (!dir.exists(out_dir)) out_dir <- file.path(\"..\", \"..\", out_dir)\nxwalk  <- read_csv(file.path(out_dir, \"crosswalk_effect_sizes.csv\"), show_col_types = FALSE)\nshared <- read_csv(file.path(out_dir, \"shared_studies.csv\"), show_col_types = FALSE)\nunmatched <- read_csv(file.path(out_dir, \"unmatched_jones_studies.csv\"), show_col_types = FALSE)\n\n# study tag + agreement / structural-cause classification\nxwalk <- xwalk %>%\n    mutate(\n        study      = paste0(author_prefix, year),\n        agreement  = if_else(magnitude_match, \"agree\", \"disagree\"),\n        es_structure = if_else(n_jones_es == n_davies_es,\n                               \"same ES count\", \"ES count differs\"),\n        cause = case_when(\n            magnitude_match                      ~ \"agree\",\n            n_jones_es != n_davies_es            ~ \"ES-count / extraction structure differs\",\n            TRUE                                 ~ \"same structure, magnitude conflict\"\n        )\n    )\n```\n:::\n\n\n## Headline summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_shared <- nrow(shared)\nn_pairs  <- nrow(xwalk)\nn_match  <- sum(xwalk$magnitude_match)\nn_sign   <- sum(xwalk$sign_agree)\ntibble(\n    Metric = c(\"Shared studies (in both datasets)\",\n               \"Jones studies NOT in Davies\",\n               \"Comparable effect-size pairs\",\n               \"Pairs matching in magnitude (|Δd| ≤ 0.15 or ≤ 15%)\",\n               \"Pairs with concordant sign\"),\n    Value  = c(n_shared,\n               nrow(unmatched),\n               n_pairs,\n               sprintf(\"%d (%s%%)\", n_match, fmt(100*n_match/n_pairs, 0)),\n               sprintf(\"%d (%s%%)\", n_sign,  fmt(100*n_sign/n_pairs, 0)))\n) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|Metric                                                       |Value    |\n|:------------------------------------------------------------|:--------|\n|Shared studies (in both datasets)                            |29       |\n|Jones studies NOT in Davies                                  |8        |\n|Comparable effect-size pairs                                 |52       |\n|Pairs matching in magnitude (&#124;Δd&#124; ≤ 0.15 or ≤ 15%) |34 (65%) |\n|Pairs with concordant sign                                   |36 (69%) |\n\n\n:::\n:::\n\n\n**How to read this.** The two datasets share 29 primary studies, with a\nfurther 8 studies appearing only in Jones. Within the shared\nstudies their effect sizes line up into 52 comparable pairs, of which\n65% agree in magnitude (tolerance: 0.15 *d*-units or\n15%). Sign agreement looks low (69%), but that is\n*expected* — the two datasets encode copying direction with opposite signs, so we\ncompare absolute magnitudes here and revisit sign separately later. The sections\nthat follow ask how serious the magnitude disagreements are, and what causes them.\n\n## Method-comparison agreement statistics\n\nWith the effect sizes paired, we ask how well the two datasets agree *as\nmeasurements of the same thing* — the classic question of whether two instruments\ngive the same reading. Three complementary tools answer it:\n\n* **Correlation** (Pearson *r*, Spearman *ρ*) — do the two rise and fall together?\n  (1 = perfectly in step.)\n* **Regression slope** of Davies on Jones — is one dataset systematically larger\n  than the other? (a slope of 1 = no scaling difference.)\n* **Bland–Altman** — for each pair, the *difference* between the two values plotted\n  against their *average*; the mean difference is the typical bias, and the 95%\n  \"limits of agreement\" bound how far apart the two datasets usually fall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npear <- cor.test(xwalk$abs_jones_d, xwalk$abs_davies_d, method = \"pearson\")\nspear <- suppressWarnings(\n    cor.test(xwalk$abs_jones_d, xwalk$abs_davies_d, method = \"spearman\"))\nfit  <- lm(abs_davies_d ~ abs_jones_d, data = xwalk)\n\n# same-ES-count subset (like-for-like extractions)\nsub <- filter(xwalk, es_structure == \"same ES count\")\npear_sub <- cor.test(sub$abs_jones_d, sub$abs_davies_d)\n\n# Bland-Altman on |d|\nxwalk <- xwalk %>%\n    mutate(ba_mean = (abs_jones_d + abs_davies_d)/2,\n           ba_diff = abs_jones_d - abs_davies_d)\nbias <- mean(xwalk$ba_diff); s <- sd(xwalk$ba_diff)\nloa_lo <- bias - 1.96*s; loa_hi <- bias + 1.96*s\n\ntibble(\n    Statistic = c(\"Pearson r (all pairs)\",\n                  \"Spearman ρ (all pairs)\",\n                  \"Pearson r (same-ES-count studies only)\",\n                  \"OLS slope (Davies ~ Jones)\",\n                  \"OLS intercept\",\n                  \"Bland–Altman mean bias (Jones − Davies, |d|)\",\n                  \"95% limits of agreement\"),\n    Value = c(sprintf(\"%s (95%% CI %s–%s, %s)\", fmt(pear$estimate,3),\n                      fmt(pear$conf.int[1],2), fmt(pear$conf.int[2],2),\n                      ifelse(pear$p.value < 1e-4, \"p < 0.0001\",\n                             paste0(\"p = \", fmt(pear$p.value,4)))),\n              fmt(spear$estimate,3),\n              sprintf(\"%s (n = %d pairs)\", fmt(pear_sub$estimate,3), nrow(sub)),\n              fmt(coef(fit)[2],3),\n              fmt(coef(fit)[1],3),\n              sprintf(\"%s d-units\", fmt(bias,3)),\n              sprintf(\"%s to %s\", fmt(loa_lo,2), fmt(loa_hi,2)))\n) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|Statistic                                              |Value                                |\n|:------------------------------------------------------|:------------------------------------|\n|Pearson r (all pairs)                                  |0.795 (95% CI 0.67–0.88, p < 0.0001) |\n|Spearman ρ (all pairs)                                 |0.862                                |\n|Pearson r (same-ES-count studies only)                 |0.891 (n = 12 pairs)                 |\n|OLS slope (Davies ~ Jones)                             |1.193                                |\n|OLS intercept                                          |0.036                                |\n|Bland–Altman mean bias (Jones − Davies, &#124;d&#124;) |-0.141 d-units                       |\n|95% limits of agreement                                |-1.05 to 0.77                        |\n\n\n:::\n:::\n\n\nA negative mean bias (-0.14) and an OLS slope > 1 (1.19) both indicate Davies tends to report **larger** magnitudes than the Jones-converted values, increasingly so for larger effects.\n\n### Agreement plots\n\nIn the **left** panel, perfect agreement would place every point on the dashed\ndiagonal; points above it are studies where Davies reports the larger magnitude.\nIn the **right** (Bland–Altman) panel, points scattered evenly around zero would\nmean no systematic difference — a shift away from zero is bias, and points beyond\nthe dashed limits are the outlying disagreements that the rest of this document\ninvestigates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim <- c(0, max(xwalk$abs_jones_d, xwalk$abs_davies_d) * 1.05)\n\np_scatter <- ggplot(xwalk, aes(abs_jones_d, abs_davies_d)) +\n    geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", colour = \"grey50\") +\n    geom_point(aes(colour = agreement, shape = es_structure), size = 2.6, alpha = .85) +\n    geom_text(aes(label = study), size = 2.4, vjust = -0.8, check_overlap = TRUE) +\n    scale_colour_manual(values = c(agree = \"#2c7fb8\", disagree = \"#d95f0e\")) +\n    coord_equal(xlim = lim, ylim = lim) +\n    labs(x = \"Jones & DuVal  |d|  (lnOR × √3/π)\", y = \"Davies  |Hedges d|\",\n         colour = NULL, shape = NULL, title = \"Effect-size agreement\") +\n    theme_minimal(base_size = 12) + theme(legend.position = \"bottom\")\n\np_ba <- ggplot(xwalk, aes(ba_mean, ba_diff)) +\n    geom_hline(yintercept = 0, colour = \"grey80\") +\n    geom_hline(yintercept = bias, colour = \"#2c7fb8\") +\n    geom_hline(yintercept = c(loa_lo, loa_hi), linetype = \"dashed\", colour = \"#d95f0e\") +\n    geom_point(aes(colour = agreement), size = 2.6, alpha = .85) +\n    geom_text(aes(label = study), size = 2.4, vjust = -0.8, check_overlap = TRUE) +\n    scale_colour_manual(values = c(agree = \"#2c7fb8\", disagree = \"#d95f0e\"), guide = \"none\") +\n    labs(x = \"Mean of the two |d|\", y = \"Jones − Davies  (|d|)\",\n         title = \"Bland–Altman\") +\n    theme_minimal(base_size = 12)\n\np_scatter + p_ba\n```\n\n::: {.cell-output-display}\n![Left: Jones-converted vs Davies |d| with the line of identity (dashed). Right: Bland–Altman plot (mean bias solid, 95% limits of agreement dashed). Points are coloured by whether the pair matches in magnitude; studies where the two teams extracted different numbers of effect sizes are ringed.](extraction_validation_files/figure-html/fig-agreement-1.png){#fig-agreement width=1056}\n:::\n:::\n\n\n## Discrepancy classification\n\nBorrowing the per-study \"required action\" structure from Sánchez-Tójar et al.'s\nvalidation codebook, every pair is classified by *why* it does or does not\nagree. The dominant structural cause is whether the two teams extracted the\n**same number of effect sizes** from a paper.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxwalk %>% count(cause, name = \"pairs\") %>%\n    mutate(`%` = fmt(100*pairs/sum(pairs), 0)) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|cause                                   | pairs|%  |\n|:---------------------------------------|-----:|:--|\n|ES-count / extraction structure differs |    13|25 |\n|agree                                   |    34|65 |\n|same structure, magnitude conflict      |     5|10 |\n\n\n:::\n:::\n\n\nThe three causes mean very different things. *Agree* needs no action.\n*ES-count / extraction structure differs* means the two teams split a study into\ndifferent numbers of effect sizes, so a clean one-to-one comparison is impossible\n— a bookkeeping difference, not necessarily an error. *Same structure, magnitude\nconflict* is the category that matters: the teams extracted the same number of\neffect sizes yet still disagree, which signals a genuine extraction difference.\nIn the per-pair table below, the `behaviour` columns are the key tell — when a\nJones \"reversal/random\" contrast is paired against a Davies \"affiliation/mating\"\none, the two teams measured a *different outcome* from the same paper.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxwalk %>%\n    transmute(study, jones_code, jones_behaviour,\n              davies_study, davies_behaviour, davies_n,\n              `Jones |d|` = round(abs_jones_d, 2),\n              `Davies |d|` = round(abs_davies_d, 2),\n              `Δ|d|` = round(abs_diff, 2),\n              sign_agree, cause) %>%\n    datatable(rownames = FALSE, filter = \"top\",\n              options = list(pageLength = 15, scrollX = TRUE),\n              caption = \"Per-pair crosswalk. Note the behaviour columns: a Jones 'reversal/random' contrast paired against a Davies 'Affiliation/Mating' contrast flags a different OUTCOME extracted from the same paper.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-47f8df24a893321f25b4\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-47f8df24a893321f25b4\">{\"x\":{\"filter\":\"top\",\"vertical\":false,\"filterHTML\":\"<tr>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"3\\\" data-max=\\\"76\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"15\\\" data-max=\\\"160\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"2.09\\\" data-scale=\\\"2\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"3.73\\\" data-scale=\\\"2\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"-2.5\\\" data-max=\\\"0.58\\\" data-scale=\\\"2\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"logical\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"width: 100%; display: none;\\\">\\n      <select multiple=\\\"multiple\\\" style=\\\"width: 100%;\\\" data-options=\\\"[&quot;true&quot;,&quot;false&quot;]\\\"><\\/select>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n<\\/tr>\",\"caption\":\"<caption>Per-pair crosswalk. Note the behaviour columns: a Jones 'reversal/random' contrast paired against a Davies 'Affiliation/Mating' contrast flags a different OUTCOME extracted from the same paper.<\\/caption>\",\"data\":[[\"APP2000\",\"APP2000\",\"AUL2009\",\"AUL2009\",\"BRI1996\",\"BRI1996\",\"BRO1996\",\"BRO1999\",\"DAG2016\",\"DAG2016\",\"DAG2016\",\"DAN2018\",\"DAN2018\",\"DRU2008\",\"DUG1992\",\"DUG1992\",\"DUG1993\",\"DUG1993\",\"DUG1998\",\"DUG1998\",\"DUG1998\",\"DUG1998\",\"DUG2003\",\"DUG2003\",\"FOR1996\",\"FOR1996\",\"FOW2015\",\"GER2016\",\"GER2016\",\"GER2016\",\"GER2016\",\"GIE2018\",\"GIE2018\",\"GOD2009\",\"GOL1993\",\"GRA1996\",\"HOW1998\",\"LAF1997\",\"MAT2013\",\"MER2009\",\"MER2009\",\"MIL2011\",\"MUN2004\",\"MUN2004\",\"NOB2018\",\"NOB2018\",\"PAT1998\",\"SLA1999\",\"VUK2007\",\"VUK2007\",\"VUK2007\",\"VUK2007\"],[\"APP2000THE\",\"APP2000THE\",\"AUL2009DO\",\"AUL2009DO\",\"BRI1996MAT\",\"BRI1996MAT\",\"BRO1996COP\",\"BRO1999MAT\",\"DAG2016DRO\",\"DAG2016DRO\",\"DAG2016DRO\",\"DAN2018CUL\",\"DAN2018CUL\",\"DRU2008MAT\",\"DUG1992REV\",\"DUG1992SEX\",\"DUG1993FEM\",\"DUG1993FEM\",\"DUG1998EFF\",\"DUG1998EFF\",\"DUG1998EFF\",\"DUG1998GEN\",\"DUG2003THE\",\"DUG2003THE\",\"FOR1996FEM\",\"FOR1996FEM\",\"FOW2015THE\",\"GER2016MAT\",\"GER2016MAT\",\"GER2016MAT\",\"GER2016MAT\",\"GIE2018MAT\",\"GIE2018MAT\",\"GOD2009MAT\",\"GOL1993SEL\",\"GRA1996MAT\",\"HOW1998MAT\",\"LAF1997FEM\",\"MAT2013FEM\",\"MER2009PUB\",\"MER2009PUB\",\"MIL2011NON\",\"MUN2004MAT\",\"MUN2004MAT\",\"NOB2018COP\",\"NOB2018COP\",\"PAT1998DO\",\"SLA1999MAT\",\"VUK2007SIZ\",\"VUK2007SIZ\",\"VUK2007SIZ\",\"VUK2007SIZ\"],[\"reversal\",\"same\",\"random\",\"random\",\"reversal\",\"reversal\",\"reversal\",\"random\",\"model_choice\",\"model_choice\",\"model_choice\",\"random\",\"random\",\"reversal\",\"reversal\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"less_attractive\",\"reversal\",\"same\",\"random\",\"random\",\"model_choice\",\"random\",\"random\",\"random\",\"random\",\"reversal\",\"reversal\",\"random\",\"random\",\"random\",\"reversal\",\"random\",\"random\",\"random\",\"random\",\"random\",\"reversal\",\"same\",\"less_attractive\",\"more_attractive\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\"],[3,3,5,5,10,10,11,12,15,15,15,16,16,18,27,27,20,20,22,22,22,22,24,24,30,30,31,35,35,35,35,36,36,37,39,42,46,52,55,57,57,58,61,61,62,62,67,73,76,76,76,76],[\"Affiliation\",\"Affiliation\",\"Mating\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Mating\",\"Mating\",\"Mating\",\"Mating\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Mating\",\"Mating\",\"Mating\",\"Mating latency\",\"Mating\",\"Mating\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Mating\",\"Mating\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Mating\",\"Mating\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\",\"Affiliation\"],[24,24,104,126,40,40,80,20,134,96,84,126,124,30,40,40,40,40,40,40,40,40,40,40,32,30,42,125,58,64,66,15,15,70,32,46,40,24,20,80,80,100,50,50,158,160,70,36,28,20,28,26],[0.83,0.74,0.04,0.23,0.83,0.83,0,0.06,0.55,0.35,0.58,0.55,0.8,0.5600000000000001,1.23,0.65,0.96,0.22,0.22,0.11,0.11,0.99,0.93,0,0,1.03,0.1,0.6,0.27,0.17,0.07000000000000001,1.68,1.68,1.88,0.14,0.57,0.61,0.2,2.09,0.27,0.49,0,0.39,0.11,0.6,0.14,0.16,0.25,0.38,0.9399999999999999,0.76,0.26],[0.25,0.24,0.05,0.29,1.38,1.38,0,0.08,0.51,0.35,0.68,0.61,1.03,0.76,3.73,0.5600000000000001,2.38,1,0.28,0.14,0.14,1.12,1.13,0,0,1.19,0.63,0.45,0.3,0.27,0.09,1.98,2.43,1.52,0.17,0.71,1.14,0.16,1.95,0.36,0.68,0,0.27,0.12,0.13,0.08,0.2,0.31,0.41,0.91,0.62,0.32],[0.58,0.49,-0.01,-0.06,-0.55,-0.55,0,-0.03,0.05,-0.01,-0.1,-0.06,-0.23,-0.21,-2.5,0.1,-1.42,-0.78,-0.06,-0.03,-0.03,-0.14,-0.2,0,0,-0.16,-0.53,0.15,-0.03,-0.1,-0.02,-0.3,-0.75,0.35,-0.04,-0.14,-0.53,0.04,0.14,-0.08,-0.19,0,0.12,-0.02,0.47,0.06,-0.04,-0.06,-0.02,0.03,0.14,-0.07000000000000001],[false,true,true,false,true,true,true,false,true,true,true,true,true,false,true,true,false,true,false,true,true,true,false,true,true,true,true,false,true,true,true,false,false,true,false,true,false,true,true,true,true,true,false,false,true,false,true,true,false,true,true,true],[\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"same structure, magnitude conflict\",\"same structure, magnitude conflict\",\"agree\",\"agree\",\"agree\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"agree\",\"same structure, magnitude conflict\",\"same structure, magnitude conflict\",\"agree\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"same structure, magnitude conflict\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"agree\",\"ES-count / extraction structure differs\",\"agree\",\"agree\",\"agree\",\"agree\",\"agree\",\"agree\",\"agree\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>study<\\/th>\\n      <th>jones_code<\\/th>\\n      <th>jones_behaviour<\\/th>\\n      <th>davies_study<\\/th>\\n      <th>davies_behaviour<\\/th>\\n      <th>davies_n<\\/th>\\n      <th>Jones |d|<\\/th>\\n      <th>Davies |d|<\\/th>\\n      <th>Δ|d|<\\/th>\\n      <th>sign_agree<\\/th>\\n      <th>cause<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,5,6,7,8]},{\"name\":\"study\",\"targets\":0},{\"name\":\"jones_code\",\"targets\":1},{\"name\":\"jones_behaviour\",\"targets\":2},{\"name\":\"davies_study\",\"targets\":3},{\"name\":\"davies_behaviour\",\"targets\":4},{\"name\":\"davies_n\",\"targets\":5},{\"name\":\"Jones |d|\",\"targets\":6},{\"name\":\"Davies |d|\",\"targets\":7},{\"name\":\"Δ|d|\",\"targets\":8},{\"name\":\"sign_agree\",\"targets\":9},{\"name\":\"cause\",\"targets\":10}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"orderCellsTop\":true,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Studies flagged for manual re-extraction\n\nThe clearest validation failures are pairs that **disagree despite both teams\nextracting the same number of effect sizes** (so the disagreement is not merely\nstructural), plus any same-paper pair whose outcome construct differs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxwalk %>%\n    filter(!magnitude_match) %>%\n    arrange(desc(abs(abs_diff))) %>%\n    transmute(study, jones_behaviour, davies_behaviour,\n              `Jones |d|` = round(abs_jones_d, 2),\n              `Davies |d|` = round(abs_davies_d, 2),\n              `Δ|d|` = round(abs_diff, 2),\n              n_jones_es, n_davies_es, cause) %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n|study   |jones_behaviour |davies_behaviour | Jones &#124;d&#124;| Davies &#124;d&#124;| Δ&#124;d&#124;| n_jones_es| n_davies_es|cause                                   |\n|:-------|:---------------|:----------------|-------------------:|--------------------:|--------------:|----------:|-----------:|:---------------------------------------|\n|DUG1992 |reversal        |Affiliation      |                1.23|                 3.73|          -2.50|          3|           2|ES-count / extraction structure differs |\n|DUG1993 |random          |Affiliation      |                0.96|                 2.38|          -1.42|          2|           2|same structure, magnitude conflict      |\n|DUG1993 |random          |Affiliation      |                0.22|                 1.00|          -0.78|          2|           2|same structure, magnitude conflict      |\n|GIE2018 |reversal        |Affiliation      |                1.68|                 2.43|          -0.75|          4|           2|ES-count / extraction structure differs |\n|APP2000 |reversal        |Affiliation      |                0.83|                 0.25|           0.58|          2|           4|ES-count / extraction structure differs |\n|BRI1996 |reversal        |Affiliation      |                0.83|                 1.38|          -0.55|          2|           2|same structure, magnitude conflict      |\n|BRI1996 |reversal        |Affiliation      |                0.83|                 1.38|          -0.55|          2|           2|same structure, magnitude conflict      |\n|HOW1998 |reversal        |Affiliation      |                0.61|                 1.14|          -0.53|          1|           1|same structure, magnitude conflict      |\n|FOW2015 |model_choice    |Mating           |                0.10|                 0.63|          -0.53|          2|           1|ES-count / extraction structure differs |\n|APP2000 |same            |Affiliation      |                0.74|                 0.24|           0.49|          2|           4|ES-count / extraction structure differs |\n|NOB2018 |less_attractive |Mating           |                0.60|                 0.13|           0.47|          2|           4|ES-count / extraction structure differs |\n|GOD2009 |random          |Affiliation      |                1.88|                 1.52|           0.35|          1|           2|ES-count / extraction structure differs |\n|GIE2018 |reversal        |Affiliation      |                1.68|                 1.98|          -0.30|          4|           2|ES-count / extraction structure differs |\n|DAN2018 |random          |Mating           |                0.80|                 1.03|          -0.23|         17|           2|ES-count / extraction structure differs |\n|DRU2008 |reversal        |Affiliation      |                0.56|                 0.76|          -0.21|          1|           2|ES-count / extraction structure differs |\n|DUG2003 |reversal        |Affiliation      |                0.93|                 1.13|          -0.20|          2|           4|ES-count / extraction structure differs |\n|MER2009 |random          |Mating           |                0.49|                 0.68|          -0.19|          2|           3|ES-count / extraction structure differs |\n|GER2016 |random          |Mating latency   |                0.60|                 0.45|           0.15|          4|           8|ES-count / extraction structure differs |\n\n\n:::\n:::\n\n\n## Sign-concordance diagnostic\n\nBecause the sign conventions differ by construction, low sign agreement is\n*expected* and is not itself a validation failure — but a breakdown helps\nconfirm the conventions are simply inverted rather than randomly assigned.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxwalk %>%\n    summarise(`pairs` = n(),\n              `sign agree` = sum(sign_agree),\n              `% agree` = fmt(100*mean(sign_agree), 0)) %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n| pairs| sign agree|% agree |\n|-----:|----------:|:-------|\n|    52|         36|69      |\n\n\n:::\n:::\n\n\n## Effect-size-count reconciliation\n\nHow the two teams partitioned each shared paper into effect sizes (a major\ndriver of the comparable-pair count, since only `min(nJ, nD)` pairs per study\ncan be aligned).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshared %>%\n    transmute(study = paste0(author_prefix, year),\n              jones_species, davies_species,\n              n_jones_es, n_davies_es,\n              n_compared,\n              `unpaired` = abs(n_jones_es - n_davies_es)) %>%\n    arrange(desc(unpaired)) %>%\n    datatable(rownames = FALSE, options = list(pageLength = 15, scrollX = TRUE))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-35de7392da10d893f2af\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-35de7392da10d893f2af\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"DAN2018\",\"VUK2007\",\"BRO1999\",\"GER2016\",\"DUG1998\",\"APP2000\",\"DUG2003\",\"GIE2018\",\"LAF1997\",\"MUN2004\",\"NOB2018\",\"PAT1998\",\"BRO1996\",\"DAG2016\",\"DRU2008\",\"DUG1992\",\"FOW2015\",\"GOD2009\",\"GRA1996\",\"MAT2013\",\"MER2009\",\"AUL2009\",\"BRI1996\",\"DUG1993\",\"FOR1996\",\"GOL1993\",\"HOW1998\",\"MIL2011\",\"SLA1999\"],[\"melanogaster\",\"reticulata\",\"reticulata\",\"melanogaster\",\"reticulata\",\"perugiae\",\"reticulata\",\"latipinna\",\"reticulata\",\"nigrofasciata\",\"melanogaster\",\"aculeatus\",\"reticulata\",\"melanogaster\",\"guttata\",\"reticulata\",\"ocreata\",\"reticulata\",\"latipes\",\"nitidus\",\"melanogaster\",\"serrata\",\"reticulata\",\"reticulata\",\"minutu\",\"aculeatus\",\"latipes\",\"mjoebergi\",\"hypoleuca\"],[\"Drosophila melanogaster\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Drosophila melanogaster\",\"Poecilia reticulata\",\"Limia perugiae\",\"Poecilia reticulata\",\"Poecilia latipinna\",\"Poecilia reticulata\",\"Limia nigrofasciata\",\"Drosophila melanogaster\",\"Gasterosteus aculeatus\",\"Poecilia reticulata\",\"Drosophila melanogaster\",\"Taeniopygia guttata\",\"Poecilia reticulata\",\"Schizocosa\",\"Poecilia reticulata\",\"Oryzias latipes\",\"Rhabdoblennius nitidus\",\"Drosophila melanogaster\",\"Drosophila serrata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Pomatoschistus minutus\",\"Gasterosteus aculeatus\",\"Oryzias latipes\",\"Uca mjoebergi\",\"Ficedula hypoleuca\"],[17,4,1,4,7,2,2,4,1,2,2,1,1,3,1,3,2,1,2,1,2,2,2,2,2,1,1,1,1],[2,12,6,8,4,4,4,2,3,4,4,3,2,4,2,2,1,2,1,2,3,2,2,2,2,1,1,1,1],[2,4,1,4,4,2,2,2,1,2,2,1,1,3,1,2,1,1,1,1,2,2,2,2,2,1,1,1,1],[15,8,5,4,3,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>study<\\/th>\\n      <th>jones_species<\\/th>\\n      <th>davies_species<\\/th>\\n      <th>n_jones_es<\\/th>\\n      <th>n_davies_es<\\/th>\\n      <th>n_compared<\\/th>\\n      <th>unpaired<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,4,5,6]},{\"name\":\"study\",\"targets\":0},{\"name\":\"jones_species\",\"targets\":1},{\"name\":\"davies_species\",\"targets\":2},{\"name\":\"n_jones_es\",\"targets\":3},{\"name\":\"n_davies_es\",\"targets\":4},{\"name\":\"n_compared\",\"targets\":5},{\"name\":\"unpaired\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshared %>% summarise(\n    `Jones effect sizes (shared studies)` = sum(n_jones_es),\n    `Davies effect sizes (shared studies)` = sum(n_davies_es),\n    `Comparable pairs (Σ min)` = sum(n_compared)) %>%\n    pivot_longer(everything(), names_to = \"Metric\", values_to = \"Count\") %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n|Metric                               | Count|\n|:------------------------------------|-----:|\n|Jones effect sizes (shared studies)  |    75|\n|Davies effect sizes (shared studies) |    87|\n|Comparable pairs (Σ min)             |    52|\n\n\n:::\n:::\n\n\n## Jones studies absent from Davies\n\nVerified against **all** Davies studies (matching species epithet anywhere,\nauthor prefix at any year, and year ± 1); none have a Davies counterpart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunmatched %>%\n    transmute(study = paste0(author_prefix, year), species,\n              n_effect_sizes, reason) %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n|study   |species      | n_effect_sizes|reason                                         |\n|:-------|:------------|--------------:|:----------------------------------------------|\n|DUG1996 |reticulata   |              4|no Davies study with this author-prefix + year |\n|FRE2009 |ater         |              2|no Davies study with this author-prefix + year |\n|GOD2005 |latipinna    |              2|no Davies study with this author-prefix + year |\n|GOU1997 |leucogaster  |              2|no Davies study with this author-prefix + year |\n|GOU2006 |leucogaster  |              2|no Davies study with this author-prefix + year |\n|MON2018 |melanogaster |              4|no Davies study with this author-prefix + year |\n|MON2019 |melanogaster |             10|no Davies study with this author-prefix + year |\n|STI2011 |olmstedi     |              2|no Davies study with this author-prefix + year |\n\n\n:::\n:::\n\n\n## Re-extraction: what happens when we return to the source PDFs {#sec-reextraction}\n\nThe agreement analysis flags *where* the two datasets disagree, but not *which*\nis correct. To resolve that for the worst cases, we pulled the primary-study\nPDFs for every study whose effect-size pair disagreed by **> 0.5 Hedges-*d*\nunits** and re-extracted each effect size from the raw data, recomputing it as a\n2×2 odds ratio — tabulating how many observers chose the demonstrated male\nversus the alternative, in the treatment and (where one exists) in the control,\nand taking the odds of one over the other — under the meta-analysis's own\nconventions (treatment-vs-control where the study used a control group; the\nobserved proportion against 50% chance otherwise). This gives a third,\nindependent estimate per effect size — a tie-breaker.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreext <- read_csv(file.path(out_dir, \"reextraction_flagged_7studies.csv\"),\n                  show_col_types = FALSE) %>%\n    mutate(\n        study     = gsub(\"_\", \" \", sub(\"^([^_]+_[0-9]+).*\", \"\\\\1\", identifierStudyId)),\n        label     = paste0(study, \" · \", identifierExperimentId),\n        reext_d   = log(effectSizeCalculatedEstimate) * 0.5513,   # ln(OR) -> Hedges d\n        jones_d   = compare_jones_d,\n        davies_d  = compare_davies_hedges_d,\n        reext_abs = abs(reext_d), jones_abs = abs(jones_d), davies_abs = abs(davies_d)\n    )\nmj <- mean(abs(reext$reext_abs - reext$jones_abs))\nmd <- mean(abs(reext$reext_abs - reext$davies_abs))\n```\n:::\n\n\n### The three estimates side by side\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreext %>%\n    transmute(Study = label,\n              `2×2 (A/B/C/D)` = paste(effectSizeSampleSizeA, effectSizeSampleSizeB,\n                                      effectSizeSampleSizeC, effectSizeSampleSizeD, sep = \"/\"),\n              `Re-extracted d` = round(reext_d, 2),\n              `Jones d` = round(jones_d, 2),\n              `Davies d` = round(davies_d, 2),\n              `|re-ext − Jones|` = round(abs(reext_abs - jones_abs), 2),\n              `|re-ext − Davies|` = round(abs(reext_abs - davies_abs), 2)) %>%\n    datatable(rownames = FALSE, options = list(pageLength = 12, dom = \"t\", scrollX = TRUE),\n              caption = \"Re-extracted effect size vs the two prior extractions (Hedges d). Cells A/B = treatment chose-target / not; C/D = control or 50/50 reference.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-fdd3068b70834e778553\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fdd3068b70834e778553\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Re-extracted effect size vs the two prior extractions (Hedges d). Cells A/B = treatment chose-target / not; C/D = control or 50/50 reference.<\\/caption>\",\"data\":[[\"Applebaum 2000 · Exp001\",\"Briggs 1996 · Exp001\",\"Briggs 1996 · Exp002\",\"Dugatkin 1992 · Exp001\",\"Dugatkin 1992 · Exp005\",\"Dugatkin 1993 · Exp001\",\"Dugatkin 1993 · Exp002\",\"FowlerFinn 2015 · Exp001\",\"FowlerFinn 2015 · Exp002\",\"Gierszewski 2018 · Exp001\",\"Gierszewski 2018 · Exp002\",\"Howard 1998 · Exp001\"],[\"13/11/5/19\",\"12/8/5/15\",\"12/8/5/15\",\"17/3/11/9\",\"16/4/11/9\",\"17/3/10/10\",\"12/8/10/10\",\"9/1/5/5\",\"6/5/5.5/5.5\",\"11/4/2/13\",\"10/5/2/13\",\"5/15/10/10\"],[0.83,0.83,0.83,0.85,0.65,0.96,0.22,1.21,0.1,1.59,1.41,-0.61],[0.83,0.83,0.83,0.85,0.65,0.96,0.22,1.21,0.1,1.59,1.41,-0.61],[-0.25,1.38,1.38,3.73,0.5600000000000001,2.38,1,0.63,0.63,1.98,2.43,1.14],[0,0,0,0,0,0,0,0,0,0,0,0],[0.58,0.55,0.55,2.89,0.1,1.42,0.78,0.58,0.53,0.39,1.01,0.53]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Study<\\/th>\\n      <th>2×2 (A/B/C/D)<\\/th>\\n      <th>Re-extracted d<\\/th>\\n      <th>Jones d<\\/th>\\n      <th>Davies d<\\/th>\\n      <th>|re-ext − Jones|<\\/th>\\n      <th>|re-ext − Davies|<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":12,\"dom\":\"t\",\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3,4,5,6]},{\"name\":\"Study\",\"targets\":0},{\"name\":\"2×2 (A/B/C/D)\",\"targets\":1},{\"name\":\"Re-extracted d\",\"targets\":2},{\"name\":\"Jones d\",\"targets\":3},{\"name\":\"Davies d\",\"targets\":4},{\"name\":\"|re-ext − Jones|\",\"targets\":5},{\"name\":\"|re-ext − Davies|\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nAcross the 12 re-extracted effect sizes the **point estimates** sit\nalmost exactly on the **Jones** values (mean |Δ*d*| = 0.00) and far from\nthe **Davies** values (mean |Δ*d*| = 0.83). Two cautions stop this from\nbeing read as \"the extraction is validated against Jones\":\n\n* **Point-estimate agreement is expected, not corroborating.** These outcomes are\n  discrete choice counts read directly from each PDF; any careful extractor\n  building the same 2×2 obtains the same lnOR. Agreement here confirms we *read the\n  papers the same way* — it is not independent evidence that either prior\n  extraction is correct.\n* **The original crosswalk selected the construction that matched Jones.** For each\n  study it chose the 2×2 that reproduced Jones's variance, which makes the variance\n  match circular. The next section removes that circularity: it re-derives every\n  effect size from a rule fixed by the study design **before** any comparison to\n  Jones, and reports count agreement and design agreement separately.\n\n### Visualising the tie-break\n\n\n::: {.cell}\n\n```{.r .cell-code}\nord  <- reext %>% arrange(reext_abs) %>% pull(label)\nlong <- reext %>%\n    select(label, Jones = jones_abs, Davies = davies_abs, `Re-extracted` = reext_abs) %>%\n    pivot_longer(-label, names_to = \"source\", values_to = \"absd\") %>%\n    mutate(label = factor(label, levels = ord))\n\np_db <- ggplot(long, aes(absd, label)) +\n    geom_line(aes(group = label), colour = \"grey75\") +\n    geom_point(aes(colour = source, shape = source), size = 3, alpha = .9) +\n    scale_colour_manual(values = c(`Re-extracted` = \"#1a9850\", Jones = \"#2c7fb8\", Davies = \"#d95f0e\")) +\n    labs(x = \"|Hedges d|\", y = NULL, colour = NULL, shape = NULL,\n         title = \"Re-extracted vs prior extractions\") +\n    theme_minimal(base_size = 11) + theme(legend.position = \"bottom\")\n\ndev <- reext %>%\n    transmute(label = factor(label, levels = ord),\n              `vs Jones`  = abs(reext_abs - jones_abs),\n              `vs Davies` = abs(reext_abs - davies_abs)) %>%\n    pivot_longer(-label, names_to = \"comparison\", values_to = \"dev\")\np_dev <- ggplot(dev, aes(dev, label, fill = comparison)) +\n    geom_col(position = \"dodge\") +\n    scale_fill_manual(values = c(`vs Jones` = \"#2c7fb8\", `vs Davies` = \"#d95f0e\")) +\n    labs(x = \"|re-extracted − prior|  (Hedges d)\", y = NULL, fill = NULL,\n         title = \"Deviation from re-extraction\") +\n    theme_minimal(base_size = 11) +\n    theme(legend.position = \"bottom\", axis.text.y = element_blank())\np_db + p_dev\n```\n\n::: {.cell-output-display}\n![Left: each flagged effect size on the |Hedges d| axis — re-extracted (independent, from the PDF) vs Jones vs Davies; the re-extracted point sits on Jones in every case, with Davies displaced. Right: absolute deviation of each prior extraction from the re-extracted value.](extraction_validation_files/figure-html/fig-reext-1.png){#fig-reext width=1056}\n:::\n:::\n\n\n### Count agreement vs design agreement (and a correction to Jones)\n\nTo break the circularity we re-derive each effect size from a rule fixed by the\nstudy design alone — *before* looking at Jones — and report two things separately:\n**count agreement** (does our lnOR from the raw counts match Jones, i.e. did we\nread the paper the same way) and **design agreement** (does our variance and N\nmatch, i.e. did we model the design the same way). The rule has two branches:\n\n* **Real control group** — the 2×2 has distinct treatment and control cells (e.g.\n  *Dugatkin 1992*'s naïve non-observer group). A standard 2×2 odds ratio is valid:\n  $\\mathrm{Var}=1/A+1/B+1/C+1/D$, $N=A+B+C+D$.\n* **Single group vs 50 % chance** — the \"50/50 rule\" sets $C=D=n/2$. The\n  design-faithful estimator is the one-sample logit of the observed proportion:\n  $\\mathrm{Var}=1/A+1/B$, $N=A+B$. The 50/50 group is a *phantom* control: it\n  invents $n$ observations that were never collected and inflates the variance by\n  **exactly $4/n$** while doubling the reported $N$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreext2 <- reext %>%\n    mutate(\n        A = effectSizeSampleSizeA, B = effectSizeSampleSizeB,\n        C = effectSizeSampleSizeC, D = effectSizeSampleSizeD,\n        design = if_else(C == D, \"single group vs 50% chance\", \"real control group\"),\n        corr_var = if_else(design == \"real control group\",\n                           1/A + 1/B + 1/C + 1/D, 1/A + 1/B),\n        corr_N   = if_else(design == \"real control group\", A + B + C + D, A + B),\n        jones_var    = compare_jones_VlnOR,\n        count_agree  = abs(reext_d - jones_d) < 0.02,   # point estimate (lnOR × √3/π)\n        design_agree = abs(corr_var - jones_var) < 0.01\n    )\n\nreext2 %>% summarise(\n    `Effect sizes` = n(),\n    `Count agreement (lnOR matches Jones)`      = sum(count_agree),\n    `Design agreement (variance matches Jones)` = sum(design_agree)\n) %>% pivot_longer(everything(), names_to = \"Quantity\", values_to = \"n\") %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                                  |  n|\n|:-----------------------------------------|--:|\n|Effect sizes                              | 12|\n|Count agreement (lnOR matches Jones)      | 12|\n|Design agreement (variance matches Jones) |  7|\n\n\n:::\n:::\n\n\nCount agreement is complete; design agreement holds **only** for the real-control\nstudies, where a 2×2 is the correct model. The single-group studies disagree by\nconstruction — and the disagreement is Jones's $4/n$ phantom-control inflation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreext2 %>%\n    filter(design == \"single group vs 50% chance\") %>%\n    transmute(Study = label,\n              `our Var (1/A+1/B)` = round(corr_var, 4),\n              `+ 4/n`             = round(4/(A + B), 4),\n              `our Var + 4/n`     = round(corr_var + 4/(A + B), 4),\n              `Jones Var`         = round(jones_var, 4),\n              `our N` = corr_N,\n              Note = if_else(abs(corr_var + 4/(A + B) - jones_var) < 0.01,\n                             \"Jones inflated by phantom 50/50 control\",\n                             \"Jones used a different null\")) %>%\n    kable()\n```\n\n::: {.cell-output-display}\n\n\n|Study                    | our Var (1/A+1/B)|  + 4/n| our Var + 4/n| Jones Var| our N|Note                                    |\n|:------------------------|-----------------:|------:|-------------:|---------:|-----:|:---------------------------------------|\n|Dugatkin 1993 · Exp001   |            0.3922| 0.2000|        0.5922|    0.5922|    20|Jones inflated by phantom 50/50 control |\n|Dugatkin 1993 · Exp002   |            0.2083| 0.2000|        0.4083|    0.4083|    20|Jones inflated by phantom 50/50 control |\n|FowlerFinn 2015 · Exp001 |            1.1111| 0.4000|        1.5111|    1.5111|    10|Jones inflated by phantom 50/50 control |\n|FowlerFinn 2015 · Exp002 |            0.3667| 0.3636|        0.7303|    0.7303|    11|Jones inflated by phantom 50/50 control |\n|Howard 1998 · Exp001     |            0.2667| 0.2000|        0.4667|    0.6076|    20|Jones used a different null             |\n\n\n:::\n:::\n\n\nFor every single-group study except *Howard 1998*, `our Var + 4/n` reproduces\nJones's variance to the fourth decimal, confirming the inflation is the invented\ncontrol group rather than a different reading. *Howard 1998* is the exception\n(Jones used a different null), and our estimate is preferred there. So on the\nvs-chance studies the design-faithful re-derivation **corrects** Jones — smaller\nvariance, halved $N$ — rather than reproducing him: the earlier \"matches Jones\nexactly\" was, for these studies, matching a 50/50-rule artifact. The corrected\n$N$ also reframes Davies's $N$ errors below: Davies's $N=40$ for *Dugatkin 1993*\nis wrong against the design-faithful $N=20$, not merely against Jones.\n\n### Why Davies diverges — four failure modes\n\nThe re-extraction shows the discrepancies are not random noise or conversion\nerror; they trace to four identifiable problems, all on the Davies side:\n\n1. **Different outcome construct.** For *Applebaum & Cruz 2000* and *Briggs et al.\n   1996*, Davies extracted a secondary **affiliation-time** measure (often\n   non-significant) rather than the **preference-reversal frequency** the studies\n   analyse; for *Howard et al. 1998* Davies extracted a **male-size preference** —\n   a different question entirely.\n2. **Computational artifacts.** *Dugatkin 1992*'s Davies *d* = 3.732 is exactly\n   **2 + √3**, the signature of a degenerate-2×2 `escalc` input; *Gierszewski et\n   al. 2018*'s *d* = 2.43 is inflated by the structural zero cell at first choice.\n3. **Sign error.** *Howard et al. 1998*: Davies records **+1.14** for a study that\n   found **no copying** (females retained their original preference 15:5); the\n   re-extraction and Jones both give **−0.61**.\n4. **Pool-vs-split, not an error.** *Fowler-Finn et al. 2015* is the one case where\n   neither is wrong: Davies pooled one effect (*d* 0.63) where Jones — and our\n   re-extraction — split it into a copying arm (*d* 1.21) and a no-copying arm\n   (*d* 0.10), matching the study's significant phenotype × age interaction.\n\nA design subtlety surfaced during re-extraction: for *Dugatkin 1992* the copying\ntests are correctly compared against the study's **naïve control group**, not\nagainst chance. Under that (correct) design Davies's total **N = 40** is right —\nonly the *magnitude* (the 2 + √3 artifact) is wrong — while Jones's third recorded\nvalue for this study (lnOR 2.234) is spurious: it reproduces from no pair of the\npaper's six experiments and should be dropped.\n\n## How many *unique* primary studies are there? {#sec-unique-studies}\n\nThe PRISMA flowchart counts 40 studies carried over from Jones & DuVal\n[-@jonesMechanismsSocialInfluence2019], 58 from Davies et al.\n[-@daviesMetaanalysisFactorsInfluencing2020] and 29 from our own extraction.\nThose three numbers do **not** sum to a count of unique primary studies, because\nthe sources overlap, which is worth making explicit.\nThis section resolves the corpus to distinct primary studies.\n\nA **study** here is one primary publication contributing at least one usable\neffect size. Three things have to be settled to count them:\n\n1. **Matches across sources.** No two sources share an identifier, so candidates\n   are generated from metadata and then adjudicated.\n2. **Duplicates *within* a source.** One source can carry the same primary study\n   under two identifiers.\n3. **Records that look like matches but are not** — same author, adjacent year,\n   same species, different paper.\n\n### Candidate generation, then explicit adjudication\n\nCandidates are generated deliberately generously: same first-author surname\nprefix (three letters, accent-folded) and publication year within ±1. Species is\nreported alongside but never used to *filter*, so no potential match is silently\ndiscarded. Every candidate the data produce is then resolved by hand — accepted\nor rejected, with the reason recorded — against the source records (authors,\nyear, species, sample size, outcome construct) and, where the two source teams\ndisagreed, against the primary PDFs already consulted for the\n[re-extraction](#sec-reextraction) above.\n\nThe adjudication is an explicit list rather than a threshold rule, and the code\n**fails loudly** if the data ever change such that a candidate is left\nunresolved, or a hand-coded decision no longer corresponds to a real candidate.\nThat way the count cannot drift silently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({library(readxl); library(dplyr); library(stringr); library(tidyr)})\n\ndeaccent    <- function(x) iconv(x, from = \"UTF-8\", to = \"ASCII//TRANSLIT\")\npfx3        <- function(surname) str_to_upper(str_sub(str_remove_all(deaccent(surname), \"[^A-Za-z]\"), 1, 3))\nepithet     <- function(x) str_to_lower(word(str_squish(as.character(x)), -1))\ncollapse_sp <- function(x) paste(sort(unique(epithet(x))), collapse = \"|\")\n\ninv_jones <- readr::read_csv(\n        here::here(\"data\", \"original_meta_analyses_datasets\", \"Jones_DuVal_2019_data.CSV\"),\n        show_col_types = FALSE) %>%\n    filter(!is.na(lnOR), !is.na(VlnOR), VlnOR > 0) %>%\n    group_by(study) %>%\n    summarise(year = as.integer(first(year)), species = collapse_sp(Species),\n              k = dplyr::n(), .groups = \"drop\") %>%\n    transmute(src = \"jones\", id = study, pfx = str_sub(study, 1, 3), year, species, k)\n\ninv_davies <- readxl::read_excel(\n        here::here(\"data\", \"original_meta_analyses_datasets\", \"Davies_et_al_2020_Final_data.xlsx\"),\n        sheet = \"Data\") %>%\n    mutate(yi = as.numeric(Hedges_d_directional), vi = as.numeric(Variance)) %>%\n    filter(!is.na(yi), !is.na(vi), vi > 0) %>%\n    group_by(Study_no, Author) %>%\n    summarise(year = as.integer(first(Year)), species = collapse_sp(Species_latin),\n              k = dplyr::n(), .groups = \"drop\") %>%\n    transmute(src = \"davies\", id = paste0(Author, \" [\", Study_no, \"]\"),\n              pfx = pfx3(word(Author, 1)), year, species, k)\n\ninv_new <- readxl::read_excel(\n        here::here(\"data\", \"1_effect_size_calculation_pipeline\",\n                   \"Data Extraction Mate Choice Meta Analysis.xlsx\"),\n        sheet = \"EduardoExtraction\") %>%\n    filter(is.na(RemoveFromDataset) | RemoveFromDataset != \"Yes\") %>%\n    group_by(identifierStudyId) %>%\n    summarise(year = as.integer(first(identifierStudyYear)),\n              species = collapse_sp(taxonomySpecies), k = dplyr::n(), .groups = \"drop\") %>%\n    transmute(src = \"new\", id = identifierStudyId,\n              pfx = pfx3(word(identifierStudyId, 1, sep = \"_\")), year, species, k)\n\ninventories <- bind_rows(inv_jones, inv_davies, inv_new)\n\ncandidate_pairs <- function(a, b, lab) {\n    inner_join(a, b, by = \"pfx\", suffix = c(\"_a\", \"_b\"), relationship = \"many-to-many\") %>%\n        filter(abs(year_a - year_b) <= 1) %>%\n        transmute(pair = lab, key = paste0(id_a, \" || \", id_b),\n                  id_a, year_a, species_a, k_a, id_b, year_b, species_b, k_b)\n}\ncands <- bind_rows(\n    candidate_pairs(inv_jones, inv_davies, \"Jones vs Davies\"),\n    candidate_pairs(inv_new,   inv_jones,  \"New vs Jones\"),\n    candidate_pairs(inv_new,   inv_davies, \"New vs Davies\")\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Accepted: these identifier pairs are the same primary study.\nACCEPT <- c(\n    \"APP2000THE || Applebaum and Cruz [3]\",\n    \"AUL2009DO || Auld et al [5]\",\n    \"BRI1996MAT || Briggs et al [10]\",\n    \"BRO1996COP || Brooks [11]\",\n    \"BRO1999MAT || Brooks [12]\",\n    \"DAG2016DRO || Dagaeff et al [15]\",\n    \"DAN2018CUL || Danchin et al [16]\",\n    \"DRU2008MAT || Drullion and Dubois [18]\",\n    \"DUG1992SEX || Dugatkin and Godin [27]\",\n    \"DUG1993FEM || Dugatkin and Godin [20]\",\n    \"DUG1998EFF || Dugatkin and Godin [22]\",\n    \"DUG1998GEN || Dugatkin [23]\",\n    \"DUG2003THE || Dugatkin et al [24]\",\n    \"FOR1996FEM || Forsgren et al [30]\",\n    \"FOW2015THE || Fowler-Finn et al [31]\",\n    \"GER2016MAT || Germain et al [35]\",\n    \"GIE2018MAT || Gierzewski et al [36]\",\n    \"GOD2009MAT || Godin and Hair [37]\",\n    \"GOL1993SEL || Goldschmidt et al [39]\",\n    \"GRA1996MAT || Grant and Green [42]\",\n    \"HOW1998MAT || Howard et al [46]\",\n    \"LAF1997FEM || Lafleur et al [52]\",\n    \"MAT2013FEM || Matsumoto and Takegaki [55]\",\n    \"MER2009PUB || Mery et al [57]\",\n    \"MIL2011NON || Milner et al [58]\",\n    \"MUN2004MAT || Munger et al [61]\",\n    \"NOB2018COP || Nobel et al [62]\",\n    \"PAT1998DO || Patriquin-Meldrum and Godin [67]\",\n    \"SLA1999MAT || Slagsvold and Viljugrein [73]\",\n    \"VUK2007SIZ || Vukomanovic and Rodd [76]\",\n    \"Moran_2013_Behaviour || Moran et al [48]\",\n    \"Ophir_2009_Unknown || Ophir and Galef [65]\"\n)\n# Rejected: generated as a candidate, but not the same study. Reason recorded.\nREJECT <- c(\n    \"DUG1992REV || Dugatkin and Godin [20]\" =\n        \"year mismatch (1992 vs 1993)\",\n    \"DUG1992REV || Dugatkin and Godin [27]\" =\n        \"Davies [27], labelled 'Dugatkin and Godin 1992', is in fact the single-authored Dugatkin (1992) and pairs with DUG1992SEX; DUG1992REV (Dugatkin and Godin 1992, choice reversal) has no Davies counterpart\",\n    \"DUG1992SEX || Dugatkin and Godin [20]\" =\n        \"year mismatch (1992 vs 1993)\",\n    \"DUG1993FEM || Dugatkin and Godin [27]\" =\n        \"year mismatch (1993 vs 1992)\",\n    \"DUG1998EFF || Dugatkin [23]\" =\n        \"DUG1998EFF pairs with the co-authored Davies [22]; Davies [23] is the single-authored Dugatkin (1998)\",\n    \"DUG1998GEN || Dugatkin and Godin [22]\" =\n        \"DUG1998GEN pairs with the single-authored Davies [23]\",\n    \"GIE2018USI || Gierzewski et al [36]\" =\n        \"GIE2018USI duplicates GIE2018MAT within Jones & DuVal (the same two reversal-vs-control contrasts under two study codes); folded into GIE2018MAT\",\n    \"NOB2018COP || Nobel et al [63]\" =\n        \"NOB2018COP pairs with Davies [62]; Davies [63] is the second Nobel et al. (2018) publication and is present in Davies only\",\n    \"Ophir_2009_Unknown || Ophir and Galef [66]\" =\n        \"the new-extraction record is Ophir and Galef (2003) Anim. Behav. 66:369-375 (DOI 10.1006/anbe.2003.2229; its n = 15 matches Davies [65] exactly). Davies [66] is their separate 2004 paper\"\n)\n# Duplicates within a single source: two identifiers, one primary study.\nWITHIN_SRC_DUP <- c(\"GIE2018USI\" = \"GIE2018MAT\")\n\nunresolved <- setdiff(cands$key, c(ACCEPT, names(REJECT)))\nstale      <- setdiff(c(ACCEPT, names(REJECT)), cands$key)\nif (length(unresolved))\n    stop(\"Unadjudicated candidate study pair(s) -- resolve each one explicitly:\\n  \",\n         paste(unresolved, collapse = \"\\n  \"))\nif (length(stale))\n    stop(\"Adjudication refers to pair(s) the data no longer generate:\\n  \",\n         paste(stale, collapse = \"\\n  \"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collapse accepted matches into canonical studies: connected components over\n# the accepted cross-source pairs plus the within-source duplicates.\nedges <- bind_rows(\n    tibble::tibble(a = str_split_fixed(ACCEPT, fixed(\" || \"), 2)[, 1],\n                   b = str_split_fixed(ACCEPT, fixed(\" || \"), 2)[, 2]),\n    tibble::tibble(a = names(WITHIN_SRC_DUP), b = unname(WITHIN_SRC_DUP))\n)\ncomp <- setNames(inventories$id, inventories$id)\nrepeat {\n    before <- comp\n    for (i in seq_len(nrow(edges))) {\n        r <- min(comp[[edges$a[i]]], comp[[edges$b[i]]])\n        comp[comp == comp[[edges$a[i]]] | comp == comp[[edges$b[i]]]] <- r\n    }\n    if (identical(before, comp)) break\n}\n\ncrosswalk <- inventories %>%\n    mutate(canonical = unname(comp[id])) %>%\n    group_by(canonical) %>%\n    summarise(\n        in_jones  = paste(sort(id[src == \"jones\"]),  collapse = \"; \"),\n        in_davies = paste(sort(id[src == \"davies\"]), collapse = \"; \"),\n        in_new    = paste(sort(id[src == \"new\"]),    collapse = \"; \"),\n        year      = min(year),\n        species   = paste(sort(unique(unlist(str_split(species, fixed(\"|\"))))), collapse = \"|\"),\n        k_jones   = sum(k[src == \"jones\"]),\n        k_davies  = sum(k[src == \"davies\"]),\n        k_new     = sum(k[src == \"new\"]),\n        .groups   = \"drop\"\n    ) %>%\n    mutate(n_sources = (in_jones != \"\") + (in_davies != \"\") + (in_new != \"\"),\n           membership = paste0(ifelse(in_jones  != \"\", \"J\", \"\"),\n                               ifelse(in_davies != \"\", \"D\", \"\"),\n                               ifelse(in_new    != \"\", \"N\", \"\"))) %>%\n    arrange(desc(n_sources), canonical)\n\nn_unique  <- nrow(crosswalk)\nn_jd      <- sum(crosswalk$membership == \"JD\")\nn_dn      <- sum(crosswalk$membership == \"DN\")\nn_jn      <- sum(crosswalk$membership == \"JN\")\nn_jdn     <- sum(crosswalk$membership == \"JDN\")\nn_j_only  <- sum(crosswalk$membership == \"J\")\nn_d_only  <- sum(crosswalk$membership == \"D\")\nn_n_only  <- sum(crosswalk$membership == \"N\")\nn_j_std   <- sum(crosswalk$in_jones  != \"\")\nn_d_std   <- sum(crosswalk$in_davies != \"\")\nn_n_std   <- sum(crosswalk$in_new    != \"\")\nn_naive   <- nrow(inv_jones) + nrow(inv_davies) + nrow(inv_new)\n\n# Deliverable for the PRISMA flowchart and for auditing.\ntryCatch({\n    d <- here::here(\"outputs\", \"3_original_dataset_crosscheck\")\n    dir.create(d, recursive = TRUE, showWarnings = FALSE)\n    readr::write_csv(crosswalk, file.path(d, \"study_crosswalk.csv\"))\n}, error = function(e) warning(\"Could not write study_crosswalk.csv: \", conditionMessage(e)))\n```\n:::\n\n\n### The reconciliation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-7783b4c56a4bf9d7f187\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7783b4c56a4bf9d7f187\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Reconciling the three source counts to unique primary studies.<\\/caption>\",\"data\":[[\"Jones &amp; DuVal (2019) study codes\",\"Jones &amp; DuVal distinct primary studies\",\"Davies et al. (2020) study records\",\"Davies et al. distinct primary studies\",\"New extraction distinct primary studies\",\"Naive sum of the three source counts\",\"Shared: Jones &amp; DuVal AND Davies et al.\",\"Shared: Davies et al. AND new extraction\",\"Shared: Jones &amp; DuVal AND new extraction\",\"Shared: all three sources\",\"Unique to Jones &amp; DuVal\",\"Unique to Davies et al.\",\"Unique to the new extraction\",\"UNIQUE PRIMARY STUDIES IN THE COMBINED CORPUS\"],[40,39,58,58,29,127,30,2,0,0,9,26,27,94]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Quantity<\\/th>\\n      <th>n<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":20,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":0},{\"className\":\"dt-center\",\"targets\":1},{\"name\":\"Quantity\",\"targets\":0},{\"name\":\"n\",\"targets\":1}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,20,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThe combined corpus contains **94 unique primary studies**, not the\n127 the three source counts suggest. The 33-study\ndifference comes from three places:\n\n* **30 studies are in both source meta-analyses.** This is the large\n  correction.\n* **2 studies in our new extraction were already in Davies et al.** —\n  Moran_2013_Behaviour and Ophir_2009_Unknown.\n  Both are pre-2019 papers that our multilingual search recovered independently\n  and that we re-extracted from the primary PDFs; each is counted once here.\n* **1 study code in Jones & DuVal duplicates**\n  another code in the same dataset (`GIE2018USI` repeats `GIE2018MAT`).\n\nThere is **no** overlap between our new extraction and Jones & DuVal\n(0 studies), and no study appears in all three sources.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-e616c22920f343582c45\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e616c22920f343582c45\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Every study present in more than one source. 'J' = Jones &amp; DuVal (2019), 'D' = Davies et al. (2020), 'N' = new extraction.<\\/caption>\",\"data\":[[\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"JD\",\"DN\",\"JD\",\"DN\",\"JD\",\"JD\",\"JD\"],[2000,2009,1996,1996,1999,2016,2018,2008,1992,1993,1998,1998,2003,1996,2015,2016,2018,2009,1993,1996,1998,1997,2013,2009,2011,2004,2013,2018,2003,1998,1999,2007],[\"perugiae\",\"serrata\",\"reticulata\",\"reticulata\",\"reticulata\",\"melanogaster\",\"melanogaster\",\"guttata\",\"reticulata\",\"reticulata\",\"reticulata\",\"reticulata\",\"reticulata\",\"minutu|minutus\",\"ocreata|schizocosa\",\"melanogaster\",\"latipinna\",\"reticulata\",\"aculeatus\",\"latipes\",\"latipes\",\"reticulata\",\"nitidus\",\"melanogaster\",\"mjoebergi\",\"nigrofasciata\",\"flabellare|zonale\",\"melanogaster\",\"japonica\",\"aculeatus\",\"hypoleuca\",\"reticulata\"],[\"APP2000THE\",\"AUL2009DO\",\"BRI1996MAT\",\"BRO1996COP\",\"BRO1999MAT\",\"DAG2016DRO\",\"DAN2018CUL\",\"DRU2008MAT\",\"DUG1992SEX\",\"DUG1993FEM\",\"DUG1998EFF\",\"DUG1998GEN\",\"DUG2003THE\",\"FOR1996FEM\",\"FOW2015THE\",\"GER2016MAT\",\"GIE2018MAT; GIE2018USI\",\"GOD2009MAT\",\"GOL1993SEL\",\"GRA1996MAT\",\"HOW1998MAT\",\"LAF1997FEM\",\"MAT2013FEM\",\"MER2009PUB\",\"MIL2011NON\",\"MUN2004MAT\",\"\",\"NOB2018COP\",\"\",\"PAT1998DO\",\"SLA1999MAT\",\"VUK2007SIZ\"],[\"Applebaum and Cruz [3]\",\"Auld et al [5]\",\"Briggs et al [10]\",\"Brooks [11]\",\"Brooks [12]\",\"Dagaeff et al [15]\",\"Danchin et al [16]\",\"Drullion and Dubois [18]\",\"Dugatkin and Godin [27]\",\"Dugatkin and Godin [20]\",\"Dugatkin and Godin [22]\",\"Dugatkin [23]\",\"Dugatkin et al [24]\",\"Forsgren et al [30]\",\"Fowler-Finn et al [31]\",\"Germain et al [35]\",\"Gierzewski et al [36]\",\"Godin and Hair [37]\",\"Goldschmidt et al [39]\",\"Grant and Green [42]\",\"Howard et al [46]\",\"Lafleur et al [52]\",\"Matsumoto and Takegaki [55]\",\"Mery et al [57]\",\"Milner et al [58]\",\"Munger et al [61]\",\"Moran et al [48]\",\"Nobel et al [62]\",\"Ophir and Galef [65]\",\"Patriquin-Meldrum and Godin [67]\",\"Slagsvold and Viljugrein [73]\",\"Vukomanovic and Rodd [76]\"],[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"Moran_2013_Behaviour\",\"\",\"Ophir_2009_Unknown\",\"\",\"\",\"\"],[\"2 / 4 / 0\",\"2 / 2 / 0\",\"2 / 2 / 0\",\"1 / 2 / 0\",\"1 / 6 / 0\",\"3 / 4 / 0\",\"17 / 2 / 0\",\"1 / 2 / 0\",\"2 / 2 / 0\",\"2 / 2 / 0\",\"4 / 4 / 0\",\"3 / 3 / 0\",\"2 / 4 / 0\",\"2 / 2 / 0\",\"2 / 1 / 0\",\"4 / 8 / 0\",\"4 / 2 / 0\",\"1 / 2 / 0\",\"1 / 1 / 0\",\"2 / 1 / 0\",\"1 / 1 / 0\",\"1 / 3 / 0\",\"1 / 2 / 0\",\"2 / 3 / 0\",\"1 / 1 / 0\",\"2 / 4 / 0\",\"0 / 4 / 4\",\"2 / 4 / 0\",\"0 / 1 / 4\",\"1 / 3 / 0\",\"1 / 1 / 0\",\"4 / 12 / 0\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Sources<\\/th>\\n      <th>Year<\\/th>\\n      <th>Species<\\/th>\\n      <th>Jones &amp; DuVal<\\/th>\\n      <th>Davies et al.<\\/th>\\n      <th>New extraction<\\/th>\\n      <th>k (J / D / N)<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Sources\",\"targets\":0},{\"name\":\"Year\",\"targets\":1},{\"name\":\"Species\",\"targets\":2},{\"name\":\"Jones & DuVal\",\"targets\":3},{\"name\":\"Davies et al.\",\"targets\":4},{\"name\":\"New extraction\",\"targets\":5},{\"name\":\"k (J / D / N)\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-a9a5f53d72e7a241c59a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a9a5f53d72e7a241c59a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Candidate pairs generated by the author-prefix/year rule and rejected on inspection. Listing them makes the judgement calls auditable rather than implicit.<\\/caption>\",\"data\":[[\"DUG1992REV || Dugatkin and Godin [20]\",\"DUG1992REV || Dugatkin and Godin [27]\",\"DUG1992SEX || Dugatkin and Godin [20]\",\"DUG1993FEM || Dugatkin and Godin [27]\",\"DUG1998EFF || Dugatkin [23]\",\"DUG1998GEN || Dugatkin and Godin [22]\",\"GIE2018USI || Gierzewski et al [36]\",\"NOB2018COP || Nobel et al [63]\",\"Ophir_2009_Unknown || Ophir and Galef [66]\"],[\"year mismatch (1992 vs 1993)\",\"Davies [27], labelled 'Dugatkin and Godin 1992', is in fact the single-authored Dugatkin (1992) and pairs with DUG1992SEX; DUG1992REV (Dugatkin and Godin 1992, choice reversal) has no Davies counterpart\",\"year mismatch (1992 vs 1993)\",\"year mismatch (1993 vs 1992)\",\"DUG1998EFF pairs with the co-authored Davies [22]; Davies [23] is the single-authored Dugatkin (1998)\",\"DUG1998GEN pairs with the single-authored Davies [23]\",\"GIE2018USI duplicates GIE2018MAT within Jones &amp; DuVal (the same two reversal-vs-control contrasts under two study codes); folded into GIE2018MAT\",\"NOB2018COP pairs with Davies [62]; Davies [63] is the second Nobel et al. (2018) publication and is present in Davies only\",\"the new-extraction record is Ophir and Galef (2003) Anim. Behav. 66:369-375 (DOI 10.1006/anbe.2003.2229; its n = 15 matches Davies [65] exactly). Davies [66] is their separate 2004 paper\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Candidate pair<\\/th>\\n      <th>Why it is not a match<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":12,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Candidate pair\",\"targets\":0},{\"name\":\"Why it is not a match\",\"targets\":1}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Supplementary table for the manuscript {#sec-supp-crosswalk}\n\nThe Results state that \"the full study-level crosswalk, with the reason recorded\nfor every accepted and rejected match, is provided in Supplementary\nInformation\". This chunk emits it as LaTeX so that claim is backed by a file\nthat ships with the manuscript.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nwrote supp_study_crosswalk.tex - 94 rows\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwrote supp_crosswalk_rejected.tex - 9 rows\n```\n\n\n:::\n:::\n\n\n---\n\n### Two judgement calls worth flagging\n\nNeither changes the count, but both are decisions rather than deductions.\n\n* **Which Jones & DuVal 1992 code pairs with Davies' 1992 record.** Davies'\n  study 27 is labelled \"Dugatkin and Godin 1992\" but carries the data of the\n  single-authored Dugatkin (1992), which is `DUG1992SEX`; `DUG1992REV` is then\n  Jones-only. Pairing them the other way round would swap which study is\n  Jones-only without altering any total, since 1992 contributes two distinct\n  publications either way.\n* **Treating `GIE2018USI` as a within-Jones duplicate.** This follows the\n  [re-extraction finding](#sec-reextraction) that the two codes carry the same\n  two reversal-vs-control contrasts. Counting them as two studies instead would\n  make the corpus 95 studies rather than 94.\n\nThe full study-level crosswalk, one row per unique study with its identifier in\neach source, is written to\n`outputs/3_original_dataset_crosscheck/study_crosswalk.csv` for the PRISMA\nflowchart and for auditing.\n\n---\n\n## Summary of the cross-check\n\nFour findings emerge from the comparison, and they are the basis for the\nsensitivity analyses reported elsewhere in this supplement.\n\n* **Re-extraction (the > 0.5 set).** Returning to the source PDFs for the\n  12 effect sizes that disagreed most, the design-blind re-derivation\n  reproduced the **point estimates** wherever the data are discrete counts (mean\n  |Δ*d*| vs Jones = 0.00; vs Davies = 0.83), **corrected** Jones\n  on the single-group / vs-chance studies (a 4/n phantom-control variance inflation\n  from the 50/50 rule, with halved *N*), and isolated **Davies** as the divergent\n  extraction — via different outcome constructs, `escalc` artifacts, a sign error,\n  and one defensible pool-vs-split. This is an independent re-derivation, **not** a\n  validation against Jones: the point-estimate agreement is expected for discrete\n  counts and the variance was no longer reverse-engineered to match.\n* **Overlap.** Of 37 Jones & DuVal studies,\n  **29 are shared** with Davies; 8 are unique to\n  Jones (28 effect sizes). Those counts key on\n  (author prefix, year), which merges the two distinct Dugatkin 1998\n  publications into one; the [study-level crosswalk](#sec-unique-studies)\n  separates them and puts the shared count at 30.\n* **Unique primary studies.** Resolving all three sources to distinct\n  publications gives **94 unique primary studies**, not the\n  127 implied by summing the source counts: 30 studies sit in\n  both source meta-analyses, 2 of our new studies were already in\n  Davies et al., and one Jones & DuVal study code is an internal duplicate.\n* **Agreement.** Across 52 comparable effect-size pairs, Jones-converted\n  and Davies magnitudes correlate at Pearson *r* = 0.79\n  (65% within tolerance), rising to\n  *r* = 0.89 among studies where both teams extracted\n  the same number of effect sizes.\n* **Direction of disagreement.** Mean Bland–Altman bias =\n  -0.14 *d*-units, indicating Davies reports\n  slightly larger magnitudes on\n  average; most large discrepancies trace to **different outcomes extracted**\n  (behaviour-type columns) or **different effect-size partitioning**, not to the\n  metric conversion.\n```\n",
    "supporting": [
      "extraction_validation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.js\"></script>\n<link href=\"../../site_libs/selectize-0.12.0/selectize.bootstrap3.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/selectize-0.12.0/selectize.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}