{
  "hash": "c3e0604997952ff5f640373607afe763",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Publication Bias Diagnostics\"\nsubtitle: \"Small-Study Effects and Time-Lag Bias in Mate-Choice Copying (MCC) Meta-Analyses\"\nauthor: \"Eduardo S. A. Santos & Collaborators\"\ndate: today\nbibliography: ../../references.bib\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n---\n\n\n\n## Introduction & Methodology\n\nPublication bias is a critical threat to the validity of meta-analytic syntheses. If studies with statistically non-significant or small effects are systematically omitted from the literature, the pooled meta-analytic summary will be biased upward.\n\nTo thoroughly evaluate the presence of publication bias and report-level selection in our Mate-Choice Copying (MCC) dataset, we employ three complementary diagnostic approaches, keeping the exact multilevel modeling logic (e.g., nested random intercepts and taxonomy control) used in our main overall effect calculations:\n\n1. **Visual Inspection (Funnel Plots):** We plot effect size estimates against their precision (inverse of the standard error, $1/\\text{SE}$) to check for visual asymmetry around the overall mean estimate.\n2. **Egger's Meta-Regression (Small-Study Effects):** We test whether study precision significantly moderates effect size. Following the recommendations of @nakagawaMethodsTestingPublication2022 and Stanley [-@stanleyMetaregressionAnalysisEconomics2012; -@stanleyMetaregressionApproximationsReduce2014], we implement a **two-step approach**:\n   * We first fit the Egger regression with the standard error ($\\text{SE} = \\sqrt{v_i}$) as the moderator. The slope tests for small-study effects, and the intercept estimates the effect that a perfectly precise study ($\\text{SE} = 0$) would report.\n   * When that intercept is statistically significant — i.e., a genuine non-zero effect is likely present — the standard-error version is known to under-estimate the true effect. We therefore re-fit the regression with the sampling variance ($\\text{V} = v_i$) as the moderator, which gives a less biased estimate of the bias-adjusted overall mean.\n3. **Decline Effect / Time-Lag Bias:** We test whether effect sizes shrink over time by adding publication year (mean-centered) to our models while simultaneously controlling for study precision.\n4. **Bias-Corrected Meta-Analytic Means (Method Comparison):** Finally, we estimate the *adjusted* overall mean under two complementary correction frameworks and compare them directly. The **current** approach follows @nakagawaMethodsTestingPublication2022: the intercept of a multilevel meta-regression on the sampling variance ($v_i$) is interpreted as the mean when sampling error is zero (i.e., an infinitely precise study). The **new** approach follows @yangRobustPointVariance2024: a *bias-robust* weighting scheme (a fixed-/common-effect GLS estimator that is less susceptible to selective reporting) is combined with **cluster-robust (CR2) variance estimation** to handle the non-independence of effect sizes within studies. We overlay both corrected means on an orchard plot using `orchaRd::pub_bias_plot()`.\n\n---\n\n## Data Loading and Alignment\n\nWe read, clean, and align the new extractions and original datasets, extracting sample sizes and publication years to construct our precision and time-lag moderators.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Paths to datasets\npath_new <- here::here(\"data\", \"1_effect_size_calculation_pipeline\", \"Data Extraction Mate Choice Meta Analysis.xlsx\")\npath_davies <- here::here(\"data\", \"original_meta_analyses_datasets\", \"Davies_et_al_2020_Final_data.xlsx\")\npath_jones <- here::here(\"data\", \"original_meta_analyses_datasets\", \"Jones_DuVal_2019_data.CSV\")\n\n# A. Read raw spreadsheets\ndb_new_raw <- readxl::read_excel(path_new, sheet = \"EduardoExtraction\")\ndb_davies_raw <- readxl::read_excel(path_davies, sheet = \"Data\")\ndb_jones_raw <- readr::read_csv(path_jones)\n\n# A2. Species-name reconciliation + phylogenetic correlation matrices.\n# Ported verbatim from overall_effect.qmd so that every multilevel model in the\n# project shares one random-effects structure. The correlation matrices are\n# indexed by FULL species binomials; these maps reproduce the reconciliation in\n# scripts/2_phylogeny/build_phylogeny.R.\nrecode_new    <- c(\"Taeniopygia guttata castanotis\" = \"Taeniopygia guttata\")\nrecode_davies <- c(\"Schizocosa\" = \"Schizocosa ocreata\")\n\njones_binomial <- tibble::tribble(\n    ~family,            ~epithet,        ~species_phylo,\n    \"Adrianichthyidae\", \"latipes\",       \"Oryzias latipes\",\n    \"Blenniidae\",       \"nitidus\",       \"Rhabdoblennius nitidus\",\n    \"Gasterosteidae\",   \"aculeatus\",     \"Gasterosteus aculeatus\",\n    \"Gobiidae\",         \"minutu\",        \"Pomatoschistus minutus\",\n    \"Percidae\",         \"olmstedi\",      \"Etheostoma olmstedi\",\n    \"Poeciliidae\",      \"latipinna\",     \"Poecilia latipinna\",\n    \"Poeciliidae\",      \"nigrofasciata\", \"Limia nigrofasciata\",\n    \"Poeciliidae\",      \"perugiae\",      \"Limia perugiae\",\n    \"Poeciliidae\",      \"reticulata\",    \"Poecilia reticulata\",\n    \"Pomacentridae\",    \"leucogaster\",   \"Amblyglyphidodon leucogaster\",\n    \"Lycosidae\",        \"ocreata\",       \"Schizocosa ocreata\",\n    \"Estrildidae\",      \"guttata\",       \"Taeniopygia guttata\",\n    \"Icteridae\",        \"ater\",          \"Molothrus ater\",\n    \"Muscicapidae\",     \"hypoleuca\",     \"Ficedula hypoleuca\",\n    \"Drosophilidae\",    \"melanogaster\",  \"Drosophila melanogaster\",\n    \"Drosophilidae\",    \"serrata\",       \"Drosophila serrata\",\n    \"Ocypodidae\",       \"mjoebergi\",     \"Uca mjoebergi\"\n)\n\nread_phylo <- function(f) {\n    pth <- here::here(\"outputs\", \"2_phylogeny\", f)\n    if (file.exists(pth)) readRDS(pth) else NULL\n}\nphylo_cor_hedges <- read_phylo(\"phylo_cor_hedges_model.rds\")\nphylo_cor_or     <- read_phylo(\"phylo_cor_or_model.rds\")\n\n# Helper: return the random-effects list, the R argument and a levels-cleaned\n# copy of the data, adding the phylogenetic term only when every species level\n# is present in the correlation matrix. Falls back with a warning otherwise, so\n# a missing phylogeny degrades the fit rather than breaking the render.\nphylo_terms <- function(dat, phylo_cor, phylo_var = \"species_phylo\") {\n    base <- list(~ 1 | identifierStudyId, ~ 1 | identifierEffectSizeID, ~ 1 | taxonomySpecies)\n    if (is.null(phylo_cor) || !phylo_var %in% colnames(dat)) {\n        return(list(data = dat, random = base, R = NULL, used_phylo = FALSE))\n    }\n    sp <- unique(as.character(dat[[phylo_var]]))\n    missing_sp <- setdiff(sp, rownames(phylo_cor))\n    if (length(missing_sp) > 0) {\n        warning(\"Phylogenetic random effect skipped (species absent from correlation matrix): \",\n                paste(missing_sp, collapse = \", \"))\n        return(list(data = dat, random = base, R = NULL, used_phylo = FALSE))\n    }\n    dat[[phylo_var]] <- factor(as.character(dat[[phylo_var]]))\n    list(\n        data       = dat,\n        random     = c(base, list(stats::as.formula(paste0(\"~ 1 | \", phylo_var)))),\n        R          = stats::setNames(list(phylo_cor[sp, sp, drop = FALSE]), phylo_var),\n        used_phylo = TRUE\n    )\n}\n\n# B. Clean new extractions\ndb_new <- db_new_raw %>%\n    filter(is.na(RemoveFromDataset) | RemoveFromDataset != \"Yes\") %>%\n    mutate(\n        effectSizeCalculatedHedgesD = as.numeric(effectSizeCalculatedHedgesD),\n        effectSizeCalculatedHedgesDVariance = as.numeric(effectSizeCalculatedHedgesDVariance),\n        effectSizeCalculatedOddsRatio = as.numeric(effectSizeCalculatedOddsRatio),\n        effectSizeCalculatedOddsRatioVariance = as.numeric(effectSizeCalculatedOddsRatioVariance),\n        logOddsRatio = log(effectSizeCalculatedOddsRatio),\n        logOddsRatioVariance = effectSizeCalculatedOddsRatioVariance,\n        identifierStudyYear = as.numeric(identifierStudyYear),\n        controlN = as.numeric(controlN),\n        treatmentN = as.numeric(treatmentN),\n        effectSizesampleSize = as.numeric(effectSizesampleSize)\n    )\n\n# ---------------------------------------------------------------------------\n# 1. Hedges' g Dataset Alignment (Continuous)\n# ---------------------------------------------------------------------------\nhedges_new <- db_new %>%\n    filter(!is.na(effectSizeCalculatedHedgesD), !is.na(effectSizeCalculatedHedgesDVariance)) %>%\n    select(\n        yi = effectSizeCalculatedHedgesD,\n        vi = effectSizeCalculatedHedgesDVariance,\n        identifierStudyId,\n        identifierEffectSizeID,\n        taxonomySpecies,\n        Year = identifierStudyYear,\n        controlN,\n        treatmentN,\n        totalN = effectSizesampleSize\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_new),\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"New Extraction (Santos)\"\n    )\n\nhedges_davies <- db_davies_raw %>%\n    mutate(\n        Hedges_d_directional = as.numeric(Hedges_d_directional),\n        Variance = as.numeric(Variance),\n        Year = as.numeric(Year),\n        N_control = as.numeric(N_control),\n        N_treatment = as.numeric(N_treatment),\n        Total_n_analysis = as.numeric(Total_n_analysis),\n        .study_id = paste0(Author, \" [\", Study_no, \"]\")\n    ) %>%\n    filter(!is.na(Hedges_d_directional), !is.na(Variance), Variance > 0) %>%\n    select(\n        yi = Hedges_d_directional,\n        vi = Variance,\n        # Davies' own study identifier -- see the note in overall_effect.qmd:\n        # keying on `Author` merges separate publications by the same authors.\n        identifierStudyId = .study_id,\n        identifierEffectSizeID = Effect_size_no,\n        taxonomySpecies = Species_latin,\n        Year,\n        controlN = N_control,\n        treatmentN = N_treatment,\n        totalN = Total_n_analysis\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_davies),\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"Original (Davies 2020)\"\n    )\n\ndb_hedges <- bind_rows(hedges_new, hedges_davies) %>%\n    mutate(across(c(identifierStudyId, taxonomySpecies, species_phylo, Dataset_Source), as.factor))\n\n# ---------------------------------------------------------------------------\n# 2. Log Odds Ratio Dataset Alignment (Binary)\n# ---------------------------------------------------------------------------\nor_new <- db_new %>%\n    filter(!is.na(logOddsRatio), !is.na(logOddsRatioVariance)) %>%\n    select(\n        yi = logOddsRatio,\n        vi = logOddsRatioVariance,\n        identifierStudyId,\n        identifierEffectSizeID,\n        taxonomySpecies,\n        Year = identifierStudyYear\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_new),\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"New Extraction (Santos)\"\n    )\n\nor_jones <- db_jones_raw %>%\n    filter(!is.na(lnOR), !is.na(VlnOR), VlnOR > 0) %>%\n    mutate(\n        family  = str_squish(as.character(Family)),\n        epithet = str_squish(as.character(Species))\n    ) %>%\n    # Rebuild the full binomial (species_phylo) from Family + epithet\n    left_join(jones_binomial, by = c(\"family\", \"epithet\")) %>%\n    select(\n        yi = lnOR,\n        vi = VlnOR,\n        identifierStudyId = study,\n        identifierEffectSizeID = study_Exp,\n        taxonomySpecies = Species,\n        species_phylo,\n        Year = year\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        taxonomySpecies = str_to_lower(as.character(taxonomySpecies)),\n        Dataset_Source = \"Original (Jones & DuVal 2019)\"\n    )\n\n# Sanity check: every Jones epithet should map to a full binomial\nif (any(is.na(or_jones$species_phylo))) {\n    warning(\n        \"Unmapped Jones epithets (phylogeny): \",\n        paste(unique(or_jones$taxonomySpecies[is.na(or_jones$species_phylo)]), collapse = \", \")\n    )\n}\n\ndb_or <- bind_rows(or_new, or_jones) %>%\n    mutate(across(c(identifierStudyId, taxonomySpecies, species_phylo, Dataset_Source), as.factor))\n```\n:::\n\n\n---\n\n## Study Inclusion & Exclusion {#sec-inclusion-pb}\n\nThe following tables document which effect sizes from the new extraction are included in the meta-analytic models and which have been removed, with the reason for each exclusion.\n\n### Excluded Effect Sizes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-dbd618b196b2bdf94a98\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-dbd618b196b2bdf94a98\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Effect sizes removed from the meta-analytic models and their reasons for exclusion.<\\/caption>\",\"data\":[[\"es0014\",\"es0015\",\"es0047\",\"es0048\",\"es0062\",\"es0063\",\"es0064\",\"es0066\",\"es0073\",\"es0074\"],[\"Harrison-Weiss_2025_AnimalBehaviour\",\"Huckvale_2016_UniversityOfExeter\",\"Nöbel_2022_ProceedingsOfTheRoyalSocietyBBiologicalSciences\",\"Nöbel_2022_ProceedingsOfTheRoyalSocietyBBiologicalSciences\",\"Plath_2008_CurrentBiology\",\"Plath_2008_CurrentBiology\",\"Plath_2009_BehavioralEcologyAndSociobiology\",\"Schütz_2000_JournalOfFishBiology\",\"Yang_2025_JournalOfAnimalEcology\",\"Ziege_2009_FrontiersInZoology\"],[2025,2016,2022,2022,2008,2008,2009,2000,2025,2009],[\"Duplicate data (same dataset as Harrison-Weiss_2024)\",\"Does not contain data to calculate effect sizes\",\"Does not contain data to calculate effect sizes\",\"Does not contain data to calculate effect sizes\",\"Focal subject is male; does not measure female mate-choice copying\",\"Does not contain data to calculate effect sizes (only overall GLM F-statistic)\",\"Audience effect on male preferences; does not measure female mate-choice copying\",\"Study design does not meet inclusion criteria (territorial visit counts, not mate preference)\",\"Does not measure mate-choice copying (social learning of mating tactics)\",\"Audience effect on male preference concealment; does not measure female mate-choice copying\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect Size ID<\\/th>\\n      <th>Study<\\/th>\\n      <th>Year<\\/th>\\n      <th>Exclusion Reason<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":20,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Effect Size ID\",\"targets\":0},{\"name\":\"Study\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Exclusion Reason\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,20,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Included Effect Sizes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-e3a2062878f1b39303a7\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e3a2062878f1b39303a7\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Effect sizes included in the meta-analytic models.<\\/caption>\",\"data\":[[\"es0001\",\"es0002\",\"es0003\",\"es0004\",\"es0005\",\"es0006\",\"es0007\",\"es0008\",\"es0009\",\"es0010\",\"es0011\",\"es0012\",\"es0013\",\"es0016\",\"es0017\",\"es0018\",\"es0019\",\"es0020\",\"es0021\",\"es0022\",\"es0023\",\"es0024\",\"es0025\",\"es0026\",\"es0027\",\"es0028\",\"es0029\",\"es0030\",\"es0031\",\"es0032\",\"es0033\",\"es0034\",\"es0035\",\"es0036\",\"es0037\",\"es0038\",\"es0039\",\"es0040\",\"es0041\",\"es0042\",\"es0043\",\"es0044\",\"es0045\",\"es0046\",\"es0049\",\"es0050\",\"es0051\",\"es0052\",\"es0053\",\"es0054\",\"es0055\",\"es0056\",\"es0057\",\"es0058\",\"es0059\",\"es0060\",\"es0061\",\"es0065\",\"es0067\",\"es0068\",\"es0069\",\"es0070\",\"es0071\",\"es0072\",\"es0075\",\"es0076\",\"es0077\",\"es0078\",\"es0079\",\"es0080\"],[\"Araújo_2024_RoyalSocietyOpenScience\",\"Araújo_2024_RoyalSocietyOpenScience\",\"Araújo_2024_RoyalSocietyOpenScience\",\"Belkina_2021_AnimalBehaviour\",\"Bierbach_2011_BehavioralEcologyAndSociobiology\",\"Bierbach_2011_BehavioralEcologyAndSociobiology\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Clemente_2012_UniversidadeLisboa\",\"Duffy_2025_AnimalBehaviour\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Kavaliers_2019_HormonesAndBehavior\",\"Kavaliers_2022_AnimalCognition\",\"Kniel_2015_FrontiersInZoology\",\"Kniel_2017_Ethology\",\"Kniel_2017_Ethology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"MacLaren_2019_Ethology\",\"MacLaren_2019_Ethology\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"Marcos_2019_ISPA\",\"Miller_2013_CarletonUniversity\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_ScientificReports\",\"Nöbel_2023_BehaviouralProcesses\",\"Nöbel_2023_Iscience\",\"Nöbel_2023_Iscience\",\"Nöbel_2025_BiologyLetters\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Pusiak_2020_AnimalBehaviour\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Witte_2018_Biology\",\"Witte_2018_Biology\",\"Ziege_2012_CurrentZoology\",\"Ziege_2012_CurrentZoology\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\"],[2024,2024,2024,2021,2011,2011,2023,2023,2012,2025,2024,2024,2024,2019,2022,2015,2017,2017,2026,2026,2026,2026,2026,2019,2019,2024,2024,2024,2024,2024,2019,2013,2025,2025,2025,2025,2025,2013,2013,2013,2013,2022,2022,2022,2022,2023,2023,2023,2025,2025,2025,2025,2025,2003,2003,2003,2003,2020,2014,2014,2014,2014,2018,2018,2012,2012,2023,2023,2023,2023],[\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Drosophila melanogaster\",\"Brachyrhaphis rhabdophora\",\"Porichthys notatus\",\"Porichthys notatus\",\"Porichthys notatus\",\"Mus musculus\",\"Mus musculus\",\"Taeniopygia guttata castanotis\",\"Taeniopygia guttata castanotis\",\"Taeniopygia guttata castanotis\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Drosophila melanogaster\",\"Poecilia reticulata\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Etheostoma zonale\",\"Etheostoma zonale\",\"Etheostoma flabellare\",\"Etheostoma flabellare\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Danio rerio\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila simulans\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Coturnix japonica\",\"Coturnix japonica\",\"Coturnix japonica\",\"Coturnix japonica\",\"Poecilia reticulata\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Enchenopa binotata\"],[\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Count data\",\"Mean difference\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Inferential statistics\",\"Inferential statistics\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Count data\",\"Inferential statistics\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\"],[-0.278,0.271,0.283,-0.008,0.659,0.288,-0.073,0.334,0.144,0.332,-0.376,0,0.596,0.699,0.575,-0.5669999999999999,-0.524,0.409,-1.762,-0.344,-1.405,-0.9399999999999999,-1.244,1.887,0.353,1.996,2.102,0.01,0.859,0.374,0.379,-0.636,0.374,0.223,0.279,0.286,-0.025,0.372,0.372,-0.07199999999999999,1.005,0.403,-0.166,0.61,0.413,-0.059,0.328,0.442,0.651,0.554,0.534,0.47,0.494,0.771,0.843,0.25,null,0.495,-0.761,0.8,0,0,-0.591,0.406,0.412,0.182,-0.218,-0.131,0.131,0.445],[0.6,1.643,1.68,0.986,3.304,1.686,0.876,1.833,1.3,1.826,0.5,1,3,4,3,0.358,0.386,2.101,0.041,0.536,0.078,0.182,0.105,30.672,1.896,37.323,45.276,1.019,4.752,1.972,2,0.316,1.978,1.502,1.668,1.684,0.955,2,2,0.875,6.5,2.095,0.737,3.062,2.13,0.898,1.826,2.25,3.264,2.765,2.667,2.368,2.474,4.052,4.615,1.573,null,2.466,0.25,4.294,1,1,0.328,2.154,2.111,1.39,0.673,0.788,1.269,2.243]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect Size ID<\\/th>\\n      <th>Study<\\/th>\\n      <th>Year<\\/th>\\n      <th>Species<\\/th>\\n      <th>Data Type<\\/th>\\n      <th>Hedges' g<\\/th>\\n      <th>OR<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":25,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Effect Size ID\",\"targets\":0},{\"name\":\"Study\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Species\",\"targets\":3},{\"name\":\"Data Type\",\"targets\":4},{\"name\":\"Hedges' g\",\"targets\":5},{\"name\":\"OR\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n---\n\n## Diagnostics by Effect Size Class\n\n::: {.panel-tabset}\n\n### Hedges' $g$ (Continuous outcomes)\n\nWe fit multilevel models on the continuous combined dataset ($k = 227$) to run our diagnostics.\n\n#### 1. Baseline Model & Funnel Plot\n\nWe run the intercept-only model to establish the global mean effect size and plot precision ($1/\\text{SE}$) against the standardized residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Intercept-only model\nVCV_hedges <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_hedges)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_hedges <- phylo_terms(db_hedges, phylo_cor_hedges)\n\nma_hedges <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_hedges,\n    random = pt_db_hedges$random,\n    R = pt_db_hedges$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_hedges$data\n)\n\nsummary(ma_hedges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-257.9500   515.9000   525.9000   543.0026   526.1727   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0525  0.2292     87     no       identifierStudyId   no \nsigma^2.2  0.3485  0.5904    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0096  0.0981     31     no         taxonomySpecies   no \nsigma^2.4  0.0163  0.1276     30     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 226) = 1389.2944, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub      \n  0.4537  0.0994  4.5651  29  <.0001  0.2504  0.6570  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract BLUPs for random effects\nblups <- ranef(ma_hedges)\nstudy_ef <- blups$identifierStudyId$intrcpt[match(db_hedges$identifierStudyId, row.names(blups$identifierStudyId))]\nobs_ef <- blups$identifierEffectSizeID$intrcpt[match(db_hedges$identifierEffectSizeID, row.names(blups$identifierEffectSizeID))]\nspec_ef <- blups$taxonomySpecies$intrcpt[match(db_hedges$taxonomySpecies, row.names(blups$taxonomySpecies))]\n\n# Handle any missing values by replacing with 0\nstudy_ef[is.na(study_ef)] <- 0\nobs_ef[is.na(obs_ef)] <- 0\nspec_ef[is.na(spec_ef)] <- 0\n\n# Marginal residuals: observed - fixed-effect prediction\nresid_marg <- db_hedges$yi - predict(ma_hedges)[[1]]\n\n# Conditional residuals: observed - fixed - random intercepts (study, obs, species)\nresid_cond <- db_hedges$yi - (predict(ma_hedges)[[1]] + study_ef + obs_ef + spec_ef)\n\n# Side-by-side funnel plots of marginal vs. conditional residuals,\n# with (a)/(b) panel tags. Drawn on-screen and saved to a manuscript PDF.\ndraw_funnels(resid_marg, resid_cond, db_hedges$vi)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/hedges_baseline_and_funnel-1.png){width=1152}\n:::\n\n```{.r .cell-code}\nsave_base_pdf(\n    \"funnel_hedges\",\n    function() draw_funnels(resid_marg, resid_cond, db_hedges$vi)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nquartz_off_screen \n                2 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Reading the funnel plots\"}\nBoth panels plot each effect size against its precision ($1/\\text{SE}$), but differ in what is removed before plotting:\n\n* **(a) Marginal residuals** are the deviations of each observed effect from the *fixed-effect (intercept) prediction* — the pooled mean — so they still carry all of the random-effects heterogeneity (between-study, between-effect-size, and between-species). Asymmetry here — a shortage of small, imprecise studies on one side of the funnel — is the classic visual signature of small-study and publication bias. Because genuine heterogeneity can mimic or exaggerate that asymmetry, apparent gaps in (a) should be read cautiously and confirmed against the formal Egger's regression below.\n* **(b) Conditional residuals** additionally subtract the estimated random intercepts (study, effect-size, and species BLUPs), so the heterogeneity captured by the multilevel structure is partialled out. A symmetric, evenly-filled funnel here means that once the nesting is accounted for there is little precision-related asymmetry left — i.e., the asymmetry seen in (a) is largely explained by the modelled random effects rather than by selective reporting. Any asymmetry that *persists* in (b) is the more credible visual indication of true small-study effects.\n:::\n\n#### 2. Egger's Meta-Regression (Small-Study Effects)\n\nTo perform Egger's regression on Hedges' $g$, we follow the two-step framework recommended by @nakagawaMethodsTestingPublication2022 and Stanley [-@stanleyMetaregressionAnalysisEconomics2012; -@stanleyMetaregressionApproximationsReduce2014]. We use the sampling standard error ($\\text{SE} = \\sqrt{v_i}$) as our precision proxy. If this moderator is statistically significant ($p < 0.05$), it indicates a significant small-study effect (larger standard errors / smaller sample sizes associated with larger effect magnitudes).\n\nWhen the intercept of the standard-error model is significant (a genuine non-zero effect is likely present), that intercept tends to under-estimate the true effect. We therefore apply the second step: re-fit Egger's regression with the sampling variance ($\\text{V} = \\text{vi}$) as the moderator, whose intercept gives a less biased estimate of the bias-adjusted overall mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate standard error precision proxy\ndb_hedges_egger <- db_hedges %>%\n    mutate(se = sqrt(vi)) %>%\n    filter(!is.na(se))\n\n# Re-estimate VCV on this subset\nVCV_hedges_egger <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_hedges_egger)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_hedges_egger <- phylo_terms(db_hedges_egger, phylo_cor_hedges)\n\n# Step 1: Egger regression model with standard error as moderator\negger_hedges <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_hedges_egger,\n    mods = ~ 1 + se,\n    random = pt_db_hedges_egger$random,\n    R = pt_db_hedges_egger$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_hedges_egger$data\n)\n\nsummary(egger_hedges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-230.1194   460.2388   472.2388   492.7355   472.6242   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0720  0.2683     87     no       identifierStudyId   no \nsigma^2.2  0.2635  0.5133    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0000  0.0001     31     no         taxonomySpecies   no \nsigma^2.4  0.0543  0.2330     30     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 225) = 1287.0869, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 225) = 58.4606, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb    ci.ub      \nintrcpt   -1.0341  0.2420  -4.2733   28  0.0002  -1.5298  -0.5384  *** \nse         4.8417  0.6332   7.6460  225  <.0001   3.5938   6.0895  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step 2: Since the intercept is significant, re-fit using variance (vi)\negger_hedges_v <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_hedges_egger,\n    mods = ~ 1 + vi,\n    random = pt_db_hedges_egger$random,\n    R = pt_db_hedges_egger$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_hedges_egger$data\n)\n\nsummary(egger_hedges_v)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-222.7861   445.5721   457.5721   478.0687   457.9574   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0532  0.2307     87     no       identifierStudyId   no \nsigma^2.2  0.2542  0.5042    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0014  0.0377     31     no         taxonomySpecies   no \nsigma^2.4  0.0255  0.1597     30     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 225) = 1232.5374, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 225) = 74.2988, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb   ci.ub      \nintrcpt   -0.2140  0.1323  -1.6179   28  0.1169  -0.4849  0.0569      \nvi         6.3236  0.7336   8.6197  225  <.0001   4.8779  7.7692  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe visualize the Egger regression using a bubble plot. Effect sizes are plotted as circles scaled by precision, with the predicted regression line showing the relationship between sample size and effect size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_egger_hedges <- orchaRd::bubble_plot(\n    egger_hedges,\n    mod = \"se\",\n    group = \"identifierStudyId\",\n    xlab = \"Standard Error of Hedges' g (se)\",\n    ylab = \"Effect size (Hedges' g)\"\n)\n\n# Color points by real source\np_egger_hedges$layers[[1]]$data$real_source <- db_hedges_egger$Dataset_Source\np_egger_hedges$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\np_egger_hedges$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\np_egger_hedges <- p_egger_hedges +\n    ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::ggtitle(\"Egger's Meta-Regression (Hedges' g)\") +\n    ggplot2::theme_minimal()\n\nprint(p_egger_hedges)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/hedges_egger_bubble_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The slope for standard error (`se`) is **positive** ($\\beta = 4.84$, $SE = 0.63$, $t = 7.65$, $p < 0.0001$), indicating clear evidence of small-study effects.\n>\n> **Two-Step Correction:** The intercept of the standard error model is statistically significant ($p = 0.000$). Following the two-step recommendation of @nakagawaMethodsTestingPublication2022 and Stanley [-@stanleyMetaregressionAnalysisEconomics2012; -@stanleyMetaregressionApproximationsReduce2014], we re-fit Egger's regression using the sampling variance (`vi`) as the moderator. In this corrected model, the adjusted overall meta-analytic mean is estimated at $\\beta_0 = -0.21$ ($SE = 0.13$, $t = -1.62$, $p = 0.117$).\n\n#### 3. Decline Effect (Time-Lag Bias)\n\nWe analyze the decline effect by evaluating whether the publication year significantly predicts the effect size, while simultaneously controlling for the study sample size precision proxy. We mean-center the year so the intercept represents the effect in an average publication year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean-center publication year\ndb_hedges_decline <- db_hedges_egger %>%\n    mutate(Year_c = Year - mean(Year, na.rm = TRUE))\n\n# VCV for decline subset\nVCV_hedges_decline <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_hedges_decline)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_hedges_decline <- phylo_terms(db_hedges_decline, phylo_cor_hedges)\n\n# Time-lag decline model controlling for sampling variance (vi)\ndecline_hedges <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_hedges_decline,\n    mods = ~ 1 + Year_c + vi,\n    random = pt_db_hedges_decline$random,\n    R = pt_db_hedges_decline$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_hedges_decline$data\n)\n\nsummary(decline_hedges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-221.7830   443.5660   457.5660   481.4476   458.0846   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0537  0.2318     87     no       identifierStudyId   no \nsigma^2.2  0.2543  0.5043    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0011  0.0338     31     no         taxonomySpecies   no \nsigma^2.4  0.0357  0.1889     30     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 224) = 1220.7194, p-val < .0001\n\nTest of Moderators (coefficients 2:3):\nF(df1 = 2, df2 = 84) = 37.4237, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb   ci.ub      \nintrcpt   -0.2186  0.1456  -1.5016   27  0.1448  -0.5172  0.0801      \nYear_c    -0.0047  0.0064  -0.7250   84  0.4705  -0.0175  0.0081      \nvi         6.3534  0.7477   8.4973  224  <.0001   4.8800  7.8268  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe construct the bubble plot showing the decline effect over years:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_decline_hedges <- orchaRd::bubble_plot(\n    decline_hedges,\n    mod = \"Year_c\",\n    group = \"identifierStudyId\",\n    xlab = \"Publication Year (centered)\",\n    ylab = \"Effect size (Hedges' g)\"\n)\n\n# Color points by real source\np_decline_hedges$layers[[1]]$data$real_source <- db_hedges_decline$Dataset_Source\np_decline_hedges$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\np_decline_hedges$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\np_decline_hedges <- p_decline_hedges +\n    ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\")\n\n# Relabel centered x-axis to actual calendar years\nmean_year_hedges <- mean(db_hedges_egger$Year, na.rm = TRUE)\ntarget_years_hedges <- seq(2000, 2026, by = 5)\n\np_decline_hedges_relabeled <- p_decline_hedges +\n    ggplot2::scale_x_continuous(\n        name = \"Publication Year\",\n        breaks = target_years_hedges - mean_year_hedges,\n        labels = target_years_hedges\n    ) +\n    ggplot2::ggtitle(\"Decline Effect / Time-Lag Bias (Hedges' g)\") +\n    ggplot2::theme_minimal()\n\nprint(p_decline_hedges_relabeled)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/hedges_decline_bubble_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The publication year slope is **non-significant** ($\\beta = 0.00$, $SE = 0.01$, $t = -0.73$, $p = 0.470$), indicating little evidence of a decline effect over time in continuous outcomes.\n\n#### 4. Unified Diagnostic Dashboard (Hedges' $g$)\n\nWe combine the Egger regression and publication year time-lag bubble plots into a single visual panel using `patchwork`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndashboard_hedges <- (p_egger_hedges / p_decline_hedges_relabeled) +\n    patchwork::plot_annotation(\n        title = \"Publication Bias Diagnostic — Hedges' g\",\n        tag_levels = \"a\", tag_prefix = \"(\", tag_suffix = \")\"\n    ) &\n    ggplot2::theme(\n        plot.title = ggplot2::element_text(size = 14, face = \"bold\", hjust = 0.5),\n        plot.tag = ggplot2::element_text(size = 12, face = \"bold\")\n    )\n\nprint(dashboard_hedges)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/hedges_unified_dashboard-1.png){width=960}\n:::\n\n```{.r .cell-code}\nsave_gg_pdf(dashboard_hedges, \"dashboard_eggers_timelag_hedges\", width = 10, height = 12)\n```\n:::\n\n\n---\n\n### Odds Ratio (Binary outcomes)\n\nWe fit multilevel models on the binary combined dataset ($k = 172$) to evaluate bias in Log Odds Ratio ($\\ln\\text{OR}$) studies.\n\n#### 1. Baseline Model & Funnel Plot\n\nWe run the intercept-only model for Odds Ratio and inspect the funnel plot representing log Odds Ratio values plotted against their precision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Intercept-only model\nVCV_or <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_or)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_or <- phylo_terms(db_or, phylo_cor_or)\n\nma_or <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_or,\n    random = pt_db_or$random,\n    R = pt_db_or$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_or$data\n)\n\nsummary(ma_or)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-229.2317   458.4635   468.4635   484.1718   468.8271   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0334  0.1828     69     no       identifierStudyId   no \nsigma^2.2  0.3543  0.5953    172     no  identifierEffectSizeID   no \nsigma^2.3  0.1864  0.4317     29     no         taxonomySpecies   no \nsigma^2.4  0.0083  0.0912     28     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 171) = 611.9869, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub      \n  0.5939  0.1466  4.0506  27  0.0004  0.2931  0.8948  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract BLUPs for random effects\nblups <- ranef(ma_or)\nstudy_ef <- blups$identifierStudyId$intrcpt[match(db_or$identifierStudyId, row.names(blups$identifierStudyId))]\nobs_ef <- blups$identifierEffectSizeID$intrcpt[match(db_or$identifierEffectSizeID, row.names(blups$identifierEffectSizeID))]\nspec_ef <- blups$taxonomySpecies$intrcpt[match(db_or$taxonomySpecies, row.names(blups$taxonomySpecies))]\n\n# Handle any missing values by replacing with 0\nstudy_ef[is.na(study_ef)] <- 0\nobs_ef[is.na(obs_ef)] <- 0\nspec_ef[is.na(spec_ef)] <- 0\n\n# Marginal residuals: observed - fixed-effect prediction\nresid_marg <- db_or$yi - predict(ma_or)[[1]]\n\n# Conditional residuals: observed - fixed - random intercepts (study, obs, species)\nresid_cond <- db_or$yi - (predict(ma_or)[[1]] + study_ef + obs_ef + spec_ef)\n\n# Side-by-side funnel plots of marginal vs. conditional residuals,\n# with (a)/(b) panel tags. Drawn on-screen and saved to a manuscript PDF.\ndraw_funnels(resid_marg, resid_cond, db_or$vi)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/or_baseline_and_funnel-1.png){width=1152}\n:::\n\n```{.r .cell-code}\nsave_base_pdf(\n    \"funnel_or\",\n    function() draw_funnels(resid_marg, resid_cond, db_or$vi)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nquartz_off_screen \n                2 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Reading the funnel plots\"}\nBoth panels plot each $\\ln\\text{OR}$ effect size against its precision ($1/\\text{SE}$), but differ in what is removed before plotting:\n\n* **(a) Marginal residuals** are the deviations of each observed effect from the *fixed-effect (intercept) prediction* — the pooled mean — so they still carry all of the random-effects heterogeneity (between-study, between-effect-size, and between-species). Asymmetry here — a shortage of small, imprecise studies on one side of the funnel — is the classic visual signature of small-study and publication bias. Because genuine heterogeneity can mimic or exaggerate that asymmetry, apparent gaps in (a) should be read cautiously and confirmed against the formal Egger's regression below.\n* **(b) Conditional residuals** additionally subtract the estimated random intercepts (study, effect-size, and species BLUPs), so the heterogeneity captured by the multilevel structure is partialled out. A symmetric, evenly-filled funnel here means that once the nesting is accounted for there is little precision-related asymmetry left — i.e., the asymmetry seen in (a) is largely explained by the modelled random effects rather than by selective reporting. Any asymmetry that *persists* in (b) is the more credible visual indication of true small-study effects.\n:::\n\n#### 2. Egger's Meta-Regression (Small-Study Effects)\n\nFor Odds Ratio studies, we use the standard error ($\\text{SE} = \\sqrt{v_i}$) as our precision proxy in the two-step framework. If the standard error moderator slope is statistically significant ($p < 0.05$), it represents a significant small-study effect.\n\nAs with the continuous outcomes, we apply the second step when the intercept of the standard-error model is significant: we re-fit Egger's regression with the sampling variance ($\\text{V} = \\text{vi}$) as the moderator, whose intercept gives a less biased estimate of the bias-adjusted overall mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate standard error proxy\ndb_or_egger <- db_or %>%\n    mutate(se = sqrt(vi)) %>%\n    filter(!is.na(se))\n\n# Re-estimate VCV on this subset\nVCV_or_egger <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_or_egger)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_or_egger <- phylo_terms(db_or_egger, phylo_cor_or)\n\n# Step 1: Egger regression model with standard error as moderator\negger_or <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_or_egger,\n    mods = ~ 1 + se,\n    random = pt_db_or_egger$random,\n    R = pt_db_or_egger$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_or_egger$data\n)\n\nsummary(egger_or)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-216.8556   433.7111   445.7111   464.5259   446.2265   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0084  0.0918     69     no       identifierStudyId   no \nsigma^2.2  0.3207  0.5663    172     no  identifierEffectSizeID   no \nsigma^2.3  0.2114  0.4598     29     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     28     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 170) = 597.1982, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 170) = 22.5257, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb   ci.ub      \nintrcpt   -0.5716  0.2806  -2.0369   26  0.0520  -1.1485  0.0052    . \nse         2.1147  0.4456   4.7461  170  <.0001   1.2352  2.9943  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step-2: Since the intercept is significant, re-fit using variance (vi)\negger_or_v <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_or_egger,\n    mods = ~ 1 + vi,\n    random = pt_db_or_egger$random,\n    R = pt_db_or_egger$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_or_egger$data\n)\n\nsummary(egger_or_v)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-216.4096   432.8192   444.8192   463.6339   445.3345   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0001     69     no       identifierStudyId   no \nsigma^2.2  0.3252  0.5703    172     no  identifierEffectSizeID   no \nsigma^2.3  0.1502  0.3876     29     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     28     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 170) = 586.7741, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 170) = 23.5751, p-val < .0001\n\nModel Results:\n\n         estimate      se    tval   df    pval    ci.lb   ci.ub      \nintrcpt    0.1001  0.1617  0.6192   26  0.5411  -0.2322  0.4324      \nvi         1.4198  0.2924  4.8554  170  <.0001   0.8425  1.9970  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe visualize the Egger regression for Odds Ratio using a bubble plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_egger_or <- orchaRd::bubble_plot(\n    egger_or,\n    mod = \"se\",\n    group = \"identifierStudyId\",\n    xlab = \"Standard Error of Log Odds Ratio (se)\",\n    ylab = \"Effect size (lnOR)\"\n)\n\n# Color points by real source\np_egger_or$layers[[1]]$data$real_source <- db_or_egger$Dataset_Source\np_egger_or$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\np_egger_or$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\np_egger_or <- p_egger_or +\n    ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::ggtitle(\"Egger's Meta-Regression (Log Odds Ratio)\") +\n    ggplot2::theme_minimal()\n\nprint(p_egger_or)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/or_egger_bubble_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The slope for the standard error is **positive** ($\\beta = 2.11$, $SE = 0.45$, $t = 4.75$, $p < 0.0001$), indicating pronounced small-study effects in binary mate-choice copying outcomes.\n>\n> **Two-Step Correction:** The intercept of the standard error model is non-significant ($p = 0.052$). Following the two-step framework, we re-fit the model using the sampling variance (`vi`) as the moderator to obtain a less biased estimate of the adjusted mean. In this corrected model, the adjusted overall log odds ratio is non-significant at $\\beta_0 = 0.10$ ($SE = 0.16$, $t = 0.62$, $p = 0.541$).\n\n#### 3. Decline Effect (Time-Lag Bias)\n\nWe test for a decline effect in the binary outcomes by regressing $\\ln\\text{OR}$ on centered publication year while simultaneously controlling for standard errors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean-center publication year\ndb_or_decline <- db_or_egger %>%\n    mutate(Year_c = Year - mean(Year, na.rm = TRUE))\n\n# VCV for decline subset\nVCV_or_decline <- metafor::vcalc(vi = vi, cluster = identifierStudyId, obs = identifierEffectSizeID, rho = 0.5, data = db_or_decline)\n\n# Phylogenetic random effect (see phylo_terms() in the data-prep chunk).\npt_db_or_decline <- phylo_terms(db_or_decline, phylo_cor_or)\n\n# Time-lag decline model controlling for sampling variance (vi)\ndecline_or <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_or_decline,\n    mods = ~ 1 + Year_c + vi,\n    random = pt_db_or_decline$random,\n    R = pt_db_or_decline$R,\n    test = \"t\",\n    dfs = \"contain\",\n    method = \"REML\",\n    sparse = TRUE,\n    data = pt_db_or_decline$data\n)\n\nsummary(decline_or)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-212.0418   424.0836   438.0836   459.9929   438.7793   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0000     69     no       identifierStudyId   no \nsigma^2.2  0.3154  0.5616    172     no  identifierEffectSizeID   no \nsigma^2.3  0.2490  0.4990     29     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     28     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 169) = 586.6984, p-val < .0001\n\nTest of Moderators (coefficients 2:3):\nF(df1 = 2, df2 = 66) = 15.0175, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb    ci.ub      \nintrcpt    0.0726  0.1772   0.4097   25  0.6855  -0.2923   0.4375      \nYear_c    -0.0279  0.0105  -2.6661   66  0.0096  -0.0488  -0.0070   ** \nvi         1.3189  0.3011   4.3800  169  <.0001   0.7245   1.9134  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe construct the bubble plot showing the decline effect for Odds Ratios:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_decline_or <- orchaRd::bubble_plot(\n    decline_or,\n    mod = \"Year_c\",\n    group = \"identifierStudyId\",\n    xlab = \"Publication Year (centered)\",\n    ylab = \"Effect size (lnOR)\"\n)\n\n# Color points by real source\np_decline_or$layers[[1]]$data$real_source <- db_or_decline$Dataset_Source\np_decline_or$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\np_decline_or$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\np_decline_or <- p_decline_or +\n    ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\") +\n    ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\")\n\n# Relabel centered x-axis to actual calendar years\nmean_year_or <- mean(db_or_egger$Year, na.rm = TRUE)\ntarget_years_or <- seq(2000, 2026, by = 5)\n\np_decline_or_relabeled <- p_decline_or +\n    ggplot2::scale_x_continuous(\n        name = \"Publication Year\",\n        breaks = target_years_or - mean_year_or,\n        labels = target_years_or\n    ) +\n    ggplot2::ggtitle(\"Decline Effect / Time-Lag Bias (Log Odds Ratio)\") +\n    ggplot2::theme_minimal()\n\nprint(p_decline_or_relabeled)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/or_decline_bubble_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The publication year slope is **statistically significant** ($\\beta = -0.03$, $SE = 0.01$, $t = -2.67$, $p = 0.010$). This provides evidence of a **decline effect (Time-Lag Bias)** in binary outcomes—the reported strength of mate-choice copying has decreased over the course of academic publication history.\n\n#### 4. Unified Diagnostic Dashboard (Log Odds Ratio)\n\nWe combine the Egger regression and publication year time-lag bubble plots into a single visual panel using `patchwork`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndashboard_or <- (p_egger_or / p_decline_or_relabeled) +\n    patchwork::plot_annotation(\n        title = \"Publication Bias Diagnostic — Log Odds Ratio\",\n        tag_levels = \"a\", tag_prefix = \"(\", tag_suffix = \")\"\n    ) &\n    ggplot2::theme(\n        plot.title = ggplot2::element_text(size = 14, face = \"bold\", hjust = 0.5),\n        plot.tag = ggplot2::element_text(size = 12, face = \"bold\")\n    )\n\nprint(dashboard_or)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/or_unified_dashboard-1.png){width=960}\n:::\n\n```{.r .cell-code}\nsave_gg_pdf(dashboard_or, \"dashboard_eggers_timelag_or\", width = 10, height = 12)\n```\n:::\n\n\n:::\n\n---\n\n## Bias-Corrected Meta-Analytic Means: Current vs. New Method\n\nThe diagnostics above *detect* small-study and time-lag bias. Here we turn to *correcting* the pooled mean, and we directly compare two correction philosophies on the same data.\n\n* **Current method — Nakagawa et al. [-@nakagawaMethodsTestingPublication2022] regression correction.** We re-use the multilevel meta-regression that includes the sampling variance ($v_i$) as a moderator (the Step-2 models `egger_hedges_v` / `egger_or_v` fitted above). Its **intercept** estimates the meta-analytic mean extrapolated to $v_i = 0$ — i.e., the effect a hypothetical infinitely-precise (infinite-$n$) study would report, with the small-study component removed. This is the *\"bias-corrected estimate\"* in @yangRobustPointVariance2024's terminology and in `orchaRd`.\n* **New method — Yang et al. [-@yangRobustPointVariance2024] bias-robust estimation.** A two-step procedure: (1) fit a **multivariate fixed-/common-effect** model whose weights come from the sampling variance–covariance matrix (**FE + VCV**, assuming $\\rho = 0.5$). This inverse-VCV weighting is the bias-robust ingredient: it is far less inflated by selectively-reported small studies than the random-effects mean, and it prevents studies contributing many correlated effect sizes from accumulating weight in proportion to their effect-size count. Then (2) apply **cluster-robust (CR2) variance estimation** (`clubSandwich`), clustering by study, so that standard errors and confidence intervals remain valid under the non-independence of multiple effect sizes per study. This is the *\"bias-robust estimate\"*. Note that the step-one model contains **no random effects**, which is why the CR2 correction is applicable here — CR2 is not valid for models with crossed random effects.\n\nWe compute both, overlay them on an orchard plot of the uncorrected multilevel mean with `orchaRd::pub_bias_plot()`, and tabulate the three estimates (uncorrected vs. the two corrections) side by side.\n\n::: {.panel-tabset}\n\n### Hedges' $g$ (Continuous outcomes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- New method: Yang et al. (2024) bias-robust estimate ---------------------\n# Step 1: multivariate common-/fixed-effect model with the sampling\n# variance-covariance matrix supplying the weights (\"FE + VCV\").\n#\n# The inverse-VCV weighting scheme IS the bias-robust part of the method: it\n# assigns smaller weights to imprecise studies reporting large effects, and it\n# stops a study contributing many correlated effect sizes from accumulating\n# weight in proportion to its effect-size count. Using rma(vi = vi) instead\n# would weight each effect size by 1/v_i independently, discarding the rho =\n# 0.5 within-study correlation assumed everywhere else in this workflow.\n#\n# rma.mv() with no `random` argument is the fixed-effect model (the fit reports\n# \"Variance Components: none\"); `method` is therefore immaterial here.\nVCV_hedges_fe <- metafor::vcalc(\n    vi = vi,\n    cluster = identifierStudyId,\n    obs = identifierEffectSizeID,\n    rho = 0.5,\n    data = db_hedges_egger\n)\n\nfe_hedges <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_hedges_fe,\n    data = db_hedges_egger,\n    method = \"REML\",\n    test = \"t\",\n    dfs = \"contain\",\n    sparse = TRUE\n)\n\n# Step 2: cluster-robust (CR2) variance estimation, clustering by study,\n# to account for non-independence of multiple effect sizes per study.\nfe_hedges_robust <- metafor::robust(\n    fe_hedges,\n    cluster = db_hedges_egger$identifierStudyId,\n    adjust = TRUE,\n    clubSandwich = TRUE\n)\n\nsummary(fe_hedges_robust)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-606.7987  1213.5973  1215.5973  1219.0178  1215.6152   \n\nVariance Components: none\n\nTest for Heterogeneity:\nQ(df = 226) = 1389.2944, p-val < .0001\n\nNumber of estimates:   227\nNumber of clusters:    87\nEstimates per cluster: 1-12 (mean: 2.61, median: 2)\n\nModel Results:\n\nestimate      se¹    tval¹     df¹    pval¹   ci.lb¹   ci.ub¹      \n  0.3350  0.0438   7.6477   45.37   <.0001   0.2468   0.4232   *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n1) results based on cluster-robust inference (var-cov estimator: CR2,\n   approx t-test and confidence interval, df: Satterthwaite approx)\n```\n\n\n:::\n\n```{.r .cell-code}\n# `egger_hedges_v` (fitted above) is the current-method Nakagawa et al. (2022)\n# vi-moderator model; its intercept is the bias-corrected mean at vi = 0.\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Orchard plot of the uncorrected multilevel meta-analytic mean ...\noc_hedges <- orchaRd::orchard_plot(\n    ma_hedges,\n    group = \"identifierStudyId\",\n    xlab = \"Hedges' g\",\n    angle = 0\n)\n\n# ... with both corrected means overlaid:\n#   red  = Yang et al. 2024 \"Bias Robust\"     (fixed-effect + CR2 robust)\n#   blue = Nakagawa et al. 2022 \"Bias Corrected\" (vi-moderator intercept)\np_pubbias_hedges <- orchaRd::pub_bias_plot(\n    oc_hedges,\n    fe_model = fe_hedges_robust,\n    v_model  = egger_hedges_v\n) +\n    ggplot2::ggtitle(\"Bias-Corrected Means — Hedges' g\") +\n    ggplot2::theme_minimal()\n\nprint(p_pubbias_hedges)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/hedges_pub_bias_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The uncorrected multilevel mean is $\\hat\\mu = 0.45$ (95% CI [0.25, 0.66]). The **current** Nakagawa correction gives a bias-corrected mean of $-0.21$ (95% CI [-0.48, 0.06]), and the **new** Yang bias-robust estimate is $0.34$ (95% CI [0.25, 0.42]).\n\n### Odds Ratio (Binary outcomes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- New method: Yang et al. (2024) bias-robust estimate ---------------------\n# Step 1: multivariate common-/fixed-effect model weighted by the sampling\n# variance-covariance matrix (\"FE + VCV\"). See the Hedges' g chunk above for\n# why the VCV, rather than diagonal 1/v_i weights, is what makes this estimator\n# bias-robust.\nVCV_or_fe <- metafor::vcalc(\n    vi = vi,\n    cluster = identifierStudyId,\n    obs = identifierEffectSizeID,\n    rho = 0.5,\n    data = db_or_egger\n)\n\nfe_or <- metafor::rma.mv(\n    yi = yi,\n    V = VCV_or_fe,\n    data = db_or_egger,\n    method = \"REML\",\n    test = \"t\",\n    dfs = \"contain\",\n    sparse = TRUE\n)\n\nfe_or_robust <- metafor::robust(\n    fe_or,\n    cluster = db_or_egger$identifierStudyId,\n    adjust = TRUE,\n    clubSandwich = TRUE\n)\n\nsummary(fe_or_robust)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-330.0733   660.1466   662.1466   665.2883   662.1703   \n\nVariance Components: none\n\nTest for Heterogeneity:\nQ(df = 171) = 611.9869, p-val < .0001\n\nNumber of estimates:   172\nNumber of clusters:    69\nEstimates per cluster: 1-17 (mean: 2.49, median: 2)\n\nModel Results:\n\nestimate      se¹    tval¹     df¹    pval¹   ci.lb¹   ci.ub¹      \n  0.5511  0.0770   7.1540   36.16   <.0001   0.3949   0.7074   *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n1) results based on cluster-robust inference (var-cov estimator: CR2,\n   approx t-test and confidence interval, df: Satterthwaite approx)\n```\n\n\n:::\n\n```{.r .cell-code}\n# `egger_or_v` (fitted above) is the current-method Nakagawa et al. (2022)\n# vi-moderator model; its intercept is the bias-corrected mean at vi = 0.\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noc_or <- orchaRd::orchard_plot(\n    ma_or,\n    group = \"identifierStudyId\",\n    xlab = \"Log Odds Ratio (lnOR)\",\n    angle = 0\n)\n\np_pubbias_or <- orchaRd::pub_bias_plot(\n    oc_or,\n    fe_model = fe_or_robust,\n    v_model  = egger_or_v\n) +\n    ggplot2::ggtitle(\"Bias-Corrected Means — Log Odds Ratio\") +\n    ggplot2::theme_minimal()\n\nprint(p_pubbias_or)\n```\n\n::: {.cell-output-display}\n![](publication_bias_files/figure-html/or_pub_bias_plot-1.png){width=864}\n:::\n:::\n\n\n> [!NOTE]\n> The uncorrected multilevel mean is $\\hat\\mu = 0.59$ (95% CI [0.29, 0.89]) on the $\\ln\\text{OR}$ scale. The **current** Nakagawa correction gives $0.10$ (95% CI [-0.23, 0.43]), and the **new** Yang bias-robust estimate is $0.55$ (95% CI [0.39, 0.71]).\n\n:::\n\n### Side-by-Side Comparison Table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-aeeacdec6db9e2faa019\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-aeeacdec6db9e2faa019\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Comparison of the uncorrected multilevel mean against the current (Nakagawa 2022) and new (Yang 2024) bias corrections. Estimates for the binary class are on the log-odds-ratio scale.<\\/caption>\",\"data\":[[\"Hedges' g (Continuous)\",\"Hedges' g (Continuous)\",\"Hedges' g (Continuous)\",\"Log Odds Ratio (Binary)\",\"Log Odds Ratio (Binary)\",\"Log Odds Ratio (Binary)\"],[\"Uncorrected (Multilevel mean)\",\"Bias-Corrected — Nakagawa 2022 (current; vi-intercept)\",\"Bias-Robust — Yang 2024 (new; FE + VCV, CR2)\",\"Uncorrected (Multilevel mean)\",\"Bias-Corrected — Nakagawa 2022 (current; vi-intercept)\",\"Bias-Robust — Yang 2024 (new; FE + VCV, CR2)\"],[0.4537016424219292,-0.2139781622387615,0.3350163545618301,0.5939197975408405,0.1001173033676138,0.5511488998532466],[0.09938576575901913,0.1322549381672457,0.04380643051452656,0.1466266085697417,0.1616755878915491,0.07704068112491202],[0.2504349282855258,-0.4848901221182362,0.24680556153184,0.2930668475494347,-0.2322116270533586,0.3949265473239137],[0.6569683565583326,0.05693379764071319,0.4232271475918202,0.8947727475322462,0.4324462337885861,0.7073712523825794],[8.48168454738124e-05,0.1168910166783748,1.071409449047066e-09,0.0003871136132857749,0.5411416265691606,2.014207149814253e-08],[null,-147.1627479892983,-26.15932515177569,null,-83.14295906919497,-7.201460174368543]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect_Class<\\/th>\\n      <th>Method<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>SE<\\/th>\\n      <th>CI_Lower<\\/th>\\n      <th>CI_Upper<\\/th>\\n      <th>p_value<\\/th>\\n      <th>Pct_Change_vs_Uncorrected<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":6,\"columnDefs\":[{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatSignif(data, 3, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Effect_Class\",\"targets\":0},{\"name\":\"Method\",\"targets\":1},{\"name\":\"Estimate\",\"targets\":2},{\"name\":\"SE\",\"targets\":3},{\"name\":\"CI_Lower\",\"targets\":4},{\"name\":\"CI_Upper\",\"targets\":5},{\"name\":\"p_value\",\"targets\":6},{\"name\":\"Pct_Change_vs_Uncorrected\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[6,10,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n> [!IMPORTANT]\n> **How to read the comparison.** Both corrections should pull the pooled estimate *toward zero* relative to the uncorrected multilevel mean if small-study/selective-reporting bias is present; the `Pct_Change_vs_Uncorrected` column quantifies that shrinkage. The two methods answer slightly different questions. The **Nakagawa** intercept is a *model-based extrapolation* to a perfectly precise study and tends to give wide confidence intervals (it is an out-of-range prediction). The **Yang** bias-robust estimate stays within the observed data, down-weights heterogeneity-driven inflation through fixed-effect weighting, and uses cluster-robust CR2 standard errors that explicitly respect the within-study dependence — making it a more conservative, inference-valid sensitivity analysis. Agreement between the two corrections strengthens confidence in the adjusted conclusion; divergence flags that the corrected mean is sensitive to modelling assumptions.\n\n---\n\n## Methodological Synthesis & Discussion\n\nWe compile the results of the small-study effect regressions and time-lag meta-regressions for both effect size classes below:\n\n### Publication Bias Comparison Table\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-53ad78131e3fe820e2f3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-53ad78131e3fe820e2f3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"Hedges' g (Continuous)\",\"Hedges' g (Continuous)\",\"Log Odds Ratio (Binary)\",\"Log Odds Ratio (Binary)\"],[\"Egger's Regression (Small-Study)\",\"Time-Lag (Decline Effect)\",\"Egger's Regression (Small-Study)\",\"Time-Lag (Decline Effect)\"],[\"Standard Error (se)\",\"Year_c (centered)\",\"Standard Error (se)\",\"Year_c (centered)\"],[4.841662796002155,-0.004666025810979565,2.114736538904287,-0.0278850817177021],[0.6332319801436992,0.006435798393025501,0.4455716115504827,0.01045904011159633],[7.645954322937761,-0.7250111836996254,4.746120453108557,-2.666122456762056],[5.973170759097947e-13,0.4704600215196109,4.377994266090393e-06,0.009639352852459418],[\"Highly Significant Bias (p &lt; 0.0001)\",\"No Significant Bias (p = 0.4705)\",\"Highly Significant Bias (p &lt; 0.0001)\",\"Significant Bias (p = 0.0096)\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect_Size_Class<\\/th>\\n      <th>Diagnostic_Test<\\/th>\\n      <th>Moderator<\\/th>\\n      <th>Slope_Beta<\\/th>\\n      <th>Std_Error<\\/th>\\n      <th>t_z_value<\\/th>\\n      <th>p_value<\\/th>\\n      <th>Evidence_of_Bias<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"columnDefs\":[{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatSignif(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Effect_Size_Class\",\"targets\":0},{\"name\":\"Diagnostic_Test\",\"targets\":1},{\"name\":\"Moderator\",\"targets\":2},{\"name\":\"Slope_Beta\",\"targets\":3},{\"name\":\"Std_Error\",\"targets\":4},{\"name\":\"t_z_value\",\"targets\":5},{\"name\":\"p_value\",\"targets\":6},{\"name\":\"Evidence_of_Bias\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Main Takeaways\n\n1. **Small-Study Effects:**\n   The Egger's regressions indicate statistically significant small-study effects for Hedges' $g$ ($p < 0.0001$) and statistically significant small-study effects for Log Odds Ratio ($p < 0.0001$). Where present, smaller and less precise trials systematically report larger mate-choice copying effect sizes—a classic signature of publication selection, in which small-sample studies are more likely to be published or reported if they find large, hypothesis-supportive effects.\n\n2. **Decline Effect (Time-Lag Bias) in Binary Outcomes:**\n   The publication-year trend for binary outcomes is statistically significant ($\\beta = -0.03$, $p = 0.010$). Over the last two decades, the reported strength of mate-choice copying (measured by Log Odds Ratios) has decreased, a pattern typical of fields experiencing a novelty effect in which early breakthrough publications report large effect sizes and subsequent rigorous replications reveal more moderate, realistic estimates.\n\n3. **Time Trend in Continuous Outcomes:**\n   For Hedges' $g$ (continuous), the publication-year trend is non-significant ($\\beta = 0.00$, $p = 0.470$). This suggests the continuous reporting scales have been relatively stable in magnitude over the history of the literature.\n\n4. **Bias-Corrected Means — Current vs. New Method:**\n   We compared two correction frameworks on the adjusted pooled mean. For Hedges' $g$, the **current** Nakagawa [-@nakagawaMethodsTestingPublication2022] $v_i$-intercept correction yields $-0.21$ while the **new** Yang [-@yangRobustPointVariance2024] bias-robust (FE + VCV, then CR2) estimate yields $0.34$ (uncorrected multilevel mean: $0.45$). For Log Odds Ratio, the corresponding values are $0.10$ (Nakagawa) and $0.55$ (Yang), against an uncorrected mean of $0.59$. The Yang bias-robust estimate is generally the more conservative, inference-valid option because it respects within-study dependence through cluster-robust variance estimation and avoids the wide-interval extrapolation inherent in the regression-intercept approach; where the two corrections agree, the adjusted conclusion is robust to modelling choice.\n\nThese diagnostic results suggest that while mate-choice copying is a genuine ecological phenomenon, the overall raw pooled estimates from both continuous and binary literatures may be moderately inflated due to selective reporting and publication biases. Future research should prioritize large-sample pre-registered replication studies to provide unbiased baselines.\n\n---\n\n## Session Info\n\n::: callout-note\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.0 (2026-04-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.5.2\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n\ntime zone: America/Edmonton\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] scales_1.4.0        DT_0.34.0           patchwork_1.3.2    \n [4] clubSandwich_0.7.0  orchaRd_2.2.0       metafor_5.0-1      \n [7] numDeriv_2016.8-1.1 metadat_1.6-0       Matrix_1.7-5       \n[10] lubridate_1.9.5     forcats_1.0.1       stringr_1.6.0      \n[13] dplyr_1.2.1         purrr_1.2.2         readr_2.2.0        \n[16] tidyr_1.3.2         tibble_3.3.1        ggplot2_4.0.3      \n[19] tidyverse_2.0.0     readxl_1.5.0       \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1   vipor_0.4.7        farver_2.1.2       S7_0.2.2          \n [5] fastmap_1.2.0      latex2exp_0.9.8    TH.data_1.1-5      pacman_0.5.1      \n [9] mathjaxr_2.0-0     digest_0.6.39      timechange_0.4.0   estimability_1.5.1\n[13] lifecycle_1.0.5    survival_3.8-6     magrittr_2.0.5     compiler_4.6.0    \n[17] rlang_1.2.0        sass_0.4.10        tools_4.6.0        yaml_2.3.12       \n[21] knitr_1.51         labeling_0.4.3     htmlwidgets_1.6.4  bit_4.6.0         \n[25] here_1.0.2         RColorBrewer_1.1-3 multcomp_1.4-30    withr_3.0.2       \n[29] grid_4.6.0         xtable_1.8-8       emmeans_2.0.3      MASS_7.3-65       \n[33] cli_3.6.6          mvtnorm_1.4-1      rmarkdown_2.31     crayon_1.5.3      \n[37] ragg_1.5.2         generics_0.1.4     otel_0.2.0         tzdb_0.5.0        \n[41] ggbeeswarm_0.7.3   cachem_1.1.0       splines_4.6.0      parallel_4.6.0    \n[45] cellranger_1.1.0   vctrs_0.7.3        sandwich_3.1-1     jsonlite_2.0.0    \n[49] hms_1.1.4          bit64_4.8.2        beeswarm_0.4.0     systemfonts_1.3.2 \n[53] crosstalk_1.2.2    jquerylib_0.1.4    glue_1.8.1         codetools_0.2-20  \n[57] stringi_1.8.7      gtable_0.3.6       pillar_1.11.1      htmltools_0.5.9   \n[61] R6_2.6.1           textshaping_1.0.5  rprojroot_2.1.1    vroom_1.7.1       \n[65] evaluate_1.0.5     lattice_0.22-9     bslib_0.11.0       coda_0.19-4.1     \n[69] nlme_3.1-169       mgcv_1.9-4         xfun_0.58          zoo_1.8-15        \n[73] pkgconfig_2.0.3   \n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "publication_bias_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}