{
  "hash": "f35e5e4292a373bb754f1092a45bf7b1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Overall Effect Size Calculation & Synthesis\"\nsubtitle: \"Meta-Analytic Update of Mate-Choice Copying (MCC)\"\nauthor: \"Eduardo S. A. Santos & Collaborators\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n---\n\n\n\n## Introduction & Project Update\n\nThis chapter calculates the overall effect size for the updated mate-choice copying (MCC) meta-analysis.\n\nWe combine three sources of data:\n\n1. **The new extraction:** our newly extracted and verified dataset of recent studies.\n2. **Original continuous dataset (@daviesMetaanalysisFactorsInfluencing2020):** standardised mean differences (Hedges' $d$) for continuous outcomes.\n3. **Original binary dataset (@jonesMechanismsSocialInfluence2019):** log odds ratios ($\\ln\\text{OR}$) for binary (choice) outcomes.\n\nThe R code below puts these sources onto common scales and then reports the meta-analytic summary for three subsets, so the new and original data can be compared:\n\n* **New extraction only:** the newly extracted dataset on its own.\n* **Original only:** the previously published data on its own.\n* **Combined:** the new and original data pooled together — the basis for the updated overall estimates.\n\n---\n\n## Data Loading and Alignment\n\nWe read the three datasets, perform data type conversions, extract species epithets for taxonomic control, and align columns into unified Hedges' $g$ and Odds Ratio datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------------------\n# 1. Load Datasets\n# ---------------------------------------------------------------------------\n\n# Paths to legacy and new datasets\npath_new <- here::here(\"data\", \"1_effect_size_calculation_pipeline\", \"Data Extraction Mate Choice Meta Analysis.xlsx\")\npath_davies <- here::here(\"data\", \"original_meta_analyses_datasets\", \"Davies_et_al_2020_Final_data.xlsx\")\npath_jones <- here::here(\"data\", \"original_meta_analyses_datasets\", \"Jones_DuVal_2019_data.CSV\")\n\n# A. Read new extraction dataset (EduardoExtraction sheet)\ndb_new_raw <- readxl::read_excel(path_new, sheet = \"EduardoExtraction\")\n\n# B. Read Davies et al. 2020 (Original continuous dataset)\ndb_davies_raw <- readxl::read_excel(path_davies, sheet = \"Data\")\n\n# C. Read Jones & DuVal 2019 (Original binary dataset)\ndb_jones_raw <- readr::read_csv(path_jones)\n\n# ---------------------------------------------------------------------------\n# 1b. Species-name reconciliation + phylogenetic correlation matrices\n# ---------------------------------------------------------------------------\n# The phylogenetic correlation matrices (built in scripts/2_phylogeny/\n# build_phylogeny.R) are indexed by FULL species binomials. The mappings below\n# reproduce that script's reconciliation so the `species_phylo` grouping in the\n# effect-size data matches the tree tip labels (and matrix dimnames) exactly.\nrecode_new    <- c(\"Taeniopygia guttata castanotis\" = \"Taeniopygia guttata\")\nrecode_davies <- c(\"Schizocosa\" = \"Schizocosa ocreata\")\n\n# Jones & DuVal store only the species EPITHET; rebuild full binomials from\n# Family + epithet (identical to build_phylogeny.R).\njones_binomial <- tibble::tribble(\n    ~family,            ~epithet,        ~species_phylo,\n    \"Adrianichthyidae\", \"latipes\",       \"Oryzias latipes\",\n    \"Blenniidae\",       \"nitidus\",       \"Rhabdoblennius nitidus\",\n    \"Gasterosteidae\",   \"aculeatus\",     \"Gasterosteus aculeatus\",\n    \"Gobiidae\",         \"minutu\",        \"Pomatoschistus minutus\",\n    \"Percidae\",         \"olmstedi\",      \"Etheostoma olmstedi\",\n    \"Poeciliidae\",      \"latipinna\",     \"Poecilia latipinna\",\n    \"Poeciliidae\",      \"nigrofasciata\", \"Limia nigrofasciata\",\n    \"Poeciliidae\",      \"perugiae\",      \"Limia perugiae\",\n    \"Poeciliidae\",      \"reticulata\",    \"Poecilia reticulata\",\n    \"Pomacentridae\",    \"leucogaster\",   \"Amblyglyphidodon leucogaster\",\n    \"Lycosidae\",        \"ocreata\",       \"Schizocosa ocreata\",\n    \"Estrildidae\",      \"guttata\",       \"Taeniopygia guttata\",\n    \"Icteridae\",        \"ater\",          \"Molothrus ater\",\n    \"Muscicapidae\",     \"hypoleuca\",     \"Ficedula hypoleuca\",\n    \"Drosophilidae\",    \"melanogaster\",  \"Drosophila melanogaster\",\n    \"Drosophilidae\",    \"serrata\",       \"Drosophila serrata\",\n    \"Ocypodidae\",       \"mjoebergi\",     \"Uca mjoebergi\"\n)\n\n# Phylogenetic correlation matrices (full binomials as dimnames). Loaded\n# defensively: if the phylogeny build has not been run, these are NULL and the\n# models gracefully fall back to a non-phylogenetic species random effect only.\nread_phylo <- function(f) {\n    p <- here::here(\"outputs\", \"2_phylogeny\", f)\n    if (file.exists(p)) readRDS(p) else NULL\n}\nphylo_cor_new    <- read_phylo(\"phylo_cor_new_extraction.rds\") # new-extraction tree\nphylo_cor_hedges <- read_phylo(\"phylo_cor_hedges_model.rds\")   # combined Hedges' g species\nphylo_cor_or     <- read_phylo(\"phylo_cor_or_model.rds\")       # combined log OR species\n\n# ---------------------------------------------------------------------------\n# 2. Process and Filter New Extraction\n# ---------------------------------------------------------------------------\ndb_new <- db_new_raw %>%\n    filter(is.na(RemoveFromDataset) | RemoveFromDataset != \"Yes\") %>%\n    mutate(\n        effectSizeCalculatedHedgesD = as.numeric(effectSizeCalculatedHedgesD),\n        effectSizeCalculatedHedgesDVariance = as.numeric(effectSizeCalculatedHedgesDVariance),\n        effectSizeCalculatedOddsRatio = as.numeric(effectSizeCalculatedOddsRatio),\n        effectSizeCalculatedOddsRatioVariance = as.numeric(effectSizeCalculatedOddsRatioVariance),\n        logOddsRatio = log(effectSizeCalculatedOddsRatio),\n        logOddsRatioVariance = effectSizeCalculatedOddsRatioVariance\n    )\n\n# ---------------------------------------------------------------------------\n# 3. Align Datasets for Hedges' g (Continuous SMD Analysis)\n# ---------------------------------------------------------------------------\n\n# A. Hedges' g from New Extraction\nhedges_new <- db_new %>%\n    filter(!is.na(effectSizeCalculatedHedgesD), !is.na(effectSizeCalculatedHedgesDVariance)) %>%\n    select(\n        yi = effectSizeCalculatedHedgesD,\n        vi = effectSizeCalculatedHedgesDVariance,\n        identifierStudyId,\n        identifierEffectSizeID,\n        taxonomySpecies\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        # Full binomial for the phylogeny (matches tree tip labels / matrix dimnames)\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_new),\n        # Extract species epithet (last word) and make lowercase for cross-dataset mapping\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"New Extraction (Santos)\"\n    )\n\n# B. Hedges' g from Davies et al. 2020 (Original)\nhedges_davies <- db_davies_raw %>%\n    mutate(\n        Hedges_d_directional = as.numeric(Hedges_d_directional),\n        Variance = as.numeric(Variance),\n        .study_id = paste0(Author, \" [\", Study_no, \"]\")\n    ) %>%\n    filter(!is.na(Hedges_d_directional), !is.na(Variance), Variance > 0) %>%\n    select(\n        yi = Hedges_d_directional,\n        vi = Variance,\n        # Davies' own study identifier. NOT `Author`: five author strings\n        # (\"Brooks\", \"Dugatkin and Godin\", \"Nobel et al\", \"Ophir and Galef\",\n        # \"White and Galef\") each cover 2-3 separate publications, so keying on\n        # Author merged 12 studies into 5, understated the study count by 7, and\n        # made vcalc() impose rho = 0.5 between effect sizes from DIFFERENT papers.\n        identifierStudyId = .study_id,\n        identifierEffectSizeID = Effect_size_no,\n        taxonomySpecies = Species_latin\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        # Full binomial for the phylogeny (matches tree tip labels / matrix dimnames)\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_davies),\n        # Extract species epithet (last word) and make lowercase\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"Original (Davies 2020)\"\n    )\n\n# C. Unified Hedges' g Dataset\ndb_hedges <- bind_rows(hedges_new, hedges_davies) %>%\n    mutate(across(c(identifierStudyId, taxonomySpecies, species_phylo, Dataset_Source), as.factor))\n\n# ---------------------------------------------------------------------------\n# 4. Align Datasets for Odds Ratio (Binary Analysis)\n# ---------------------------------------------------------------------------\n\n# A. Log Odds Ratio from New Extraction\nor_new <- db_new %>%\n    filter(!is.na(logOddsRatio), !is.na(logOddsRatioVariance)) %>%\n    select(\n        yi = logOddsRatio,\n        vi = logOddsRatioVariance,\n        identifierStudyId,\n        identifierEffectSizeID,\n        taxonomySpecies,\n        experimentalTypeSex\n    ) %>%\n    mutate(observer_sex = factor(str_squish(as.character(experimentalTypeSex)),\n                                 levels = c(\"Female\", \"Male\"))) %>%\n    select(-experimentalTypeSex) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        # Full binomial for the phylogeny (matches tree tip labels / matrix dimnames)\n        species_phylo = dplyr::recode(str_squish(as.character(taxonomySpecies)), !!!recode_new),\n        taxonomySpecies = str_to_lower(word(as.character(taxonomySpecies), -1)),\n        Dataset_Source = \"New Extraction (Santos)\"\n    )\n\n# B. Log Odds Ratio from Jones & DuVal 2019 (Original)\nor_jones <- db_jones_raw %>%\n    filter(!is.na(lnOR), !is.na(VlnOR), VlnOR > 0) %>%\n    mutate(\n        family  = str_squish(as.character(Family)),\n        epithet = str_squish(as.character(Species))\n    ) %>%\n    # Rebuild full binomial (species_phylo) from Family + epithet\n    left_join(jones_binomial, by = c(\"family\", \"epithet\")) %>%\n    select(\n        yi = lnOR,\n        vi = VlnOR,\n        identifierStudyId = study,\n        identifierEffectSizeID = study_Exp,\n        taxonomySpecies = Species,\n        species_phylo\n    ) %>%\n    mutate(\n        identifierStudyId = as.character(identifierStudyId),\n        identifierEffectSizeID = as.character(identifierEffectSizeID),\n        taxonomySpecies = str_to_lower(as.character(taxonomySpecies)),\n        # Jones & DuVal synthesised female mate-choice copying only, so their\n        # dataset carries no sex column: every observer is female by\n        # construction. Coding it explicitly is what makes the female-only\n        # sensitivity analysis below possible.\n        observer_sex = factor(\"Female\", levels = c(\"Female\", \"Male\")),\n        Dataset_Source = \"Original (Jones & DuVal 2019)\"\n    )\n\n# Sanity check: every Jones epithet should map to a full binomial\nif (any(is.na(or_jones$species_phylo))) {\n    warning(\n        \"Unmapped Jones epithets (phylogeny): \",\n        paste(unique(or_jones$taxonomySpecies[is.na(or_jones$species_phylo)]), collapse = \", \")\n    )\n}\n\n# C. Unified Log Odds Ratio Dataset\ndb_or <- bind_rows(or_new, or_jones) %>%\n    mutate(across(c(identifierStudyId, taxonomySpecies, species_phylo, Dataset_Source), as.factor))\n\n# Sanity check: observer sex must be complete in the analysed OR data, or the\n# female-only sensitivity analysis would silently drop rows of unknown sex.\nif (any(is.na(db_or$observer_sex))) {\n    warning(\"Missing observer sex in the log OR dataset: \",\n            sum(is.na(db_or$observer_sex)), \" effect size(s)\")\n}\n```\n:::\n\n\n---\n\n## Study Inclusion & Exclusion {#sec-inclusion}\n\nThe following tables document which effect sizes from the new extraction are included in the meta-analytic models and which have been removed, with the reason for each exclusion.\n\n### Excluded Effect Sizes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-78aa250bb589d79b1f76\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-78aa250bb589d79b1f76\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Effect sizes removed from the meta-analytic models and their reasons for exclusion.<\\/caption>\",\"data\":[[\"es0014\",\"es0015\",\"es0047\",\"es0048\",\"es0062\",\"es0063\",\"es0064\",\"es0066\",\"es0073\",\"es0074\"],[\"Harrison-Weiss_2025_AnimalBehaviour\",\"Huckvale_2016_UniversityOfExeter\",\"Nöbel_2022_ProceedingsOfTheRoyalSocietyBBiologicalSciences\",\"Nöbel_2022_ProceedingsOfTheRoyalSocietyBBiologicalSciences\",\"Plath_2008_CurrentBiology\",\"Plath_2008_CurrentBiology\",\"Plath_2009_BehavioralEcologyAndSociobiology\",\"Schütz_2000_JournalOfFishBiology\",\"Yang_2025_JournalOfAnimalEcology\",\"Ziege_2009_FrontiersInZoology\"],[2025,2016,2022,2022,2008,2008,2009,2000,2025,2009],[\"Duplicate data (same dataset as Harrison-Weiss_2024)\",\"Does not contain data to calculate effect sizes\",\"Does not contain data to calculate effect sizes\",\"Does not contain data to calculate effect sizes\",\"Focal subject is male; does not measure female mate-choice copying\",\"Does not contain data to calculate effect sizes (only overall GLM F-statistic)\",\"Audience effect on male preferences; does not measure female mate-choice copying\",\"Study design does not meet inclusion criteria (territorial visit counts, not mate preference)\",\"Does not measure mate-choice copying (social learning of mating tactics)\",\"Audience effect on male preference concealment; does not measure female mate-choice copying\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect Size ID<\\/th>\\n      <th>Study<\\/th>\\n      <th>Year<\\/th>\\n      <th>Exclusion Reason<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":20,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Effect Size ID\",\"targets\":0},{\"name\":\"Study\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Exclusion Reason\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,20,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Included Effect Sizes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-7133fc9a1a8e238a3b7c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7133fc9a1a8e238a3b7c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Effect sizes included in the meta-analytic models.<\\/caption>\",\"data\":[[\"es0001\",\"es0002\",\"es0003\",\"es0004\",\"es0005\",\"es0006\",\"es0007\",\"es0008\",\"es0009\",\"es0010\",\"es0011\",\"es0012\",\"es0013\",\"es0016\",\"es0017\",\"es0018\",\"es0019\",\"es0020\",\"es0021\",\"es0022\",\"es0023\",\"es0024\",\"es0025\",\"es0026\",\"es0027\",\"es0028\",\"es0029\",\"es0030\",\"es0031\",\"es0032\",\"es0033\",\"es0034\",\"es0035\",\"es0036\",\"es0037\",\"es0038\",\"es0039\",\"es0040\",\"es0041\",\"es0042\",\"es0043\",\"es0044\",\"es0045\",\"es0046\",\"es0049\",\"es0050\",\"es0051\",\"es0052\",\"es0053\",\"es0054\",\"es0055\",\"es0056\",\"es0057\",\"es0058\",\"es0059\",\"es0060\",\"es0061\",\"es0065\",\"es0067\",\"es0068\",\"es0069\",\"es0070\",\"es0071\",\"es0072\",\"es0075\",\"es0076\",\"es0077\",\"es0078\",\"es0079\",\"es0080\"],[\"Araújo_2024_RoyalSocietyOpenScience\",\"Araújo_2024_RoyalSocietyOpenScience\",\"Araújo_2024_RoyalSocietyOpenScience\",\"Belkina_2021_AnimalBehaviour\",\"Bierbach_2011_BehavioralEcologyAndSociobiology\",\"Bierbach_2011_BehavioralEcologyAndSociobiology\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Clemente_2012_UniversidadeLisboa\",\"Duffy_2025_AnimalBehaviour\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Harrison-Weiss_2024_McMasterUniversity\",\"Kavaliers_2019_HormonesAndBehavior\",\"Kavaliers_2022_AnimalCognition\",\"Kniel_2015_FrontiersInZoology\",\"Kniel_2017_Ethology\",\"Kniel_2017_Ethology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"Kobayashi_2026_JournalOfEthology\",\"MacLaren_2019_Ethology\",\"MacLaren_2019_Ethology\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"MacLaren_2024_PlosOne\",\"Marcos_2019_ISPA\",\"Miller_2013_CarletonUniversity\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Mitchell_2025_AmericanNaturalist\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Moran_2013_Behaviour\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_BehavioralEcology\",\"Nöbel_2022_ScientificReports\",\"Nöbel_2023_BehaviouralProcesses\",\"Nöbel_2023_Iscience\",\"Nöbel_2023_Iscience\",\"Nöbel_2025_BiologyLetters\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Nöbel_2025_ScientificReports\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Ophir_2009_Unknown\",\"Pusiak_2020_AnimalBehaviour\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Silva_2014_UniversidadeLisboa\",\"Witte_2018_Biology\",\"Witte_2018_Biology\",\"Ziege_2012_CurrentZoology\",\"Ziege_2012_CurrentZoology\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\",\"Cirino_2023_AnimalBehaviour\"],[2024,2024,2024,2021,2011,2011,2023,2023,2012,2025,2024,2024,2024,2019,2022,2015,2017,2017,2026,2026,2026,2026,2026,2019,2019,2024,2024,2024,2024,2024,2019,2013,2025,2025,2025,2025,2025,2013,2013,2013,2013,2022,2022,2022,2022,2023,2023,2023,2025,2025,2025,2025,2025,2003,2003,2003,2003,2020,2014,2014,2014,2014,2018,2018,2012,2012,2023,2023,2023,2023],[\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Drosophila melanogaster\",\"Brachyrhaphis rhabdophora\",\"Porichthys notatus\",\"Porichthys notatus\",\"Porichthys notatus\",\"Mus musculus\",\"Mus musculus\",\"Taeniopygia guttata castanotis\",\"Taeniopygia guttata castanotis\",\"Taeniopygia guttata castanotis\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia reticulata\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Poecilia latipinna\",\"Drosophila melanogaster\",\"Poecilia reticulata\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Etheostoma zonale\",\"Etheostoma zonale\",\"Etheostoma flabellare\",\"Etheostoma flabellare\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Danio rerio\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila simulans\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Drosophila melanogaster\",\"Coturnix japonica\",\"Coturnix japonica\",\"Coturnix japonica\",\"Coturnix japonica\",\"Poecilia reticulata\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Drosophila subobscura\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Poecilia mexicana\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Enchenopa binotata\",\"Enchenopa binotata\"],[\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Count data\",\"Mean difference\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Inferential statistics\",\"Inferential statistics\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Count data\",\"Inferential statistics\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Inferential statistics\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Count data\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\",\"Mean difference\"],[-0.278,0.271,0.283,-0.008,0.659,0.288,-0.073,0.334,0.144,0.332,-0.376,0,0.596,0.699,0.575,-0.5669999999999999,-0.524,0.409,-1.762,-0.344,-1.405,-0.9399999999999999,-1.244,1.887,0.353,1.996,2.102,0.01,0.859,0.374,0.379,-0.636,0.374,0.223,0.279,0.286,-0.025,0.372,0.372,-0.07199999999999999,1.005,0.403,-0.166,0.61,0.413,-0.059,0.328,0.442,0.651,0.554,0.534,0.47,0.494,0.771,0.843,0.25,null,0.495,-0.761,0.8,0,0,-0.591,0.406,0.412,0.182,-0.218,-0.131,0.131,0.445],[0.6,1.643,1.68,0.986,3.304,1.686,0.876,1.833,1.3,1.826,0.5,1,3,4,3,0.358,0.386,2.101,0.041,0.536,0.078,0.182,0.105,30.672,1.896,37.323,45.276,1.019,4.752,1.972,2,0.316,1.978,1.502,1.668,1.684,0.955,2,2,0.875,6.5,2.095,0.737,3.062,2.13,0.898,1.826,2.25,3.264,2.765,2.667,2.368,2.474,4.052,4.615,1.573,null,2.466,0.25,4.294,1,1,0.328,2.154,2.111,1.39,0.673,0.788,1.269,2.243]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Effect Size ID<\\/th>\\n      <th>Study<\\/th>\\n      <th>Year<\\/th>\\n      <th>Species<\\/th>\\n      <th>Data Type<\\/th>\\n      <th>Hedges' g<\\/th>\\n      <th>OR<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":25,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Effect Size ID\",\"targets\":0},{\"name\":\"Study\",\"targets\":1},{\"name\":\"Year\",\"targets\":2},{\"name\":\"Species\",\"targets\":3},{\"name\":\"Data Type\",\"targets\":4},{\"name\":\"Hedges' g\",\"targets\":5},{\"name\":\"OR\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n---\n\n## Dataset Composition Summary {#sec-composition}\n\nBefore inspecting the effect size distributions, we summarize how the aligned datasets are composed. The first table reports the number of studies (`k`) and effect sizes contributed by each original source and by our new extraction. The second table summarizes the number of effect sizes per species, ordered from most to least common.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine both aligned effect-size datasets, tagging the effect-size class.\n# Note: the New Extraction (Santos) contributes to BOTH the Hedges' g and the\n# Odds Ratio datasets; n_distinct() on study IDs therefore avoids double-counting\n# studies while total effect sizes are summed across classes.\ndb_summary_all <- bind_rows(\n    db_hedges %>% mutate(EffectType = \"Hedges' g\"),\n    db_or %>% mutate(EffectType = \"Log Odds Ratio\")\n) %>%\n    mutate(across(c(identifierStudyId, taxonomySpecies, Dataset_Source, EffectType), as.character))\n```\n:::\n\n\n### Studies & Effect Sizes by Source\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-e2049e813dd231a7af47\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e2049e813dd231a7af47\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Number of studies and effect sizes contributed by each data source.<\\/caption>\",\"data\":[[\"New Extraction (Santos)\",\"Original (Davies 2020)\",\"Original (Jones &amp; DuVal 2019)\",\"TOTAL\"],[29,58,40,127],[69,158,0,227],[69,0,103,172],[138,158,103,399],[15,23,17,36]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Data Source<\\/th>\\n      <th>Studies (k)<\\/th>\\n      <th>Hedges' g (ES)<\\/th>\\n      <th>Log OR (ES)<\\/th>\\n      <th>Total Effect Sizes<\\/th>\\n      <th>Species<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":10,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Data Source\",\"targets\":0},{\"name\":\"Studies (k)\",\"targets\":1},{\"name\":\"Hedges' g (ES)\",\"targets\":2},{\"name\":\"Log OR (ES)\",\"targets\":3},{\"name\":\"Total Effect Sizes\",\"targets\":4},{\"name\":\"Species\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Effect Sizes per Species\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-1b778ac598220c0f6507\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1b778ac598220c0f6507\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Number of effect sizes per species, ordered from most to least common.<\\/caption>\",\"data\":[[\"melanogaster\",\"reticulata\",\"latipinna\",\"mexicana\",\"japonica\",\"binotata\",\"aculeatus\",\"guttata\",\"subobscura\",\"castanotis\",\"flabellare\",\"nigrofasciata\",\"notatus\",\"perugiae\",\"zonale\",\"latipes\",\"leucogaster\",\"musculus\",\"serrata\",\"typhle\",\"dama\",\"nitidus\",\"norvegicus\",\"ater\",\"formosa\",\"holbrooki\",\"hypoleuca\",\"minutu\",\"minutus\",\"mjoebergi\",\"ocreata\",\"olmstedi\",\"rerio\",\"rhabdophora\",\"simulans\",\"schizocosa\"],[23,29,14,4,7,1,5,5,1,2,2,2,1,2,2,4,2,2,2,1,2,2,1,1,1,1,2,1,1,2,1,1,1,1,1,1],[50,54,28,9,11,6,6,7,4,3,4,4,3,4,4,2,0,2,2,4,3,2,3,0,2,2,1,0,2,1,0,0,1,1,1,1],[63,35,13,6,3,6,2,1,4,3,2,2,3,2,2,3,4,2,2,0,0,1,0,2,0,0,1,2,0,1,2,2,1,1,1,0],[113,89,41,15,14,12,8,8,8,6,6,6,6,6,6,5,4,4,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,1]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Species<\\/th>\\n      <th>Studies (k)<\\/th>\\n      <th>Hedges' g (ES)<\\/th>\\n      <th>Log OR (ES)<\\/th>\\n      <th>Total Effect Sizes<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"order\":[[3,\"desc\"]],\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Species\",\"targets\":0},{\"name\":\"Studies (k)\",\"targets\":1},{\"name\":\"Hedges' g (ES)\",\"targets\":2},{\"name\":\"Log OR (ES)\",\"targets\":3},{\"name\":\"Total Effect Sizes\",\"targets\":4}],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nIn total, the aligned data comprise 399 effect sizes from 127 studies across 36 species. The most-studied species is *Melanogaster* (113 effect sizes from 23 studies).\n\n---\n\n## Effect Size Distribution (Density Plots) {#sec-density}\n\nBefore fitting the multi-level models, we inspect the distribution of our aligned effect sizes across the different subsets (New Extraction, Original Only, and Combined). \n\nThe density plots below use the same split logic as the orchard plots in the result section, facet-wrapping by subset while coloring the distribution curves by their actual dataset source to check for shifts or outliers.\n\n::: {.panel-tabset}\n\n### Hedges' $g$ (Continuous SMD)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare density data for Hedges' g\ndb_hedges_density <- bind_rows(\n    db_hedges %>% mutate(Group = as.character(Dataset_Source)),\n    db_hedges %>% mutate(Group = \"Combined\")\n) %>%\n    mutate(Group = factor(Group, levels = c(\"New Extraction (Santos)\", \"Original (Davies 2020)\", \"Combined\")))\n\n# Plot densities\np_hedges_dens <- ggplot(db_hedges_density, aes(x = yi, fill = Dataset_Source, color = Dataset_Source)) +\n    geom_density(alpha = 0.4, linewidth = 0.8) +\n    geom_vline(xintercept = 0, linewidth = 1.0, linetype = \"solid\", color = \"black\") +\n    geom_rug(alpha = 0.6) +\n    facet_wrap(~Group, ncol = 1) +\n    scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n    scale_color_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n    labs(\n        title = \"Distribution of Hedges' g Effect Sizes\",\n        x = \"Hedges' g\",\n        y = \"Density\"\n    ) +\n    theme_minimal(base_size = 12) +\n    theme(\n        legend.position = \"bottom\",\n        strip.text = element_text(face = \"bold\", size = 11),\n        plot.title = element_text(face = \"bold\", hjust = 0.5)\n    )\n\nprint(p_hedges_dens)\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/hedges_density_plots-1.png){width=960}\n:::\n:::\n\n\n### Odds Ratio (Binary outcomes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare density data for Odds Ratio (lnOR)\ndb_or_density <- bind_rows(\n    db_or %>% mutate(Group = as.character(Dataset_Source)),\n    db_or %>% mutate(Group = \"Combined\")\n) %>%\n    mutate(Group = factor(Group, levels = c(\"New Extraction (Santos)\", \"Original (Jones & DuVal 2019)\", \"Combined\")))\n\n# Plot densities\np_or_dens <- ggplot(db_or_density, aes(x = yi, fill = Dataset_Source, color = Dataset_Source)) +\n    geom_density(alpha = 0.4, linewidth = 0.8) +\n    geom_vline(xintercept = 0, linewidth = 1.0, linetype = \"solid\", color = \"black\") +\n    geom_rug(alpha = 0.6) +\n    facet_wrap(~Group, ncol = 1) +\n    scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\") +\n    scale_color_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal 2019)\" = \"#0072B2\"), name = \"Data Source\") +\n    labs(\n        title = \"Distribution of Log Odds Ratio (lnOR) Effect Sizes\",\n        x = \"Log Odds Ratio (lnOR)\",\n        y = \"Density\"\n    ) +\n    theme_minimal(base_size = 12) +\n    theme(\n        legend.position = \"bottom\",\n        strip.text = element_text(face = \"bold\", size = 11),\n        plot.title = element_text(face = \"bold\", hjust = 0.5)\n    )\n\nprint(p_or_dens)\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/or_density_plots-1.png){width=960}\n:::\n:::\n\n\n:::\n\n---\n\n## Model Fitting Function\n\nThis helper function handles the variance–covariance (VCV) matrix construction and fits a multilevel random-effects model using `rma.mv()` in `metafor`. \n\n* **Variance–Covariance:** We construct a VCV matrix via `vcalc()` to handle dependencies among multiple effect sizes within the same study (assuming $r = 0.5$ for nested measurements).\n* **Random intercepts** are modeled for:\n\n  * Study (`identifierStudyId`)\n  * Individual trial/effect size (`identifierEffectSizeID`)\n  * Species (`taxonomySpecies`) — the *non-phylogenetic* species effect, capturing species-specific deviations not explained by shared ancestry\n  * Phylogeny (`species_phylo`) — a *phylogenetic* random effect supplied with a species-by-species correlation matrix (`R = list(species_phylo = phylo_cor)`) derived from the Open Tree of Life topology with Grafen branch lengths (see `scripts/2_phylogeny/build_phylogeny.R`). This partitions the among-species variance into a component attributable to phylogenetic relatedness and a residual species component.\n\nThe phylogenetic term is added to the **uncorrected** models only (for the New, Original, and Combined datasets); the small-study bias-corrected (Egger-type) models retain the original structure. When a phylogenetic correlation matrix is unavailable, the fit gracefully falls back to the non-phylogenetic structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_overall_mv <- function(dat, yi = \"yi\", vi = \"vi\", cluster_var = \"identifierStudyId\", obs_var = \"identifierEffectSizeID\", rho = 0.5, phylo_cor = NULL, phylo_var = \"species_phylo\") {\n    # Remove rows with missing values\n    dat2 <- dat %>%\n        filter(!is.na(.data[[yi]]), !is.na(.data[[vi]]), .data[[vi]] > 0)\n\n    if (nrow(dat2) == 0) {\n        message(\"No complete cases found.\")\n        return(NULL)\n    }\n\n    # 1. Build VCV Matrix\n    VCV <- metafor::vcalc(\n        vi = dat2[[vi]],\n        cluster = dat2[[cluster_var]],\n        obs = dat2[[obs_var]],\n        rho = rho,\n        data = dat2\n    )\n\n    # 2. Assemble random-effects structure. Always include study, effect-size,\n    #    and a (non-phylogenetic) species intercept. If a phylogenetic\n    #    correlation matrix is supplied AND every species level is present in it,\n    #    add a phylogenetic random effect with R = subset-of-correlation-matrix.\n    random_list <- list(\n        ~ 1 | identifierStudyId,\n        ~ 1 | identifierEffectSizeID,\n        ~ 1 | taxonomySpecies\n    )\n    R_arg <- NULL\n    used_phylo <- FALSE\n\n    if (!is.null(phylo_cor) && phylo_var %in% colnames(dat2)) {\n        sp <- unique(as.character(dat2[[phylo_var]]))\n        missing_sp <- setdiff(sp, rownames(phylo_cor))\n        if (length(missing_sp) == 0) {\n            # Subset the correlation matrix to the species actually present so the\n            # dimnames match the grouping levels exactly. Also drop any stale\n            # (unused) factor levels on the grouping column so metafor's level\n            # set matches the R-matrix dimnames.\n            dat2[[phylo_var]] <- factor(as.character(dat2[[phylo_var]]))\n            Csub <- phylo_cor[sp, sp, drop = FALSE]\n            random_list <- c(random_list, list(stats::as.formula(paste0(\"~ 1 | \", phylo_var))))\n            R_arg <- stats::setNames(list(Csub), phylo_var)\n            used_phylo <- TRUE\n        } else {\n            warning(\n                \"Phylogenetic random effect skipped (species absent from correlation matrix): \",\n                paste(missing_sp, collapse = \", \")\n            )\n        }\n    }\n\n    # 3. Fit Multi-Level Random-Effects Model\n    mod <- metafor::rma.mv(\n        yi = dat2[[yi]],\n        V = VCV,\n        random = random_list,\n        R = R_arg,\n        test = \"t\",\n        dfs = \"contain\",\n        method = \"REML\",\n        sparse = TRUE,\n        data = dat2\n    )\n\n    list(data = dat2, VCV = VCV, model = mod, used_phylo = used_phylo)\n}\n\n# Helper function to fit bias-corrected multilevel models with a continuous moderator (Egger-type)\n#\n# The random-effects structure MIRRORS fit_overall_mv(), including the optional\n# phylogenetic term. This matters: the headline contrast in the paper is the\n# uncorrected mean against this model's intercept at vi = 0, so the two fits must\n# differ only by the moderator, not by their random-effects structure.\nfit_corrected_mv <- function(dat, yi = \"yi\", vi = \"vi\", moderator = \"vi\", cluster_var = \"identifierStudyId\", obs_var = \"identifierEffectSizeID\", rho = 0.5,\n                             phylo_cor = NULL, phylo_var = \"species_phylo\") {\n    # Remove rows with missing values\n    dat2 <- dat %>%\n        filter(!is.na(.data[[yi]]), !is.na(.data[[vi]]), .data[[vi]] > 0)\n\n    if (nrow(dat2) == 0) {\n        message(\"No complete cases found.\")\n        return(NULL)\n    }\n\n    if (moderator == \"se\" && !\"se\" %in% colnames(dat2)) {\n        dat2 <- dat2 %>% mutate(se = sqrt(vi))\n    }\n\n    # 1. Build VCV Matrix\n    VCV <- metafor::vcalc(\n        vi = dat2[[vi]],\n        cluster = dat2[[cluster_var]],\n        obs = dat2[[obs_var]],\n        rho = rho,\n        data = dat2\n    )\n\n    # 2. Assemble the random-effects structure, adding the phylogenetic term when\n    #    a correlation matrix is supplied and every species level is present in it\n    #    (identical logic and fallback behaviour to fit_overall_mv).\n    random_list <- list(\n        ~ 1 | identifierStudyId,\n        ~ 1 | identifierEffectSizeID,\n        ~ 1 | taxonomySpecies\n    )\n    R_arg <- NULL\n    used_phylo <- FALSE\n\n    if (!is.null(phylo_cor) && phylo_var %in% colnames(dat2)) {\n        sp <- unique(as.character(dat2[[phylo_var]]))\n        missing_sp <- setdiff(sp, rownames(phylo_cor))\n        if (length(missing_sp) == 0) {\n            dat2[[phylo_var]] <- factor(as.character(dat2[[phylo_var]]))\n            Csub <- phylo_cor[sp, sp, drop = FALSE]\n            random_list <- c(random_list, list(stats::as.formula(paste0(\"~ 1 | \", phylo_var))))\n            R_arg <- stats::setNames(list(Csub), phylo_var)\n            used_phylo <- TRUE\n        } else {\n            warning(\n                \"Phylogenetic random effect skipped in bias-corrected model (species absent from correlation matrix): \",\n                paste(missing_sp, collapse = \", \")\n            )\n        }\n    }\n\n    # 3. Fit Multi-Level Egger Model using dynamic formula\n    formula_str <- paste(\"~ 1 +\", moderator)\n    mod <- metafor::rma.mv(\n        yi = dat2[[yi]],\n        V = VCV,\n        mods = as.formula(formula_str),\n        random = random_list,\n        R = R_arg,\n        test = \"t\",\n        dfs = \"contain\",\n        method = \"REML\",\n        sparse = TRUE,\n        data = dat2\n    )\n\n    list(data = dat2, VCV = VCV, model = mod, used_phylo = used_phylo)\n}\n\n# Helper function to add Mean (95% CI) labels dynamically one line above k-values in orchard plots\nadd_ci_labels <- function(plot_obj, orchard_results) {\n    est <- sprintf(\"%.2f\", orchard_results$mod_table$estimate)\n    ci_l <- sprintf(\"%.2f\", orchard_results$mod_table$lowerCL)\n    ci_u <- sprintf(\"%.2f\", orchard_results$mod_table$upperCL)\n\n    orig_labels <- plot_obj$layers[[6]]$aes_params$label\n\n    new_labels <- c()\n    for (i in 1:length(orig_labels)) {\n        # Extract the original sample size numbers using regex\n        nums <- regmatches(orig_labels[i], gregexpr(\"[0-9]+\", orig_labels[i]))[[1]]\n        if (length(nums) >= 2) {\n            k_val <- nums[1]\n            n_val <- nums[2]\n            k_text <- paste0(\"k = \", k_val, \" (\", n_val, \")\")\n        } else {\n            k_text <- orig_labels[i]\n        }\n        # Place Mean (95% CI) on the first line and k = xx (xx) on the second line\n        new_labels[i] <- paste0(est[i], \" [\", ci_l[i], \", \", ci_u[i], \"]\\n\", k_text)\n    }\n\n    plot_obj$layers[[6]]$aes_params$label <- new_labels\n    plot_obj$layers[[6]]$geom_params$parse <- FALSE\n    plot_obj$layers[[6]]$aes_params$hjust <- \"right\"\n    plot_obj$layers[[6]]$aes_params$vjust <- 0.5\n    plot_obj$layers[[6]]$aes_params$size <- 3.0 # Slightly smaller font size to fit better\n\n    plot_obj\n}\n```\n:::\n\n\n---\n\n## Multi-Level Synthesis Results\n\nWe fit the multilevel meta-analysis across all three database splits (New Only, Original Only, and Combined) for both effect size classes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------------------\n# HEDGES' G MODELS (UNCORRECTED) — now incorporating phylogenetic relatedness\n# ---------------------------------------------------------------------------\n# New-only uses the new-extraction tree; Original-only and Combined use the\n# combined Hedges' g tree (Davies species are a subset of the combined tree).\nres_hedges_new <- fit_overall_mv(db_hedges %>% filter(Dataset_Source == \"New Extraction (Santos)\"), phylo_cor = phylo_cor_new)\nres_hedges_orig <- fit_overall_mv(db_hedges %>% filter(Dataset_Source == \"Original (Davies 2020)\"), phylo_cor = phylo_cor_hedges)\nres_hedges_comb <- fit_overall_mv(db_hedges, phylo_cor = phylo_cor_hedges)\n\n# HEDGES' G MODELS (BIAS-CORRECTED)\nres_hedges_new_corr <- fit_corrected_mv(db_hedges %>% filter(Dataset_Source == \"New Extraction (Santos)\"), moderator = \"vi\", phylo_cor = phylo_cor_new)\nres_hedges_orig_corr <- fit_corrected_mv(db_hedges %>% filter(Dataset_Source == \"Original (Davies 2020)\"), moderator = \"vi\", phylo_cor = phylo_cor_hedges)\nres_hedges_comb_corr <- fit_corrected_mv(db_hedges, moderator = \"vi\", phylo_cor = phylo_cor_hedges)\n\n# ---------------------------------------------------------------------------\n# ODDS RATIO MODELS (UNCORRECTED) — now incorporating phylogenetic relatedness\n# ---------------------------------------------------------------------------\n# New-only uses the new-extraction tree; Original-only and Combined use the\n# combined log OR tree (Jones species are a subset of the combined tree).\nres_or_new <- fit_overall_mv(db_or %>% filter(Dataset_Source == \"New Extraction (Santos)\"), phylo_cor = phylo_cor_new)\nres_or_orig <- fit_overall_mv(db_or %>% filter(Dataset_Source == \"Original (Jones & DuVal 2019)\"), phylo_cor = phylo_cor_or)\nres_or_comb <- fit_overall_mv(db_or, phylo_cor = phylo_cor_or)\n\n# ODDS RATIO MODELS (BIAS-CORRECTED)\nres_or_new_corr <- fit_corrected_mv(db_or %>% filter(Dataset_Source == \"New Extraction (Santos)\"), moderator = \"vi\", phylo_cor = phylo_cor_new)\nres_or_orig_corr <- fit_corrected_mv(db_or %>% filter(Dataset_Source == \"Original (Jones & DuVal 2019)\"), moderator = \"vi\", phylo_cor = phylo_cor_or)\nres_or_comb_corr <- fit_corrected_mv(db_or, moderator = \"vi\", phylo_cor = phylo_cor_or)\n```\n:::\n\n\n---\n\n## Results and Visualizations\n\n::: {.panel-tabset}\n\n### Hedges' $g$ (Continuous outcomes)\n\n::: {.panel-tabset}\n\n#### Uncorrected Overall Effect\n\nThis plot displays the standard multi-level meta-analytic summaries across the three splits (New Only, Original Only, and Combined) *without* adjusting for publication bias. Points represent individual effect sizes colored by their data source.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_new) && !is.null(res_hedges_orig) && !is.null(res_hedges_comb)) {\n    # 1. Extract S3 result objects using mod_results\n    h_new <- orchaRd::mod_results(res_hedges_new$model, group = \"identifierStudyId\")\n    h_orig <- orchaRd::mod_results(res_hedges_orig$model, group = \"identifierStudyId\")\n    h_comb <- orchaRd::mod_results(res_hedges_comb$model, group = \"identifierStudyId\")\n\n    # 2. Clone S3 result objects to lists for manual editing\n    class(h_new) <- \"list\"\n    h_new$mod_table$name <- \"New Extraction (Santos)\"\n    h_new$data$moderator <- \"New Extraction (Santos)\"\n    class(h_new) <- c(\"orchard\", \"data.frame\")\n\n    class(h_orig) <- \"list\"\n    h_orig$mod_table$name <- \"Original (Davies 2020)\"\n    h_orig$data$moderator <- \"Original (Davies 2020)\"\n    class(h_orig) <- c(\"orchard\", \"data.frame\")\n\n    class(h_comb) <- \"list\"\n    h_comb$mod_table$name <- \"Combined\"\n    h_comb$data$moderator <- \"Combined\"\n    class(h_comb) <- c(\"orchard\", \"data.frame\")\n\n    # 3. Merge model results\n    sub_hedges <- orchaRd::submerge(h_new, h_orig, h_comb)\n\n    # 4. Add point-level real source mapping\n    class(sub_hedges) <- \"list\"\n    sub_hedges$data$real_source <- c(\n        rep(\"New Extraction (Santos)\", nrow(h_new$data)),\n        rep(\"Original (Davies 2020)\", nrow(h_orig$data)),\n        rep(\"New Extraction (Santos)\", nrow(h_new$data)),\n        rep(\"Original (Davies 2020)\", nrow(h_orig$data))\n    )\n    class(sub_hedges) <- c(\"orchard\", \"data.frame\")\n\n    # 4. Generate Plot\n    p_hedges <- orchaRd::orchard_plot(sub_hedges, xlab = \"Hedges' g\", flip = TRUE)\n\n    # 5. Customize color mapping for points\n    p_hedges$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\n    p_hedges$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\n    # 6. Apply themes & custom palette (colorblind friendly orange/blue)\n    p_hedges <- p_hedges +\n        ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::ggtitle(\"Overall Synthesis — Hedges' g Estimates (Uncorrected)\") +\n        ggplot2::theme(\n            legend.position = c(0.98, 0.02),\n            legend.justification = c(\"right\", \"bottom\"),\n            legend.background = ggplot2::element_rect(fill = scales::alpha(\"white\", 0.75), color = \"grey90\"),\n            legend.box = \"vertical\",\n            legend.margin = ggplot2::margin(t = 4, r = 4, b = 4, l = 4),\n            legend.title = ggplot2::element_text(size = 9, face = \"bold\"),\n            legend.text = ggplot2::element_text(size = 8)\n        )\n\n    # Add Mean (95% CI) and k labels\n    p_hedges <- add_ci_labels(p_hedges, sub_hedges)\n\n    print(p_hedges)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/hedges_unified_plot-1.png){width=960}\n:::\n:::\n\n\n#### Bias-Corrected Overall Effect\n\nThis plot displays the small-study publication bias corrected meta-analytic summaries (evaluated at $\\text{V} = 0$, representing the theoretical estimate for a study of infinite sample size/precision) using the two-step Egger-type meta-regression framework. Points represent the same raw effect sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_new_corr) && !is.null(res_hedges_orig_corr) && !is.null(res_hedges_comb_corr)) {\n    # 1. Extract S3 result objects using mod_results at vi = 0\n    h_new_corr <- orchaRd::mod_results(res_hedges_new_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n    h_orig_corr <- orchaRd::mod_results(res_hedges_orig_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n    h_comb_corr <- orchaRd::mod_results(res_hedges_comb_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n\n    # 2. Clone S3 result objects to lists for manual editing\n    class(h_new_corr) <- \"list\"\n    h_new_corr$mod_table$name <- \"New Extraction (Santos)\"\n    h_new_corr$data$moderator <- \"New Extraction (Santos)\"\n    class(h_new_corr) <- c(\"orchard\", \"data.frame\")\n\n    class(h_orig_corr) <- \"list\"\n    h_orig_corr$mod_table$name <- \"Original (Davies 2020)\"\n    h_orig_corr$data$moderator <- \"Original (Davies 2020)\"\n    class(h_orig_corr) <- c(\"orchard\", \"data.frame\")\n\n    class(h_comb_corr) <- \"list\"\n    h_comb_corr$mod_table$name <- \"Combined\"\n    h_comb_corr$data$moderator <- \"Combined\"\n    class(h_comb_corr) <- c(\"orchard\", \"data.frame\")\n\n    # 3. Merge model results\n    sub_hedges_corr <- orchaRd::submerge(h_new_corr, h_orig_corr, h_comb_corr)\n\n    # 4. Add point-level real source mapping\n    class(sub_hedges_corr) <- \"list\"\n    sub_hedges_corr$data$real_source <- c(\n        rep(\"New Extraction (Santos)\", nrow(h_new_corr$data)),\n        rep(\"Original (Davies 2020)\", nrow(h_orig_corr$data)),\n        rep(\"New Extraction (Santos)\", nrow(h_new_corr$data)),\n        rep(\"Original (Davies 2020)\", nrow(h_orig_corr$data))\n    )\n    class(sub_hedges_corr) <- c(\"orchard\", \"data.frame\")\n\n    # 4. Generate Plot\n    p_hedges_corr <- orchaRd::orchard_plot(sub_hedges_corr, xlab = \"Hedges' g (Bias Corrected)\", flip = TRUE)\n\n    # 5. Customize color mapping for points\n    p_hedges_corr$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\n    p_hedges_corr$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\n    # 6. Apply themes & custom palette\n    p_hedges_corr <- p_hedges_corr +\n        ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Davies 2020)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::ggtitle(\"Overall Synthesis — Hedges' g Estimates (Bias-Corrected)\") +\n        ggplot2::theme(\n            legend.position = c(0.98, 0.02),\n            legend.justification = c(\"right\", \"bottom\"),\n            legend.background = ggplot2::element_rect(fill = scales::alpha(\"white\", 0.75), color = \"grey90\"),\n            legend.box = \"vertical\",\n            legend.margin = ggplot2::margin(t = 4, r = 4, b = 4, l = 4),\n            legend.title = ggplot2::element_text(size = 9, face = \"bold\"),\n            legend.text = ggplot2::element_text(size = 8)\n        )\n\n    # Add Mean (95% CI) and k labels\n    p_hedges_corr <- add_ci_labels(p_hedges_corr, sub_hedges_corr)\n\n    print(p_hedges_corr)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/hedges_corrected_plot-1.png){width=960}\n:::\n:::\n\n\n#### Side-by-Side Comparison\n\nWe combine the uncorrected and small-study bias corrected orchard plots side-by-side using `patchwork` to directly evaluate the shifts in pooled estimates and prediction intervals when publication selection is accounted for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"p_hedges\") && exists(\"p_hedges_corr\")) {\n    comparison_hedges <- (p_hedges + p_hedges_corr) +\n        patchwork::plot_annotation(\n            title = \"Comparison of Uncorrected vs. Bias-Corrected Synthesis (Hedges' g)\",\n            subtitle = \"Bias-corrected estimates are conditioned on study variance = 0 (infinite precision)\",\n            theme = ggplot2::theme(\n                plot.title = ggplot2::element_text(size = 16, face = \"bold\", hjust = 0.5),\n                plot.subtitle = ggplot2::element_text(size = 12, italic = TRUE, hjust = 0.5)\n            )\n        )\n    print(comparison_hedges)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/hedges_comparison_plot-1.png){width=1344}\n:::\n:::\n\n\n#### Detailed Model Statistics\n\nHere are the text outputs and fit statistics for the three database splits. Each split displays the uncorrected and small-study bias-corrected (Egger's variance-adjusted) model summaries:\n\n::: {.panel-tabset}\n\n##### New Only\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_new)) {\n    print(summary(res_hedges_new$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_new$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 69; method: REML)\n\n  logLik  Deviance       AIC       BIC      AICc   \n-53.6358  107.2716  117.2716  128.3691  118.2393   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0000     29     no       identifierStudyId   no \nsigma^2.2  0.1509  0.3885     69     no  identifierEffectSizeID   no \nsigma^2.3  0.0865  0.2941     15     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     15     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 68) = 313.8235, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval    ci.lb   ci.ub    \n  0.2069  0.1124  1.8413  14  0.0869  -0.0341  0.4478  . \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.075307e+01              1.730240e-07              5.133174e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             2.942133e+01              7.888421e-10 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_new_corr)) {\n    print(summary(res_hedges_new_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_new_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 69; method: REML)\n\n  logLik  Deviance       AIC       BIC      AICc   \n-51.6538  103.3076  115.3076  128.5358  116.7076   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0000     29     no       identifierStudyId   no \nsigma^2.2  0.1454  0.3813     69     no  identifierEffectSizeID   no \nsigma^2.3  0.0887  0.2979     15     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     15     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 67) = 312.1221, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 67) = 2.6750, p-val = 0.1066\n\nModel Results:\n\n         estimate      se     tval  df    pval    ci.lb   ci.ub    \nintrcpt   -0.0223  0.1799  -0.1237  13  0.9034  -0.4108  0.3663    \nvi         2.5507  1.5596   1.6355  67  0.1066  -0.5622  5.6637    \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.052898e+01              6.480791e-07              5.000840e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             3.052058e+01              1.435705e-08 \n```\n\n\n:::\n:::\n\n\n:::\n\n##### Original Only\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_orig)) {\n    print(summary(res_hedges_orig$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_orig$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 158; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-191.6953   383.3905   393.3905   408.6718   393.7879   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0238  0.1544     58     no       identifierStudyId   no \nsigma^2.2  0.4505  0.6712    158     no  identifierEffectSizeID   no \nsigma^2.3  0.0000  0.0000     23     no         taxonomySpecies   no \nsigma^2.4  0.0268  0.1638     23     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 157) = 1057.3459, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub      \n  0.5654  0.1217  4.6443  22  0.0001  0.3129  0.8178  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.578134e+01              4.080187e+00              7.711020e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             1.855101e-07              4.590962e+00 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_orig_corr)) {\n    print(summary(res_hedges_orig_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_orig_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 158; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-162.0686   324.1372   336.1372   354.4364   336.7010   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0206  0.1436     58     no       identifierStudyId   no \nsigma^2.2  0.3184  0.5643    158     no  identifierEffectSizeID   no \nsigma^2.3  0.0000  0.0000     23     no         taxonomySpecies   no \nsigma^2.4  0.0133  0.1151     23     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 156) = 894.6118, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 156) = 62.9944, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb   ci.ub      \nintrcpt   -0.1485  0.1299  -1.1433   21  0.2658  -0.4186  0.1216      \nvi         6.3327  0.7979   7.9369  156  <.0001   4.7566  7.9087  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.092058e+01              4.735750e+00              7.314022e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             1.785359e-07              3.044617e+00 \n```\n\n\n:::\n:::\n\n\n:::\n\n##### Combined\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_comb)) {\n    print(summary(res_hedges_comb$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_comb$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-257.9500   515.9000   525.9000   543.0026   526.1727   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0525  0.2292     87     no       identifierStudyId   no \nsigma^2.2  0.3485  0.5904    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0096  0.0981     31     no         taxonomySpecies   no \nsigma^2.4  0.0163  0.1276     30     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 226) = 1389.2944, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub      \n  0.4537  0.0994  4.5651  29  <.0001  0.2504  0.6570  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n                85.485226                 10.519765                 69.779271 \n       I2_taxonomySpecies          I2_species_phylo \n                 1.927308                  3.258882 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_hedges_comb_corr)) {\n    print(summary(res_hedges_comb_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_hedges_comb_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-222.7861   445.5721   457.5721   478.0687   457.9574   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0532  0.2307     87     no       identifierStudyId   no \nsigma^2.2  0.2542  0.5042    227     no  identifierEffectSizeID   no \nsigma^2.3  0.0014  0.0377     31     no         taxonomySpecies   no \nsigma^2.4  0.0255  0.1597     30     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 225) = 1232.5374, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 225) = 74.2988, p-val < .0001\n\nModel Results:\n\n         estimate      se     tval   df    pval    ci.lb   ci.ub      \nintrcpt   -0.2140  0.1323  -1.6179   28  0.1169  -0.4849  0.0569      \nvi         6.3236  0.7336   8.6197  225  <.0001   4.8779  7.7692  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n               82.1802314                13.0778266                62.4810715 \n       I2_taxonomySpecies          I2_species_phylo \n                0.3496849                 6.2716483 \n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n:::\n\n### Odds Ratio (Binary outcomes)\n\n::: {.panel-tabset}\n\n#### Uncorrected Overall Effect\n\nThis plot displays the standard multi-level meta-analytic summaries across the three splits (New Only, Original Only, and Combined) *without* adjusting for publication bias. Points represent individual log odds ratios colored by their data source.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_new) && !is.null(res_or_orig) && !is.null(res_or_comb)) {\n    # 1. Extract S3 result objects using mod_results\n    o_new <- orchaRd::mod_results(res_or_new$model, group = \"identifierStudyId\")\n    o_orig <- orchaRd::mod_results(res_or_orig$model, group = \"identifierStudyId\")\n    o_comb <- orchaRd::mod_results(res_or_comb$model, group = \"identifierStudyId\")\n\n    # 2. Clone S3 result objects to lists for manual editing\n    class(o_new) <- \"list\"\n    o_new$mod_table$name <- \"New Extraction (Santos)\"\n    o_new$data$moderator <- \"New Extraction (Santos)\"\n    class(o_new) <- c(\"orchard\", \"data.frame\")\n\n    class(o_orig) <- \"list\"\n    o_orig$mod_table$name <- \"Original (Jones & DuVal 2019)\"\n    o_orig$data$moderator <- \"Original (Jones & DuVal 2019)\"\n    class(o_orig) <- c(\"orchard\", \"data.frame\")\n\n    class(o_comb) <- \"list\"\n    o_comb$mod_table$name <- \"Combined\"\n    o_comb$data$moderator <- \"Combined\"\n    class(o_comb) <- c(\"orchard\", \"data.frame\")\n\n    # 3. Merge model results\n    sub_or <- orchaRd::submerge(o_new, o_orig, o_comb)\n\n    # 4. Add point-level real source mapping\n    class(sub_or) <- \"list\"\n    sub_or$data$real_source <- c(\n        rep(\"New Extraction (Santos)\", nrow(o_new$data)),\n        rep(\"Original (Jones & DuVal)\", nrow(o_orig$data)),\n        rep(\"New Extraction (Santos)\", nrow(o_new$data)),\n        rep(\"Original (Jones & DuVal)\", nrow(o_orig$data))\n    )\n    class(sub_or) <- c(\"orchard\", \"data.frame\")\n\n    # 4. Generate Plot\n    p_or <- orchaRd::orchard_plot(sub_or, xlab = \"Log Odds Ratio (lnOR)\", flip = TRUE)\n\n    # 5. Customize color mapping for points\n    p_or$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\n    p_or$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\n    # 6. Apply themes & custom palette (colorblind friendly orange/blue)\n    p_or <- p_or +\n        ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::ggtitle(\"Overall Synthesis — Log Odds Ratio Estimates (Uncorrected)\") +\n        ggplot2::theme(\n            legend.position = c(0.98, 0.02),\n            legend.justification = c(\"right\", \"bottom\"),\n            legend.background = ggplot2::element_rect(fill = scales::alpha(\"white\", 0.75), color = \"grey90\"),\n            legend.box = \"vertical\",\n            legend.margin = ggplot2::margin(t = 4, r = 4, b = 4, l = 4),\n            legend.title = ggplot2::element_text(size = 9, face = \"bold\"),\n            legend.text = ggplot2::element_text(size = 8)\n        )\n\n    # Add Mean (95% CI) and k labels\n    p_or <- add_ci_labels(p_or, sub_or)\n\n    print(p_or)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/or_unified_plot-1.png){width=960}\n:::\n:::\n\n\n#### Bias-Corrected Overall Effect\n\nThis plot displays the small-study publication bias corrected meta-analytic summaries (evaluated at $\\text{V} = 0$, representing the theoretical estimate for a study of infinite sample size/precision) using the two-step Egger-type meta-regression framework. Points represent the same raw effect sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_new_corr) && !is.null(res_or_orig_corr) && !is.null(res_or_comb_corr)) {\n    # 1. Extract S3 result objects using mod_results at vi = 0\n    o_new_corr <- orchaRd::mod_results(res_or_new_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n    o_orig_corr <- orchaRd::mod_results(res_or_orig_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n    o_comb_corr <- orchaRd::mod_results(res_or_comb_corr$model, group = \"identifierStudyId\", at = list(vi = 0), mod = \"1\")\n\n    # 2. Clone S3 result objects to lists for manual editing\n    class(o_new_corr) <- \"list\"\n    o_new_corr$mod_table$name <- \"New Extraction (Santos)\"\n    o_new_corr$data$moderator <- \"New Extraction (Santos)\"\n    class(o_new_corr) <- c(\"orchard\", \"data.frame\")\n\n    class(o_orig_corr) <- \"list\"\n    o_orig_corr$mod_table$name <- \"Original (Jones & DuVal 2019)\"\n    o_orig_corr$data$moderator <- \"Original (Jones & DuVal 2019)\"\n    class(o_orig_corr) <- c(\"orchard\", \"data.frame\")\n\n    class(o_comb_corr) <- \"list\"\n    o_comb_corr$mod_table$name <- \"Combined\"\n    o_comb_corr$data$moderator <- \"Combined\"\n    class(o_comb_corr) <- c(\"orchard\", \"data.frame\")\n\n    # 3. Merge model results\n    sub_or_corr <- orchaRd::submerge(o_new_corr, o_orig_corr, o_comb_corr)\n\n    # 4. Add point-level real source mapping\n    class(sub_or_corr) <- \"list\"\n    sub_or_corr$data$real_source <- c(\n        rep(\"New Extraction (Santos)\", nrow(o_new_corr$data)),\n        rep(\"Original (Jones & DuVal)\", nrow(o_orig_corr$data)),\n        rep(\"New Extraction (Santos)\", nrow(o_new_corr$data)),\n        rep(\"Original (Jones & DuVal)\", nrow(o_orig_corr$data))\n    )\n    class(sub_or_corr) <- c(\"orchard\", \"data.frame\")\n\n    # 4. Generate Plot\n    p_or_corr <- orchaRd::orchard_plot(sub_or_corr, xlab = \"Log Odds Ratio (lnOR) (Bias Corrected)\", flip = TRUE)\n\n    # 5. Customize color mapping for points\n    p_or_corr$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\n    p_or_corr$layers[[1]]$mapping$fill <- ggplot2::aes(fill = real_source)$fill\n\n    # 6. Apply themes & custom palette\n    p_or_corr <- p_or_corr +\n        ggplot2::scale_colour_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::scale_fill_manual(values = c(\"New Extraction (Santos)\" = \"#D55E00\", \"Original (Jones & DuVal)\" = \"#0072B2\"), name = \"Data Source\") +\n        ggplot2::ggtitle(\"Overall Synthesis — Log Odds Ratio Estimates (Bias-Corrected)\") +\n        ggplot2::theme(\n            legend.position = c(0.98, 0.02),\n            legend.justification = c(\"right\", \"bottom\"),\n            legend.background = ggplot2::element_rect(fill = scales::alpha(\"white\", 0.75), color = \"grey90\"),\n            legend.box = \"vertical\",\n            legend.margin = ggplot2::margin(t = 4, r = 4, b = 4, l = 4),\n            legend.title = ggplot2::element_text(size = 9, face = \"bold\"),\n            legend.text = ggplot2::element_text(size = 8)\n        )\n\n    # Add Mean (95% CI) and k labels\n    p_or_corr <- add_ci_labels(p_or_corr, sub_or_corr)\n\n    print(p_or_corr)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/or_corrected_plot-1.png){width=960}\n:::\n:::\n\n\n#### Side-by-Side Comparison\n\nWe combine the uncorrected and small-study bias corrected orchard plots side-by-side using `patchwork` to directly evaluate the shifts in pooled estimates and prediction intervals when publication selection is accounted for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"p_or\") && exists(\"p_or_corr\")) {\n    comparison_or <- (p_or + p_or_corr) +\n        patchwork::plot_annotation(\n            title = \"Comparison of Uncorrected vs. Bias-Corrected Synthesis (Odds Ratio)\",\n            subtitle = \"Bias-corrected estimates are conditioned on study variance = 0 (infinite precision)\",\n            theme = ggplot2::theme(\n                plot.title = ggplot2::element_text(size = 16, face = \"bold\", hjust = 0.5),\n                plot.subtitle = ggplot2::element_text(size = 12, italic = TRUE, hjust = 0.5)\n            )\n        )\n    print(comparison_or)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/or_comparison_plot-1.png){width=1344}\n:::\n:::\n\n\n#### Detailed Model Statistics\n\nHere are the text outputs and fit statistics for the three database splits. Each split displays the uncorrected and small-study bias-corrected (Egger's variance-adjusted) model summaries:\n\n::: {.panel-tabset}\n\n##### New Only\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_new)) {\n    print(summary(res_or_new$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_new$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 69; method: REML)\n\n  logLik  Deviance       AIC       BIC      AICc   \n-94.5908  189.1817  199.1817  210.2792  200.1494   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0001     29     no       identifierStudyId   no \nsigma^2.2  0.5030  0.7092     69     no  identifierEffectSizeID   no \nsigma^2.3  0.2894  0.5380     15     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     15     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 68) = 313.9260, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval    ci.lb   ci.ub    \n  0.3788  0.2056  1.8420  14  0.0868  -0.0623  0.8198  . \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.075748e+01              3.637257e-07              5.126179e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             2.949569e+01              1.803305e-09 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_new_corr)) {\n    print(summary(res_or_new_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_new_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 69; method: REML)\n\n  logLik  Deviance       AIC       BIC      AICc   \n-92.0141  184.0282  196.0282  209.2564  197.4282   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0001     29     no       identifierStudyId   no \nsigma^2.2  0.4851  0.6965     69     no  identifierEffectSizeID   no \nsigma^2.3  0.2936  0.5419     15     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     15     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 67) = 312.1315, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 67) = 2.6278, p-val = 0.1097\n\nModel Results:\n\n         estimate      se     tval  df    pval    ci.lb   ci.ub    \nintrcpt   -0.0151  0.3184  -0.0474  13  0.9629  -0.7029  0.6727    \nvi         1.2993  0.8015   1.6211  67  0.1097  -0.3005  2.8992    \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             8.048494e+01              9.614165e-07              5.013758e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             3.034736e+01              2.200372e-08 \n```\n\n\n:::\n:::\n\n\n:::\n\n##### Original Only\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_orig)) {\n    print(summary(res_or_orig$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_orig$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 103; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-124.6315   249.2629   259.2629   272.3878   259.8879   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0000     40     no       identifierStudyId   no \nsigma^2.2  0.1973  0.4442    103     no  identifierEffectSizeID   no \nsigma^2.3  0.3887  0.6235     17     no         taxonomySpecies   no \nsigma^2.4  0.0605  0.2460     17     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 102) = 287.4819, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub     \n  0.7533  0.2513  2.9975  16  0.0085  0.2206  1.2861  ** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             7.591909e+01              1.235893e-07              2.316938e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             4.564459e+01              7.105124e+00 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_orig_corr)) {\n    print(summary(res_or_orig_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_orig_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 103; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-116.4779   232.9558   244.9558   260.6466   245.8495   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0000     40     no       identifierStudyId   no \nsigma^2.2  0.1837  0.4286    103     no  identifierEffectSizeID   no \nsigma^2.3  0.2398  0.4896     17     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0001     17     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 101) = 266.7344, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 101) = 14.5796, p-val = 0.0002\n\nModel Results:\n\n         estimate      se    tval   df    pval    ci.lb   ci.ub      \nintrcpt    0.3085  0.2152  1.4333   15  0.1723  -0.1502  0.7671      \nvi         1.2145  0.3181  3.8183  101  0.0002   0.5835  1.8454  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             6.737045e+01              1.743032e-11              2.922292e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             3.814753e+01              6.596456e-07 \n```\n\n\n:::\n:::\n\n\n:::\n\n##### Combined\n\n::: {.panel-tabset}\n\n###### Uncorrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_comb)) {\n    print(summary(res_or_comb$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_comb$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-229.2317   458.4635   468.4635   484.1718   468.8271   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0334  0.1828     69     no       identifierStudyId   no \nsigma^2.2  0.3543  0.5953    172     no  identifierEffectSizeID   no \nsigma^2.3  0.1864  0.4317     29     no         taxonomySpecies   no \nsigma^2.4  0.0083  0.0912     28     no           species_phylo  yes \n\nTest for Heterogeneity:\nQ(df = 171) = 611.9869, p-val < .0001\n\nModel Results:\n\nestimate      se    tval  df    pval   ci.lb   ci.ub      \n  0.5939  0.1466  4.0506  27  0.0004  0.2931  0.8948  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n                74.679950                  4.286108                 45.430779 \n       I2_taxonomySpecies          I2_species_phylo \n                23.896658                  1.066405 \n```\n\n\n:::\n:::\n\n\n###### Bias-Corrected\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(res_or_comb_corr)) {\n    print(summary(res_or_comb_corr$model))\n    cat(\"\\nHeterogeneity (I^2):\\n\")\n    print(orchaRd::i2_ml(res_or_comb_corr$model))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-216.4096   432.8192   444.8192   463.6339   445.3345   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed                  factor    R \nsigma^2.1  0.0000  0.0001     69     no       identifierStudyId   no \nsigma^2.2  0.3252  0.5703    172     no  identifierEffectSizeID   no \nsigma^2.3  0.1502  0.3876     29     no         taxonomySpecies   no \nsigma^2.4  0.0000  0.0000     28     no           species_phylo  yes \n\nTest for Residual Heterogeneity:\nQE(df = 170) = 586.7741, p-val < .0001\n\nTest of Moderators (coefficient 2):\nF(df1 = 1, df2 = 170) = 23.5751, p-val < .0001\n\nModel Results:\n\n         estimate      se    tval   df    pval    ci.lb   ci.ub      \nintrcpt    0.1001  0.1617  0.6192   26  0.5411  -0.2322  0.4324      \nvi         1.4198  0.2924  4.8554  170  <.0001   0.8425  1.9970  *** \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nHeterogeneity (I^2):\n                 I2_Total      I2_identifierStudyId I2_identifierEffectSizeID \n             7.065306e+01              2.030358e-06              4.833209e+01 \n       I2_taxonomySpecies          I2_species_phylo \n             2.232097e+01              9.985997e-13 \n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n:::\n\n:::\n\n---\n\n## Female-Only Sensitivity Analysis (log odds ratio) {#sec-female-only}\n\nJones & DuVal [-@jonesMechanismsSocialInfluence2019] synthesised **female**\nmate-choice copying only. Our combined log odds ratio dataset includes male\nobservers as well, so setting our pooled OR against their 2.71 compares two\ndifferent scopes. This section refits the combined odds ratio model on female\nobservers alone, which is the estimate that *can* be set against theirs on\nlike-for-like terms.\n\nThe model is identical to the combined model above in every other respect —\nsame `rma.mv` structure, same `vcalc` sampling variance–covariance matrix with\n$\\rho = 0.5$, same study / effect-size / species random effects plus the\nphylogenetic correlation matrix, REML, `test = \"t\"`, `dfs = \"contain\"` — so the\nonly thing that changes is which rows enter it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndb_or_female <- db_or %>% filter(observer_sex == \"Female\")\n\n# Audit the scope difference so it is reportable, not just assumed.\nor_sex_audit <- db_or %>%\n    count(Dataset_Source, observer_sex, name = \"k\") %>%\n    arrange(Dataset_Source, observer_sex)\n\nn_or_male_es      <- sum(db_or$observer_sex == \"Male\", na.rm = TRUE)\nstudies_lost_male <- setdiff(as.character(unique(db_or$identifierStudyId)),\n                             as.character(unique(db_or_female$identifierStudyId)))\n\nres_or_comb_female <- fit_overall_mv(db_or_female, phylo_cor = phylo_cor_or)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-9463f304c5bbafd9ce8d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9463f304c5bbafd9ce8d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Observer sex by source in the combined log odds ratio dataset. Jones &amp; DuVal rows are female by construction; the male-observer effect sizes all come from the new extraction.<\\/caption>\",\"data\":[[\"New Extraction (Santos)\",\"New Extraction (Santos)\",\"Original (Jones &amp; DuVal 2019)\"],[\"Female\",\"Male\",\"Female\"],[61,8,103]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Dataset_Source<\\/th>\\n      <th>observer_sex<\\/th>\\n      <th>k<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Dataset_Source\",\"targets\":0},{\"name\":\"observer_sex\",\"targets\":1},{\"name\":\"k\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-819e48954b32b75772a7\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-819e48954b32b75772a7\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Combined log odds ratio model, all observers versus female observers only. Odds ratios are back-transformed from the log scale on which the models were fitted; '% favoured' is the implied probability of choosing the socially favoured male against a 50:50 chance expectation.<\\/caption>\",\"data\":[[\"Combined — all observers\",\"Combined — female observers only\"],[172,164],[69,66],[29,29],[0.594,0.594],[1.81,1.81],[1.34,1.32],[2.45,2.49],[0.000387,0.0007],[64.40000000000001,64.40000000000001]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Model<\\/th>\\n      <th>k (effect sizes)<\\/th>\\n      <th>Studies<\\/th>\\n      <th>Species<\\/th>\\n      <th>log OR<\\/th>\\n      <th>OR<\\/th>\\n      <th>OR CI lower<\\/th>\\n      <th>OR CI upper<\\/th>\\n      <th>p<\\/th>\\n      <th>% favoured<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Model\",\"targets\":0},{\"name\":\"k (effect sizes)\",\"targets\":1},{\"name\":\"Studies\",\"targets\":2},{\"name\":\"Species\",\"targets\":3},{\"name\":\"log OR\",\"targets\":4},{\"name\":\"OR\",\"targets\":5},{\"name\":\"OR CI lower\",\"targets\":6},{\"name\":\"OR CI upper\",\"targets\":7},{\"name\":\"p\",\"targets\":8},{\"name\":\"% favoured\",\"targets\":9}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\nRestricting the combined odds ratio dataset to female observers drops\n8 male-observer effect sizes, all of them from the new extraction,\nand removes 3 studies entirely\n(Bierbach_2011_BehavioralEcologyAndSociobiology, Pusiak_2020_AnimalBehaviour, Ziege_2012_CurrentZoology). The female-only mean OR is\n**1.81** (95% CI: 1.32 to 2.49; $k$ =\n164 effect sizes from 66 studies), against 1.81 for the\nall-observer model.\n\nThe two are effectively identical, which is the substantive point: the gap\nbetween our pooled estimate and the 2.71 of Jones & DuVal\n[-@jonesMechanismsSocialInfluence2019] is **not** an artefact of our having\nincluded male observers. It reflects the added evidence and the different\nanalytical framework, not the change in scope. This is consistent with the\n[observer-sex moderator analysis](moderator_analysis.qmd#sec-bio-sex), which\nfinds no detectable difference between female and male observers on either\nscale.\n\n---\n\n## Combined Correction Comparison {#sec-correction-comparison}\n\nThe tabs above present the uncorrected and bias-corrected estimates on separate plots. To make the comparison easier to read, we produce **two figures** — one for Hedges' $g$ and one for the log odds ratio — using the same `orchaRd::pub_bias_plot()` approach as the publication-bias chapter. Each figure stacks the three model levels (New Extraction, Original, Combined) as rows; within each row a single orchard trunk shows the uncorrected multilevel mean drawn over its raw effect sizes **once**, with the two corrected means overlaid on top. The raw points are coloured by data source and the legend is boxed in the corner, matching the side-by-side comparison plots above.\n\nThe three estimates shown per subplot are:\n\n* **Uncorrected** (the trunk) — the multilevel `rma.mv` mean.\n* **Bias-Corrected (Nakagawa et al. [-@nakagawaMethodsTestingPublication2022]); purple overlay** — the intercept of the multilevel meta-regression with sampling variance ($v_i$) as a moderator, evaluated at $v_i = 0$ (the effect a hypothetical infinitely-precise study would report).\n* **Bias-Robust (Yang et al. [-@yangRobustPointVariance2024]); green overlay** — a multivariate fixed-/common-effect model weighted by the sampling variance–covariance matrix (FE + VCV, $\\rho = 0.5$), followed by cluster-robust (CR2) variance estimation clustered by study. The step-one model contains no random effects, which is what makes the CR2 correction applicable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Yang et al. (2024) bias-robust estimate (FE + VCV, then CR2 cluster-robust),\n# fitted for each database split. Mirrors the construction in publication_bias.qmd\n# but applied to New, Original, and Combined subsets.\n#\n# Step one must be a MULTIVARIATE fixed-effect model whose weights come from the\n# sampling variance-covariance matrix (rho = 0.5), not a univariate rma() with\n# diagonal 1/v_i weights. The inverse-VCV weighting scheme is what makes the\n# estimator bias-robust: it downweights imprecise studies reporting large\n# effects and prevents a study contributing many correlated effect sizes from\n# accruing weight in proportion to its effect-size count. rma.mv() with no\n# `random` argument is the fixed-effect model (\"Variance Components: none\").\nfit_bias_robust <- function(dat, yi = \"yi\", vi = \"vi\", cluster_var = \"identifierStudyId\",\n                            obs_var = \"identifierEffectSizeID\", rho = 0.5) {\n    dat2 <- dat %>% filter(!is.na(.data[[yi]]), !is.na(.data[[vi]]), .data[[vi]] > 0)\n    if (nrow(dat2) == 0) return(NULL)\n    tryCatch({\n        VCV <- metafor::vcalc(\n            vi = dat2[[vi]],\n            cluster = dat2[[cluster_var]],\n            obs = dat2[[obs_var]],\n            rho = rho,\n            data = dat2\n        )\n        fe <- metafor::rma.mv(\n            yi = dat2[[yi]],\n            V = VCV,\n            method = \"REML\",\n            test = \"t\",\n            dfs = \"contain\",\n            sparse = TRUE,\n            data = dat2\n        )\n        metafor::robust(fe, cluster = dat2[[cluster_var]], adjust = TRUE, clubSandwich = TRUE)\n    }, error = function(e) {\n        warning(\"Bias-robust fit failed: \", conditionMessage(e)); NULL\n    })\n}\n\nrob_hedges_new  <- fit_bias_robust(db_hedges %>% filter(Dataset_Source == \"New Extraction (Santos)\"))\nrob_hedges_orig <- fit_bias_robust(db_hedges %>% filter(Dataset_Source == \"Original (Davies 2020)\"))\nrob_hedges_comb <- fit_bias_robust(db_hedges)\n\nrob_or_new  <- fit_bias_robust(db_or %>% filter(Dataset_Source == \"New Extraction (Santos)\"))\nrob_or_orig <- fit_bias_robust(db_or %>% filter(Dataset_Source == \"Original (Jones & DuVal 2019)\"))\nrob_or_comb <- fit_bias_robust(db_or)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------------------\n# Subplot builder: one orchard trunk per model level, styled to match the\n# `hedges_comparison_plot` aesthetics — raw points coloured by data source\n# (colourblind orange/blue) with the boxed corner legend.\n#\n# The two corrected means are overlaid by hand (rather than via\n# orchaRd::pub_bias_plot(), whose colours are hardcoded red/blue and whose text\n# sits on top of the data) so that we can:\n#   * use overlay colours that stand out from the orange/blue raw points\n#     (green = Bias-Robust / Yang 2024, purple = Bias-Corrected / Nakagawa 2022);\n#   * right-align the estimate text on the far side of the panel, kept inside\n#     the plot box;\n#   * share a common x-axis (effect-size) range across the stacked panels.\n# ---------------------------------------------------------------------------\nsource_palette <- c(\n    \"New Extraction (Santos)\"       = \"#D55E00\",\n    \"Original (Davies 2020)\"        = \"#0072B2\",\n    \"Original (Jones & DuVal 2019)\" = \"#0072B2\"\n)\n\n# Overlay colours — chosen to be distinct from the orange/blue raw points and\n# colourblind-distinguishable (Okabe-Ito green + a strong violet).\nyang_col <- \"#009E73\"  # Bias-Robust (Yang et al. 2024)\nnaka_col <- \"#7B2D8E\"  # Bias-Corrected (Nakagawa et al. 2022)\n\n# Extract the corrected meta-analytic mean + 95% CI from an (intercept-only or\n# vi-moderated) rma / rma.mv model — same intercept used by orchaRd::get_ints_dat.\ncorrected_est <- function(model) {\n    b <- tryCatch(as.numeric(model$b[\"intrcpt\", ]),\n                  error = function(e) as.numeric(model$b[1]))\n    data.frame(name = \"Intrcpt\", pred = b,\n               ci.lb = model$ci.lb[1], ci.ub = model$ci.ub[1])\n}\n\n# src: either a single data-source label (recycled) or a per-point character\n# vector matching the order of the model's effect sizes (used for Combined).\n# xlim: optional c(lo, hi) shared effect-size range for axis alignment; when\n# supplied, the estimate text is right-aligned to xlim[2] (inside the box).\nmake_pub_bias_subplot <- function(unc_res, corr_res, rob_model, src, xlab, title, xlim = NULL) {\n    if (is.null(unc_res) || is.null(unc_res$model) ||\n        is.null(corr_res) || is.null(corr_res$model) || is.null(rob_model)) {\n        return(NULL)\n    }\n    # Single-trunk orchard result; attach the true per-point data source.\n    h <- orchaRd::mod_results(unc_res$model, group = \"identifierStudyId\")\n    if (length(src) == 1) src <- rep(src, nrow(h$data))\n    class(h) <- \"list\"\n    h$data$real_source <- src\n    class(h) <- c(\"orchard\", \"data.frame\")\n\n    # k/g labels to the left so the right margin is free for the estimate text.\n    # Widen point.size range so bubble area tracks precision more visibly.\n    # trunk.size = 1 -> point estimate drawn at size 4 (matches the overlay diamonds).\n    oc <- orchaRd::orchard_plot(h, xlab = xlab, flip = TRUE, k.pos = \"left\",\n                                point.size = c(0.8, 10), trunk.size = 1)\n\n    # Recolour the raw points (layer 1) by data source — as in hedges_comparison_plot.\n    oc$layers[[1]]$mapping$colour <- ggplot2::aes(colour = real_source)$colour\n    oc$layers[[1]]$mapping$fill   <- ggplot2::aes(fill = real_source)$fill\n\n    # Corrected estimates to overlay on the single uncorrected trunk.\n    yang <- corrected_est(rob_model)       # Bias-Robust   (Yang 2024)\n    naka <- corrected_est(corr_res$model)  # Bias-Corrected (Nakagawa 2022)\n\n    # Common effect-size range (falls back to this panel's data if not supplied).\n    if (is.null(xlim)) {\n        rng <- range(c(h$data$yi, yang$ci.lb, yang$ci.ub, naka$ci.lb, naka$ci.ub),\n                     na.rm = TRUE, finite = TRUE)\n        pad <- diff(rng) * 0.08\n        xlim <- c(rng[1] - pad, rng[2] + pad)\n    }\n    txt_y <- xlim[2]  # right edge (effect-size axis is horizontal after flip)\n\n    oc <- oc +\n        # Bias-Robust (Yang) — nudged below the trunk. Black CI bar; coloured\n        # diamond with a black border so it stands out against the bubbles.\n        ggplot2::geom_linerange(data = yang,\n            ggplot2::aes(x = name, ymin = ci.lb, ymax = ci.ub),\n            colour = \"black\", linewidth = 1.2,\n            position = ggplot2::position_nudge(x = -0.08), inherit.aes = FALSE) +\n        ggplot2::geom_point(data = yang,\n            ggplot2::aes(x = name, y = pred),\n            fill = yang_col, colour = \"black\", shape = 23, size = 4, stroke = 0.9,\n            position = ggplot2::position_nudge(x = -0.08), inherit.aes = FALSE) +\n        # Bias-Corrected (Nakagawa) — nudged above the trunk. Black CI bar;\n        # coloured diamond with a black border.\n        ggplot2::geom_linerange(data = naka,\n            ggplot2::aes(x = name, ymin = ci.lb, ymax = ci.ub),\n            colour = \"black\", linewidth = 1.2,\n            position = ggplot2::position_nudge(x = 0.08), inherit.aes = FALSE) +\n        ggplot2::geom_point(data = naka,\n            ggplot2::aes(x = name, y = pred),\n            fill = naka_col, colour = \"black\", shape = 23, size = 4, stroke = 0.9,\n            position = ggplot2::position_nudge(x = 0.08), inherit.aes = FALSE) +\n        # Estimate text, right-aligned to the right edge so it stays in the box.\n        # x positions mirror each diamond's nudge: Yang below (x<1), Naka above (x>1).\n        ggplot2::annotate(\"text\", x = 0.66, y = txt_y, hjust = 1, vjust = 0.5,\n            colour = yang_col, size = 3.4, fontface = \"bold\",\n            label = sprintf(\"Bias-Robust (Yang): %.2f [%.2f, %.2f]\",\n                            yang$pred, yang$ci.lb, yang$ci.ub)) +\n        ggplot2::annotate(\"text\", x = 1.34, y = txt_y, hjust = 1, vjust = 0.5,\n            colour = naka_col, size = 3.4, fontface = \"bold\",\n            label = sprintf(\"Bias-Corrected (Nakagawa): %.2f [%.2f, %.2f]\",\n                            naka$pred, naka$ci.lb, naka$ci.ub)) +\n        ggplot2::scale_colour_manual(values = source_palette, name = \"Data Source\") +\n        ggplot2::scale_fill_manual(values = source_palette, name = \"Data Source\") +\n        ggplot2::ggtitle(title) +\n        ggplot2::coord_flip(ylim = xlim) +\n        ggplot2::theme(\n            legend.position      = c(0.98, 0.02),\n            legend.justification = c(\"right\", \"bottom\"),\n            legend.background    = ggplot2::element_rect(fill = scales::alpha(\"white\", 0.75), color = \"grey90\"),\n            legend.box           = \"vertical\",\n            legend.margin        = ggplot2::margin(t = 4, r = 4, b = 4, l = 4),\n            legend.title         = ggplot2::element_text(size = 9, face = \"bold\"),\n            legend.text          = ggplot2::element_text(size = 8),\n            plot.title           = ggplot2::element_text(face = \"bold\", hjust = 0.5),\n            # Panel identifier (a)/(b)/(c) in the top-left corner of the box.\n            plot.tag             = ggplot2::element_text(size = 13, face = \"bold\", hjust = 0, vjust = 1),\n            plot.tag.position    = c(0.015, 0.985)\n        )\n\n    oc\n}\n\n# Shared effect-size range across the three panels of a stack, padded for the\n# right-aligned estimate text. Includes raw points + all corrected-estimate CIs.\ncompute_stack_xlim <- function(db, corr_models, rob_models) {\n    ci_vals <- function(m) if (is.null(m)) numeric(0) else c(m$ci.lb[1], m$ci.ub[1])\n    vals <- c(db$yi,\n              unlist(lapply(corr_models, function(r) if (is.null(r)) numeric(0) else ci_vals(r$model))),\n              unlist(lapply(rob_models, ci_vals)))\n    vals <- vals[is.finite(vals)]\n    rng <- range(vals)\n    pad <- diff(rng) * 0.08\n    c(rng[1] - pad, rng[2] + pad)\n}\n\n# Per-point source vectors for the Combined trunks (new rows then original rows,\n# matching bind_rows() order — same assumption as hedges_comparison_plot).\nn_h_new  <- nrow(orchaRd::mod_results(res_hedges_new$model,  group = \"identifierStudyId\")$data)\nn_h_orig <- nrow(orchaRd::mod_results(res_hedges_orig$model, group = \"identifierStudyId\")$data)\nsrc_h_comb <- c(rep(\"New Extraction (Santos)\", n_h_new), rep(\"Original (Davies 2020)\", n_h_orig))\n\nn_o_new  <- nrow(orchaRd::mod_results(res_or_new$model,  group = \"identifierStudyId\")$data)\nn_o_orig <- nrow(orchaRd::mod_results(res_or_orig$model, group = \"identifierStudyId\")$data)\nsrc_o_comb <- c(rep(\"New Extraction (Santos)\", n_o_new), rep(\"Original (Jones & DuVal 2019)\", n_o_orig))\n```\n:::\n\n\n\n\n### Hedges' $g$ (Continuous outcomes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shared x-axis range so the three Hedges panels align for easy comparison.\nhedges_xlim <- compute_stack_xlim(\n    db_hedges,\n    list(res_hedges_new_corr, res_hedges_orig_corr, res_hedges_comb_corr),\n    list(rob_hedges_new, rob_hedges_orig, rob_hedges_comb)\n)\n\nph_new  <- make_pub_bias_subplot(res_hedges_new,  res_hedges_new_corr,  rob_hedges_new,  \"New Extraction (Santos)\", \"Hedges' g\", \"New Extraction\", xlim = hedges_xlim)\nph_orig <- make_pub_bias_subplot(res_hedges_orig, res_hedges_orig_corr, rob_hedges_orig, \"Original (Davies 2020)\",  \"Hedges' g\", \"Original\",       xlim = hedges_xlim)\nph_comb <- make_pub_bias_subplot(res_hedges_comb, res_hedges_comb_corr, rob_hedges_comb, src_h_comb,                \"Hedges' g\", \"Combined\",       xlim = hedges_xlim)\n\nfig_hedges <- (ph_orig / ph_new / ph_comb) +\n    patchwork::plot_annotation(\n        tag_levels = \"a\", tag_prefix = \"(\", tag_suffix = \")\",\n        title = \"Hedges' g — Uncorrected mean with Bias-Corrected & Bias-Robust overlays\",\n        subtitle = \"Overlays: purple = Bias-Corrected (Nakagawa 2022), green = Bias-Robust (Yang 2024).\",\n        theme = ggplot2::theme(\n            plot.title    = ggplot2::element_text(size = 15, face = \"bold\", hjust = 0.5),\n            plot.subtitle = ggplot2::element_text(size = 11, face = \"italic\", hjust = 0.5)\n        )\n    )\n\nsave_deliverable_fig(fig_hedges, \"correction_comparison_hedges\", width = 9, height = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsaved: correction_comparison_hedges (.pdf + .png)\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(fig_hedges)\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/correction_comparison_hedges-1.png){width=864}\n:::\n:::\n\n\n### Odds Ratio (Binary outcomes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shared x-axis range so the three OR panels align for easy comparison.\nor_xlim <- compute_stack_xlim(\n    db_or,\n    list(res_or_new_corr, res_or_orig_corr, res_or_comb_corr),\n    list(rob_or_new, rob_or_orig, rob_or_comb)\n)\n\npo_new  <- make_pub_bias_subplot(res_or_new,  res_or_new_corr,  rob_or_new,  \"New Extraction (Santos)\",       \"Log Odds Ratio (lnOR)\", \"New Extraction\", xlim = or_xlim)\npo_orig <- make_pub_bias_subplot(res_or_orig, res_or_orig_corr, rob_or_orig, \"Original (Jones & DuVal 2019)\", \"Log Odds Ratio (lnOR)\", \"Original\",       xlim = or_xlim)\npo_comb <- make_pub_bias_subplot(res_or_comb, res_or_comb_corr, rob_or_comb, src_o_comb,                      \"Log Odds Ratio (lnOR)\", \"Combined\",       xlim = or_xlim)\n\nfig_or <- (po_orig / po_new / po_comb) +\n    patchwork::plot_annotation(\n        tag_levels = \"a\", tag_prefix = \"(\", tag_suffix = \")\",\n        title = \"Log Odds Ratio — Uncorrected mean with Bias-Corrected & Bias-Robust overlays\",\n        subtitle = \"Overlays: purple = Bias-Corrected (Nakagawa 2022), green = Bias-Robust (Yang 2024).\",\n        theme = ggplot2::theme(\n            plot.title    = ggplot2::element_text(size = 15, face = \"bold\", hjust = 0.5),\n            plot.subtitle = ggplot2::element_text(size = 11, face = \"italic\", hjust = 0.5)\n        )\n    )\n\nsave_deliverable_fig(fig_or, \"correction_comparison_or\", width = 9, height = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsaved: correction_comparison_or (.pdf + .png)\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(fig_or)\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/correction_comparison_or-1.png){width=864}\n:::\n:::\n\n\n### Figure 3 — both scales in one two-column display item {#sec-fig3-composite}\n\nThe manuscript needs these two stacks as a **single** display item. Supplying\nthem as two full-width images stacked in one column forced each to about a third\nof the text height, which shrank the labels and clashed with Figure 5's\ntwo-column design. This chunk therefore composes the\nsame six sub-plots as a 2 (scale) $\\times$ 3 (dataset) grid, drawn at Biology\nOpen's maximum display size of 180 $\\times$ 210 mm so nothing is scaled down at\ntypesetting.\n\nColumn order is **Hedges' $g$ = A, log odds ratio = B**, matching Figures 4 and\n5 so the effect-size scales appear in the same order in every display item.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rescale for the smaller canvas: six sub-plots at 180 x 210 mm instead of one\n# stack at 9 x 12 in. ggplot2 sizes points, strokes and line widths in mm, i.e.\n# in ABSOLUTE units, so they do not shrink with the panel -- leaving them alone\n# is what made the markers and bubbles look oversized. Each panel is about 0.45\n# of its former linear size, so every size-like parameter is scaled to match and\n# the bubble size scale is given an explicit, smaller output range.\nGEOM_SCALE <- 0.45\n\nshrink <- function(p) {\n    if (is.null(p)) return(NULL)\n    for (j in seq_along(p$layers)) {\n        cls <- class(p$layers[[j]]$geom)[1]\n        ap  <- p$layers[[j]]$aes_params\n        if (cls != \"GeomText\") {\n            # points, diamonds, CI bars and whiskers\n            for (k in c(\"size\", \"stroke\", \"linewidth\")) {\n                if (!is.null(ap[[k]]) && is.numeric(ap[[k]]))\n                    p$layers[[j]]$aes_params[[k]] <- ap[[k]] * GEOM_SCALE\n            }\n            next\n        }\n        # Unconditional: a text layer with no explicit size would otherwise keep\n        # ggplot2's 3.88 mm (~11 pt) default and dominate the smaller canvas.\n        p$layers[[j]]$aes_params$size <- 1.8\n        # Half the panel width, so the full method names no longer fit and the\n        # right-hand annotation clipped. The caption and the colours identify\n        # which estimator is which, so the prefixes can be abbreviated.\n        lab <- p$layers[[j]]$aes_params$label\n        if (!is.null(lab) && is.character(lab)) {\n            lab <- sub(\"Bias-Corrected \\\\(Nakagawa\\\\): \", \"Corrected: \", lab)\n            lab <- sub(\"Bias-Robust \\\\(Yang\\\\): \",        \"Robust: \",    lab)\n            p$layers[[j]]$aes_params$label <- lab\n        }\n    }\n    suppressMessages(\n        p +\n        # the precision bubbles: default output range is 1-6 mm, far too big here\n        ggplot2::scale_size_continuous(range = c(0.3, 2.3)) +\n        ggplot2::theme(\n            plot.title  = ggplot2::element_text(size = 7, face = \"bold\", hjust = 0.5),\n            axis.text   = ggplot2::element_text(size = 5.5),\n            axis.title  = ggplot2::element_text(size = 6.5),\n            legend.position = \"none\",\n            plot.margin = ggplot2::margin(1, 2, 1, 1, \"mm\")\n        )\n    )\n}\n\ncol_A <- (shrink(ph_orig) / shrink(ph_new) / shrink(ph_comb))\ncol_B <- (shrink(po_orig) / shrink(po_new) / shrink(po_comb))\n\nhdr <- function(x, lab) patchwork::wrap_elements(\n    x + patchwork::plot_annotation(\n        title = lab,\n        theme = ggplot2::theme(\n            plot.title  = ggplot2::element_text(size = 9, face = \"bold\", hjust = 0.5),\n            plot.margin = ggplot2::margin(0, 0, 0, 0, \"mm\"))))\n\nfig_corr_combined <- patchwork::wrap_plots(\n    hdr(col_A, \"(A)  Hedges' g scale\"),\n    hdr(col_B, \"(B)  Log odds ratio scale\"), ncol = 2)\n\nsave_deliverable_fig(fig_corr_combined, \"correction_comparison_combined\",\n                     width = 180 / 25.4, height = 210 / 25.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsaved: correction_comparison_combined (.pdf + .png)\n```\n\n\n:::\n\n```{.r .cell-code}\nfig_corr_combined\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/correction_comparison_combined-1.png){width=680.64}\n:::\n:::\n\n\n---\n\n## Taxonomic Moderator (Heteroscedastic Model) {#sec-taxonomic-moderator}\n\nThe combined synthesis pools effect sizes across very different organisms — insects and other arthropods, ray-finned fishes, and the remaining vertebrates (birds and mammals). Two questions follow naturally: does the *average* strength of mate-choice copying differ among these groups, and is the *amount of heterogeneity* itself group-specific? To answer both we fit a single `rma.mv` model with **taxonomic group as a categorical moderator** and a **heteroscedastic** random-effects structure that lets the variance components differ across groups.\n\nThree design choices define this model:\n\n* **Taxonomic grouping.** Each species (full binomial) is assigned to **Arthropods**, **Fish**, or **Other Vertebrates** by genus. The genus uniquely determines the class for every species in these data, so the mapping is unambiguous (verified in the table below).\n* **No phylogenetic term.** The heterogeneity decomposition shows the phylogenetic component contributes very little variance, so it is dropped here; the species random intercept (`taxonomySpecies`) still absorbs among-species differences within each group.\n* **Heteroscedasticity (`struct = \"HCS\"`, `rho = 0`).** The **residual (within-study) effect-size** variance is allowed to take a separate value in each taxonomic group, over a single pooled between-study variance, rather than forcing one common residual variance. This follows the `orchaRd` 2.0 recommendation for meta-regression with heterogeneous variances [@nakagawaOrchaRd2Visualising2023]: the heteroscedastic random term is written as an `~ moderator | unit` formula (`~ tax_group | identifierEffectSizeID`) with a heteroscedastic compound-symmetry structure and the between-level covariance fixed to zero (`rho = 0`), since each effect size belongs to exactly one taxonomic group and a cross-group covariance is not identifiable. (A fuller structure that *also* made the between-study variance group-specific was considered but dropped: its per-group between-study variances collapse to zero for the groups with few studies, so it is over-parameterised for these data.)\n* **Marginalised means.** The moderator is fitted **with an intercept** (`mods = ~ tax_group`) and the per-group means, confidence intervals, and prediction intervals are obtained as **marginalised means** through `orchaRd::mod_results()` (which calls `emmeans` internally), again as recommended in the `orchaRd` 2.0 workflow. The overall test for differences among groups is the model's omnibus moderator test ($Q_M$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------------------\n# Genus-based taxonomic classification of the combined-dataset species.\n# Classification keys on the FULL binomial (`species_phylo`); the genus alone\n# unambiguously determines the class for every species in these datasets\n# (cross-checked against the higher-taxon cascade in build_phylogeny.R).\n# ---------------------------------------------------------------------------\narthropod_genera <- c(\"Drosophila\", \"Enchenopa\", \"Schizocosa\", \"Uca\")\nfish_genera <- c(\n    \"Amblyglyphidodon\", \"Brachyrhaphis\", \"Danio\", \"Etheostoma\", \"Gambusia\",\n    \"Gasterosteus\", \"Limia\", \"Oryzias\", \"Poecilia\", \"Pomatoschistus\",\n    \"Porichthys\", \"Rhabdoblennius\", \"Syngnathus\"\n)\nothervert_genera <- c(\"Coturnix\", \"Dama\", \"Ficedula\", \"Molothrus\", \"Mus\", \"Rattus\", \"Taeniopygia\")\n\ntax_levels  <- c(\"Arthropods\", \"Fish\", \"Other Vertebrates\")\ntax_palette <- c(\"Arthropods\" = \"#E69F00\", \"Fish\" = \"#56B4E9\", \"Other Vertebrates\" = \"#009E73\")\n\nclassify_taxon <- function(binomial) {\n    genus <- stringr::word(as.character(binomial), 1)\n    grp <- dplyr::case_when(\n        genus %in% arthropod_genera ~ \"Arthropods\",\n        genus %in% fish_genera      ~ \"Fish\",\n        genus %in% othervert_genera ~ \"Other Vertebrates\",\n        TRUE                        ~ NA_character_\n    )\n    factor(grp, levels = tax_levels)\n}\n\n# Add the taxonomic group to the combined Hedges' g and log OR datasets.\ndb_hedges_tax <- db_hedges %>% mutate(tax_group = classify_taxon(species_phylo))\ndb_or_tax     <- db_or     %>% mutate(tax_group = classify_taxon(species_phylo))\n\n# Defensive check: every species should be classified.\nunmapped_tax <- sort(unique(as.character(c(\n    db_hedges_tax$species_phylo[is.na(db_hedges_tax$tax_group)],\n    db_or_tax$species_phylo[is.na(db_or_tax$tax_group)]\n))))\nif (length(unmapped_tax) > 0) {\n    warning(\"Unclassified species (no taxonomic group): \", paste(unmapped_tax, collapse = \", \"))\n}\n```\n:::\n\n\n### Species-to-Group Mapping (verification)\n\nThe table below lists every species in the combined datasets, its full binomial, the species level used as a random effect (the epithet), and the taxonomic group it was assigned to, with the number of effect sizes it contributes to each effect-size class. This is the audit the analysis is built on — each row should look correct.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-272ca97d3424d5997841\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-272ca97d3424d5997841\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Each combined-dataset species, its assigned taxonomic group, and the number of effect sizes it contributes to the Hedges' g and log OR classes. Use this to confirm the categorical variable matches the original species.<\\/caption>\",\"data\":[[\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Arthropods\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Fish\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\",\"Other Vertebrates\"],[\"Drosophila melanogaster\",\"Drosophila serrata\",\"Drosophila simulans\",\"Drosophila subobscura\",\"Enchenopa binotata\",\"Schizocosa ocreata\",\"Schizocosa ocreata\",\"Uca mjoebergi\",\"Amblyglyphidodon leucogaster\",\"Brachyrhaphis rhabdophora\",\"Danio rerio\",\"Etheostoma flabellare\",\"Etheostoma olmstedi\",\"Etheostoma zonale\",\"Gambusia holbrooki\",\"Gasterosteus aculeatus\",\"Limia nigrofasciata\",\"Limia perugiae\",\"Oryzias latipes\",\"Poecilia formosa\",\"Poecilia latipinna\",\"Poecilia mexicana\",\"Poecilia reticulata\",\"Pomatoschistus minutus\",\"Pomatoschistus minutus\",\"Porichthys notatus\",\"Rhabdoblennius nitidus\",\"Syngnathus typhle\",\"Coturnix japonica\",\"Dama dama\",\"Ficedula hypoleuca\",\"Molothrus ater\",\"Mus musculus\",\"Rattus norvegicus\",\"Taeniopygia guttata\",\"Taeniopygia guttata\"],[\"melanogaster\",\"serrata\",\"simulans\",\"subobscura\",\"binotata\",\"ocreata\",\"schizocosa\",\"mjoebergi\",\"leucogaster\",\"rhabdophora\",\"rerio\",\"flabellare\",\"olmstedi\",\"zonale\",\"holbrooki\",\"aculeatus\",\"nigrofasciata\",\"perugiae\",\"latipes\",\"formosa\",\"latipinna\",\"mexicana\",\"reticulata\",\"minutu\",\"minutus\",\"notatus\",\"nitidus\",\"typhle\",\"japonica\",\"dama\",\"hypoleuca\",\"ater\",\"musculus\",\"norvegicus\",\"castanotis\",\"guttata\"],[50,2,1,4,6,0,1,1,0,1,1,4,0,4,2,6,4,4,2,2,28,9,54,0,2,3,2,4,11,3,1,0,2,3,3,7],[63,2,1,4,6,2,0,1,4,1,1,2,2,2,0,2,2,2,3,0,13,6,35,2,0,3,1,0,3,0,1,2,2,0,3,1]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Taxonomic group<\\/th>\\n      <th>Species (full binomial)<\\/th>\\n      <th>Species level (epithet)<\\/th>\\n      <th>Hedges' g<\\/th>\\n      <th>Log OR<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"tip\",\"pageLength\":40,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Taxonomic group\",\"targets\":0},{\"name\":\"Species (full binomial)\",\"targets\":1},{\"name\":\"Species level (epithet)\",\"targets\":2},{\"name\":\"Hedges' g\",\"targets\":3},{\"name\":\"Log OR\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,25,40,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Model Fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------------------\n# Heteroscedastic taxonomic-moderator model, following the orchaRd 2.0\n# heterogeneous-variance workflow (Nakagawa et al. 2023, vignette Example 4).\n#\n# * The moderator is fitted WITH an intercept (`mods = ~ tax_group`); per-group\n#   means / CIs / PIs are obtained downstream as marginalised means via\n#   orchaRd::mod_results() (emmeans), and the among-group test is the model's\n#   omnibus moderator test (QM).\n# * The heterogeneous (residual) variance is specified as a `~ tax_group | unit`\n#   random term with struct = \"HCS\" and the between-level covariance fixed to\n#   zero (rho = 0) — exactly the structure used in the orchaRd documentation.\n#   With each unit belonging to a single group this estimates one residual\n#   variance per group with no cross-group covariance.\n# * PRIMARY structure: group-specific RESIDUAL variance\n#   (`~ tax_group | identifierEffectSizeID`) over a single pooled between-study\n#   variance (`~ 1 | identifierStudyId`), a homoscedastic species intercept\n#   (`~ 1 | taxonomySpecies`), AND the phylogenetic correlation term\n#   (`~ 1 | species_phylo` with `R =`), so that the moderator models match the\n#   random-effects structure of the intercept-only models. If that fit fails the\n#   cascade falls back to the same structure without phylogeny, then to the\n#   homoscedastic variants; the cascade log records which was used, giving an\n#   empirical justification for whatever structure the manuscript reports.\n#   (The fuller both-level heteroscedastic structure -- per-group BETWEEN-STUDY\n#   variances as well -- remains excluded: those variances collapse to the zero\n#   boundary for the thin groups, i.e. it is over-parameterised for these data.)\n# * Each heteroscedastic structure is tried with several optimisers (nlminb,\n#   optim/BFGS, optim/L-BFGS-B, then a high-iteration Nelder-Mead) before being\n#   declared a failure; only if none converge does the cascade fall back to a\n#   simpler structure. The vignette's default Nelder-Mead alone hits its\n#   iteration cap on these data (convergence = 1), so robust optimisers go first.\n# ---------------------------------------------------------------------------\nfit_taxon_hetero_mv <- function(dat, group_var = \"tax_group\", yi = \"yi\", vi = \"vi\",\n                                cluster_var = \"identifierStudyId\",\n                                obs_var = \"identifierEffectSizeID\", rho = 0.5,\n                                phylo_cor = NULL, phylo_var = \"species_phylo\") {\n    dat2 <- dat %>%\n        filter(!is.na(.data[[yi]]), !is.na(.data[[vi]]), .data[[vi]] > 0, !is.na(.data[[group_var]]))\n    if (nrow(dat2) == 0) {\n        message(\"No complete cases found.\")\n        return(NULL)\n    }\n    dat2[[group_var]] <- droplevels(factor(dat2[[group_var]], levels = tax_levels))\n\n    VCV <- metafor::vcalc(vi = dat2[[vi]], cluster = dat2[[cluster_var]], obs = dat2[[obs_var]], rho = rho, data = dat2)\n\n    mods_f  <- stats::as.formula(paste0(\"~ \", group_var))                       # intercept-coded\n    obs_f   <- stats::as.formula(paste0(\"~ \", group_var, \" | \", obs_var))       # heteroscedastic residual\n\n    # Optimisers tried (in order) for the heteroscedastic structures. The default\n    # Nelder-Mead used in the orchaRd vignette hits its iteration cap on these\n    # data (convergence = 1), so we lead with the more robust derivative-based\n    # optimisers and only then fall back to a high-iteration Nelder-Mead.\n    opt_grid <- list(\n        \"nlminb\"            = list(optimizer = \"nlminb\", iter.max = 10000, eval.max = 10000),\n        \"optim/BFGS\"        = list(optimizer = \"optim\", optmethod = \"BFGS\", maxit = 10000),\n        \"optim/L-BFGS-B\"    = list(optimizer = \"optim\", optmethod = \"L-BFGS-B\", maxit = 10000),\n        \"optim/Nelder-Mead\" = list(optimizer = \"optim\", optmethod = \"Nelder-Mead\", maxit = 50000, reltol = 1e-9)\n    )\n\n    # Build one rma.mv call for a candidate structure + optimiser control.\n    build <- function(cand, ctrl) {\n        args <- c(\n            list(yi = dat2[[yi]], V = VCV, mods = mods_f, random = cand$random,\n                 test = \"t\", dfs = \"contain\", method = \"REML\", sparse = TRUE, data = dat2),\n            cand$args\n        )\n        if (!is.null(cand$struct)) args$struct <- cand$struct\n        if (!is.null(cand$R))      args$R      <- cand$R\n        if (!is.null(ctrl))        args$control <- ctrl\n        do.call(metafor::rma.mv, args)\n    }\n\n    # Candidate structures, tried in order. The cascade stops at the FIRST one\n    # that fits without error; warnings do NOT stop the cascade but are recorded.\n    # PRIMARY = residual-only HCS (orchaRd Example 4 default): a single pooled\n    # between-study variance plus a group-specific residual variance. The fuller\n    # both-level structure was dropped because its per-group between-study\n    # variances collapse to the zero boundary for the thin groups (Other\n    # Vertebrates, Arthropods) — i.e. it is over-parameterised for these data.\n    # Build the optional phylogenetic term, mirroring fit_overall_mv(). The\n    # phylogenetic candidates are tried FIRST so that the taxon-moderator models\n    # match the random-effects structure of the intercept-only models. If\n    # HCS + phylogeny is over-parameterised for these data the cascade falls back\n    # automatically, and the recorded cascade log then documents WHY the\n    # phylogenetic term was dropped -- which is exactly what the manuscript needs\n    # to state.\n    phylo_random <- NULL\n    R_arg <- NULL\n    if (!is.null(phylo_cor) && phylo_var %in% colnames(dat2)) {\n        sp <- unique(as.character(dat2[[phylo_var]]))\n        missing_sp <- setdiff(sp, rownames(phylo_cor))\n        if (length(missing_sp) == 0) {\n            dat2[[phylo_var]] <- factor(as.character(dat2[[phylo_var]]))\n            phylo_random <- stats::as.formula(paste0(\"~ 1 | \", phylo_var))\n            R_arg <- stats::setNames(list(phylo_cor[sp, sp, drop = FALSE]), phylo_var)\n        } else {\n            warning(\n                \"Phylogenetic random effect unavailable for taxon model (species absent from correlation matrix): \",\n                paste(missing_sp, collapse = \", \")\n            )\n        }\n    }\n\n    candidates <- list()\n    if (!is.null(phylo_random)) {\n        candidates <- c(candidates, list(\n            list(spec = \"Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0)\",\n                 random = list(~ 1 | identifierStudyId, obs_f, ~ 1 | taxonomySpecies, phylo_random),\n                 struct = \"HCS\", args = list(rho = 0), R = R_arg, het = TRUE),\n            list(spec = \"Homoscedastic + phylogeny (single variance per component)\",\n                 random = list(~ 1 | identifierStudyId, ~ 1 | identifierEffectSizeID, ~ 1 | taxonomySpecies, phylo_random),\n                 struct = NULL, args = list(), R = R_arg, het = FALSE)\n        ))\n    }\n    candidates <- c(candidates, list(\n        list(spec = \"Heteroscedastic (residual only, per group; HCS, rho = 0)\",\n             random = list(~ 1 | identifierStudyId, obs_f, ~ 1 | taxonomySpecies),\n             struct = \"HCS\", args = list(rho = 0), het = TRUE),\n        list(spec = \"Homoscedastic (single variance per component)\",\n             random = list(~ 1 | identifierStudyId, ~ 1 | identifierEffectSizeID, ~ 1 | taxonomySpecies),\n             struct = NULL, args = list(), het = FALSE)\n    ))\n\n    # Attempt one candidate. Heteroscedastic structures cycle through opt_grid\n    # until one converges; the homoscedastic structure uses the metafor default.\n    # Errors AND warnings are captured (warnings do not abort).\n    fit_once <- function(cand, ctrl) {\n        warns <- character(0)\n        t0 <- Sys.time()\n        mod <- tryCatch(\n            withCallingHandlers(\n                build(cand, ctrl),\n                warning = function(w) {\n                    warns[[length(warns) + 1L]] <<- conditionMessage(w)\n                    invokeRestart(\"muffleWarning\")\n                }\n            ),\n            error = function(e) structure(list(msg = conditionMessage(e)), class = \"tax_fit_error\")\n        )\n        list(mod = mod, warns = warns, secs = as.numeric(difftime(Sys.time(), t0, units = \"secs\")))\n    }\n\n    attempt <- function(cand) {\n        if (!isTRUE(cand$het)) {\n            r <- fit_once(cand, NULL)\n            failed <- inherits(r$mod, \"tax_fit_error\")\n            return(list(model = if (failed) NULL else r$mod, failed = failed,\n                        error = if (failed) r$mod$msg else NA_character_,\n                        warnings = r$warns, secs = r$secs, optimizer = \"default (nlminb)\"))\n        }\n        msgs <- character(0)\n        total <- 0\n        for (onm in names(opt_grid)) {\n            r <- fit_once(cand, opt_grid[[onm]])\n            total <- total + r$secs\n            if (!inherits(r$mod, \"tax_fit_error\")) {\n                return(list(model = r$mod, failed = FALSE, error = NA_character_,\n                            warnings = r$warns, secs = total, optimizer = onm))\n            }\n            msgs <- c(msgs, paste0(onm, \": \", r$mod$msg))\n        }\n        list(model = NULL, failed = TRUE, error = paste(msgs, collapse = \" || \"),\n             warnings = character(0), secs = total, optimizer = NA_character_)\n    }\n\n    diag_rows <- list()\n    chosen <- NULL\n    chosen_spec <- NA_character_\n    for (i in seq_along(candidates)) {\n        cand <- candidates[[i]]\n        if (!is.null(chosen)) {\n            diag_rows[[i]] <- tibble::tibble(\n                stage = i, structure = cand$spec, status = \"not attempted\", optimizer = NA_character_,\n                seconds = NA_real_, n_warnings = NA_integer_, detail = \"an earlier structure succeeded\"\n            )\n            next\n        }\n        a <- attempt(cand)\n        status <- if (a$failed) \"ERROR\" else if (length(a$warnings) > 0) \"OK (with warnings)\" else \"OK\"\n        detail <- if (a$failed) a$error else if (length(a$warnings) > 0) paste(a$warnings, collapse = \" || \") else \"clean fit\"\n        diag_rows[[i]] <- tibble::tibble(\n            stage = i, structure = cand$spec, status = status, optimizer = a$optimizer,\n            seconds = round(a$secs, 2), n_warnings = length(a$warnings), detail = detail\n        )\n        if (!a$failed) {\n            chosen <- a$model\n            chosen_spec <- cand$spec\n        }\n    }\n    diagnostics <- dplyr::bind_rows(diag_rows)\n\n    if (is.null(chosen)) {\n        warning(\"All taxonomic-moderator structures failed to fit.\")\n        return(list(data = dat2, VCV = VCV, model = NULL, spec = \"ALL FAILED\", diagnostics = diagnostics))\n    }\n    list(data = dat2, VCV = VCV, model = chosen, spec = chosen_spec, diagnostics = diagnostics)\n}\n\nres_tax_hedges <- fit_taxon_hetero_mv(db_hedges_tax, phylo_cor = phylo_cor_hedges)\nres_tax_or     <- fit_taxon_hetero_mv(db_or_tax,     phylo_cor = phylo_cor_or)\n\n# Omnibus among-group test. With the intercept-coded moderator, metafor's built-in\n# QM tests all non-intercept coefficients jointly — i.e. exactly whether the group\n# means differ — so it is used directly (no custom contrast matrix needed).\namong_group_test <- function(res) {\n    if (is.null(res) || is.null(res$model)) {\n        return(NULL)\n    }\n    list(QM = res$model$QM, QMp = res$model$QMp, QMdf = res$model$QMdf)\n}\nqm_tax_hedges <- among_group_test(res_tax_hedges)\nqm_tax_or     <- among_group_test(res_tax_or)\n\n# Total I^2 (orchaRd if available; otherwise a Higgins typical-variance fallback\n# so a heterogeneity figure is always reported even under the heteroscedastic\n# structure).\ntotal_i2 <- function(res) {\n    if (is.null(res) || is.null(res$model)) {\n        return(NA_real_)\n    }\n    m <- res$model\n    i2 <- tryCatch(orchaRd::i2_ml(m), error = function(e) NULL)\n    if (!is.null(i2) && any(grepl(\"Total\", names(i2)))) {\n        return(as.numeric(i2[grep(\"Total\", names(i2))[1]]))\n    }\n    vi <- res$data$vi\n    wi <- 1 / vi\n    k  <- length(vi)\n    s2 <- (k - 1) * sum(wi) / (sum(wi)^2 - sum(wi^2))\n    vc <- sum(c(m$sigma2, m$tau2, m$gamma2), na.rm = TRUE)\n    100 * vc / (vc + s2)\n}\ni2_tax_hedges <- total_i2(res_tax_hedges)\ni2_tax_or     <- total_i2(res_tax_or)\n\n# Persist the fitted results + cascade diagnostics so they can be inspected\n# interactively in an R session WITHOUT re-rendering the book, e.g.:\n#   b <- readRDS(\"outputs/1_effect_size_calculation_pipeline/taxon_model_fits.rds\")\n#   b$hedges$spec ; b$hedges$diagnostics ; summary(b$hedges$model)\n# (also consumed by scripts/1_effect_size_calculation_pipeline/diagnose_taxon_model.R)\ntryCatch({\n    tax_out_dir <- here::here(\"outputs\", \"1_effect_size_calculation_pipeline\")\n    dir.create(tax_out_dir, recursive = TRUE, showWarnings = FALSE)\n    saveRDS(\n        list(\n            hedges = res_tax_hedges, or = res_tax_or,\n            qm = list(hedges = qm_tax_hedges, or = qm_tax_or),\n            i2 = list(hedges = i2_tax_hedges, or = i2_tax_or),\n            saved_at = Sys.time()\n        ),\n        file.path(tax_out_dir, \"taxon_model_fits.rds\")\n    )\n}, error = function(e) warning(\"Could not save taxon_model_fits.rds: \", conditionMessage(e)))\n```\n:::\n\n\n### Fit Diagnostics {#sec-taxon-fit-diagnostics}\n\nThe model is fitted through a **fallback cascade**: the most flexible heteroscedastic structure is attempted first, and only if it *errors* does the next-simpler structure get tried (warnings do **not** trigger a fallback, but are captured and shown). The report below tells you exactly what happened for each effect-size class — which structures were attempted, whether each fit was clean / produced warnings / errored (with the captured message), how long it took, which structure was ultimately used, the per-group sample sizes, and the variance components of the chosen model (so you can see whether any group's variance collapsed to the zero boundary).\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========================================================\n FIT DIAGNOSTIC: Hedges' g \n========================================================\n  Chosen structure : Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0) \n  Model is NULL    : FALSE \n\n  Cascade log:\n stage structure                                                           \n 1     Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0)\n 2     Homoscedastic + phylogeny (single variance per component)           \n 3     Heteroscedastic (residual only, per group; HCS, rho = 0)            \n 4     Homoscedastic (single variance per component)                       \n status        optimizer seconds n_warnings detail                        \n OK            nlminb    3.35     0         clean fit                     \n not attempted <NA>        NA    NA         an earlier structure succeeded\n not attempted <NA>        NA    NA         an earlier structure succeeded\n not attempted <NA>        NA    NA         an earlier structure succeeded\n\n  Per-group sample sizes:\n Taxonomic group   k (effect sizes) studies species\n Arthropods         65              22       7     \n Fish              132              46      17     \n Other Vertebrates  30              19       7     \n\n  Variance components (chosen model):\n Component                       Variance\n Residual σ² — Arthropods        0.12476 \n Residual σ² — Fish              0.52912 \n Residual σ² — Other Vertebrates 0.48318 \n Between-study τ²                0.02882 \n Species σ²                      0.01479 \n <NA>                            0.00000 \n  NOTE: 1 variance component(s) at/near zero (boundary estimate).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========================================================\n FIT DIAGNOSTIC: Log Odds Ratio \n========================================================\n  Chosen structure : Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0) \n  Model is NULL    : FALSE \n\n  Cascade log:\n stage structure                                                           \n 1     Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0)\n 2     Homoscedastic + phylogeny (single variance per component)           \n 3     Heteroscedastic (residual only, per group; HCS, rho = 0)            \n 4     Homoscedastic (single variance per component)                       \n status        optimizer seconds n_warnings detail                        \n OK            nlminb    2.01     0         clean fit                     \n not attempted <NA>        NA    NA         an earlier structure succeeded\n not attempted <NA>        NA    NA         an earlier structure succeeded\n not attempted <NA>        NA    NA         an earlier structure succeeded\n\n  Per-group sample sizes:\n Taxonomic group   k (effect sizes) studies species\n Arthropods        79               22       7     \n Fish              81               39      16     \n Other Vertebrates 12                8       6     \n\n  Variance components (chosen model):\n Component                       Variance\n Residual σ² — Arthropods        0.15312 \n Residual σ² — Fish              1.04230 \n Residual σ² — Other Vertebrates 0.30326 \n Between-study τ²                0.00000 \n Species σ²                      0.18939 \n <NA>                            0.00000 \n  NOTE: 2 variance component(s) at/near zero (boundary estimate).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-8deed2811bfb0c2a027a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8deed2811bfb0c2a027a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Fallback-cascade log: every candidate random-effects structure, whether it was attempted, its fit status (OK / OK with warnings / ERROR / not attempted), runtime in seconds, warning count, and the captured error or warning text. The first 'OK' row per analysis is the structure that was actually used.<\\/caption>\",\"data\":[[\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Log OR\",\"Log OR\",\"Log OR\",\"Log OR\"],[1,2,3,4,1,2,3,4],[\"Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0)\",\"Homoscedastic + phylogeny (single variance per component)\",\"Heteroscedastic (residual only, per group; HCS, rho = 0)\",\"Homoscedastic (single variance per component)\",\"Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0)\",\"Homoscedastic + phylogeny (single variance per component)\",\"Heteroscedastic (residual only, per group; HCS, rho = 0)\",\"Homoscedastic (single variance per component)\"],[\"OK\",\"not attempted\",\"not attempted\",\"not attempted\",\"OK\",\"not attempted\",\"not attempted\",\"not attempted\"],[\"nlminb\",null,null,null,\"nlminb\",null,null,null],[3.35,null,null,null,2.01,null,null,null],[0,null,null,null,0,null,null,null],[\"clean fit\",\"an earlier structure succeeded\",\"an earlier structure succeeded\",\"an earlier structure succeeded\",\"clean fit\",\"an earlier structure succeeded\",\"an earlier structure succeeded\",\"an earlier structure succeeded\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Analysis<\\/th>\\n      <th>stage<\\/th>\\n      <th>structure<\\/th>\\n      <th>status<\\/th>\\n      <th>optimizer<\\/th>\\n      <th>seconds<\\/th>\\n      <th>n_warnings<\\/th>\\n      <th>detail<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":12,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"name\":\"Analysis\",\"targets\":0},{\"name\":\"stage\",\"targets\":1},{\"name\":\"structure\",\"targets\":2},{\"name\":\"status\",\"targets\":3},{\"name\":\"optimizer\",\"targets\":4},{\"name\":\"seconds\",\"targets\":5},{\"name\":\"n_warnings\",\"targets\":6},{\"name\":\"detail\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Model Output: Hedges' $g$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom-effects structure: Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0) \n\n\nMultivariate Meta-Analysis Model (k = 227; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-241.9473   483.8947   501.8947   532.5995   502.7358   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed             factor    R \nsigma^2.1  0.0288  0.1698     87     no  identifierStudyId   no \nsigma^2.2  0.0148  0.1216     31     no    taxonomySpecies   no \nsigma^2.3  0.0000  0.0001     30     no      species_phylo  yes \n\nouter factor: identifierEffectSizeID (nlvls = 227)\ninner factor: tax_group              (nlvls = 3)\n\n            estim    sqrt  k.lvl  fixed              level \ntau^2.1    0.1248  0.3532     65     no         Arthropods \ntau^2.2    0.5291  0.7274    132     no               Fish \ntau^2.3    0.4832  0.6951     30     no  Other Vertebrates \nrho        0.0000                   yes                    \n\nTest for Residual Heterogeneity:\nQE(df = 224) = 1382.2337, p-val < .0001\n\nTest of Moderators (coefficients 2:3):\nF(df1 = 2, df2 = 27) = 3.0033, p-val = 0.0664\n\nModel Results:\n\n                            estimate      se    tval  df    pval    ci.lb \nintrcpt                       0.2471  0.1067  2.3157  27  0.0284   0.0282 \ntax_groupFish                 0.2516  0.1450  1.7353  27  0.0941  -0.0459 \ntax_groupOther Vertebrates    0.4564  0.2010  2.2710  27  0.0313   0.0441 \n                             ci.ub    \nintrcpt                     0.4660  * \ntax_groupFish               0.5492  . \ntax_groupOther Vertebrates  0.8688  * \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Model Output: Log Odds Ratio\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom-effects structure: Heteroscedastic + phylogeny (residual only, per group; HCS, rho = 0) \n\n\nMultivariate Meta-Analysis Model (k = 172; method: REML)\n\n   logLik   Deviance        AIC        BIC       AICc   \n-211.1938   422.3876   440.3876   468.5567   441.5197   \n\nVariance Components:\n\n            estim    sqrt  nlvls  fixed             factor    R \nsigma^2.1  0.0000  0.0000     69     no  identifierStudyId   no \nsigma^2.2  0.1894  0.4352     29     no    taxonomySpecies   no \nsigma^2.3  0.0000  0.0001     28     no      species_phylo  yes \n\nouter factor: identifierEffectSizeID (nlvls = 172)\ninner factor: tax_group              (nlvls = 3)\n\n            estim    sqrt  k.lvl  fixed              level \ntau^2.1    0.1531  0.3913     79     no         Arthropods \ntau^2.2    1.0423  1.0209     81     no               Fish \ntau^2.3    0.3033  0.5507     12     no  Other Vertebrates \nrho        0.0000                   yes                    \n\nTest for Residual Heterogeneity:\nQE(df = 169) = 609.1379, p-val < .0001\n\nTest of Moderators (coefficients 2:3):\nF(df1 = 2, df2 = 25) = 1.1697, p-val = 0.3269\n\nModel Results:\n\n                            estimate      se    tval  df    pval    ci.lb \nintrcpt                       0.3346  0.2275  1.4706  25  0.1539  -0.1340 \ntax_groupFish                 0.4810  0.3147  1.5284  25  0.1390  -0.1672 \ntax_groupOther Vertebrates    0.2718  0.3864  0.7036  25  0.4882  -0.5239 \n                             ci.ub    \nintrcpt                     0.8032    \ntax_groupFish               1.1291    \ntax_groupOther Vertebrates  1.0676    \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Group Means and Heterogeneity\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c432ba7e727bb2b68e4a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c432ba7e727bb2b68e4a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Estimated mean effect (with 95% confidence and prediction intervals) for each taxonomic group, from the heteroscedastic moderator models.<\\/caption>\",\"data\":[[\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Log OR\",\"Log OR\",\"Log OR\"],[\"Arthropods\",\"Fish\",\"Other Vertebrates\",\"Arthropods\",\"Fish\",\"Other Vertebrates\"],[0.247,0.499,0.703,0.335,0.8159999999999999,0.606],[0.028,0.297,0.354,-0.134,0.368,-0.037],[0.466,0.7,1.053,0.803,1.263,1.25],[-1.148,-0.894,-0.718,-1.534,-1.048,-1.314],[1.642,1.891,2.125,2.204,2.679,2.527]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Analysis<\\/th>\\n      <th>Taxonomic group<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>CI lower<\\/th>\\n      <th>CI upper<\\/th>\\n      <th>PI lower<\\/th>\\n      <th>PI upper<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":12,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Analysis\",\"targets\":0},{\"name\":\"Taxonomic group\",\"targets\":1},{\"name\":\"Estimate\",\"targets\":2},{\"name\":\"CI lower\",\"targets\":3},{\"name\":\"CI upper\",\"targets\":4},{\"name\":\"PI lower\",\"targets\":5},{\"name\":\"PI upper\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-6ffdc69004f02a4ac8db\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6ffdc69004f02a4ac8db\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Variance components from the heteroscedastic models. Under the both-DIAG structure the between-study and residual variances are estimated separately within each taxonomic group; the species component is shared.<\\/caption>\",\"data\":[[\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Hedges' g\",\"Log OR\",\"Log OR\",\"Log OR\",\"Log OR\",\"Log OR\",\"Log OR\"],[\"Residual σ² — Arthropods\",\"Residual σ² — Fish\",\"Residual σ² — Other Vertebrates\",\"Between-study τ²\",\"Species σ²\",null,\"Residual σ² — Arthropods\",\"Residual σ² — Fish\",\"Residual σ² — Other Vertebrates\",\"Between-study τ²\",\"Species σ²\",null],[0.12476,0.52912,0.48318,0.02882,0.01479,0,0.15312,1.0423,0.30326,0,0.18939,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Analysis<\\/th>\\n      <th>Component<\\/th>\\n      <th>Variance<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":20,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Analysis\",\"targets\":0},{\"name\":\"Component\",\"targets\":1},{\"name\":\"Variance\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,20,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\nFor Hedges' $g$, total heterogeneity is 94.2% and the among-group test is p = 0.066 (Wald $Q_M$ = 3.00), so the difference among taxonomic groups is **non-significant**. For the log odds ratio, total heterogeneity is 89.5% and the among-group test is p = 0.327 (Wald $Q_M$ = 1.17), a **non-significant** difference among groups. The group means and their intervals are tabulated above; the variance-component table shows the group-specific residual (within-study) variances, which is where the heteroscedastic structure lets variability differ across the three groups.\n\n### Orchard Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_taxon_orchard <- function(res, xlab, title) {\n    if (is.null(res) || is.null(res$model)) {\n        return(NULL)\n    }\n    mr <- orchaRd::mod_results(res$model, mod = \"tax_group\", group = \"identifierStudyId\")\n    oc <- orchaRd::orchard_plot(mr, xlab = xlab, angle = 0, g = TRUE, k = TRUE)\n    # Replace each group's k-count label with \"estimate [95% CI]\\nk = K (studies)\"\n    # using the same helper as the overall plots. tryCatch guards against any\n    # orchaRd layer-order change so the figure still renders if it fails.\n    oc <- tryCatch(add_ci_labels(oc, mr), error = function(e) {\n        warning(\"add_ci_labels (taxon) failed: \", conditionMessage(e)); oc\n    })\n    oc +\n        ggplot2::scale_colour_manual(values = tax_palette, name = \"Taxonomic group\", aesthetics = c(\"colour\", \"fill\")) +\n        ggplot2::ggtitle(title) +\n        ggplot2::theme(\n            plot.title = ggplot2::element_text(face = \"bold\", hjust = 0.5),\n            legend.position = \"none\"\n        )\n}\n\n# Save a figure as a proper deliverable (PNG + PDF) in outputs/.\nsave_taxon_fig <- function(plot_obj, basename, width = 10, height = 9) {\n    if (is.null(plot_obj)) {\n        return(invisible())\n    }\n    tryCatch({\n        d <- here::here(\"outputs\", \"1_effect_size_calculation_pipeline\")\n        dir.create(d, recursive = TRUE, showWarnings = FALSE)\n        ggplot2::ggsave(file.path(d, paste0(basename, \".png\")), plot_obj, width = width, height = height, dpi = 300, bg = \"white\")\n        ggplot2::ggsave(file.path(d, paste0(basename, \".pdf\")), plot_obj, width = width, height = height)\n    }, error = function(e) stop(\"Could not save \", basename, \": \", conditionMessage(e)))\n    for (ext in c(\".pdf\", \".png\")) {\n        p <- file.path(here::here(\"outputs\", \"1_effect_size_calculation_pipeline\"), paste0(basename, ext))\n        if (!file.exists(p) || difftime(Sys.time(), file.mtime(p), units = \"mins\") > 5)\n            stop(\"Stale or missing figure: \", p, \" -- is it open in a viewer?\")\n    }\n}\n\np_tax_h <- plot_taxon_orchard(res_tax_hedges, \"Hedges' g\", \"Hedges' g by taxonomic group\")\np_tax_o <- plot_taxon_orchard(res_tax_or, \"Log Odds Ratio (lnOR)\", \"Log OR by taxonomic group\")\n\n# Save the individual panels too, in case they are wanted separately.\nsave_taxon_fig(p_tax_h, \"taxon_moderator_orchard_hedges\", width = 10, height = 5)\nsave_taxon_fig(p_tax_o, \"taxon_moderator_orchard_or\", width = 10, height = 5)\n\nif (!is.null(p_tax_h) && !is.null(p_tax_o)) {\n    # Biology Open specifies bold UPPERCASE panel letters (A, B, C, ...) at 12 pt\n    # final size. This figure is drawn at 10 in (254 mm) wide and the journal\n    # caps a display item at 180 mm, so it is reduced to about 71% at\n    # typesetting; the tag is therefore drawn at 17 pt to land near 12 pt on the\n    # page.\n    fig_tax <- (p_tax_h / p_tax_o) +\n        patchwork::plot_annotation(\n            tag_levels = \"A\", tag_prefix = \"(\", tag_suffix = \")\",\n            title = \"Mate-choice copying by taxonomic group (heteroscedastic moderator model)\",\n            theme = ggplot2::theme(\n                plot.title = ggplot2::element_text(size = 15, face = \"bold\", hjust = 0.5),\n                plot.tag   = ggplot2::element_text(size = 17, face = \"bold\")\n            )\n        )\n    print(fig_tax)\n    # Combined stacked figure = the main deliverable.\n    save_taxon_fig(fig_tax, \"taxon_moderator_orchard\", width = 10, height = 9)\n} else {\n    if (!is.null(p_tax_h)) print(p_tax_h)\n    if (!is.null(p_tax_o)) print(p_tax_o)\n}\n```\n\n::: {.cell-output-display}\n![](overall_effect_files/figure-html/taxon_orchard_plots-1.png){width=960}\n:::\n:::\n\n\n---\n\n## Heterogeneity Decomposition (Partial $I^2$) {#sec-heterogeneity}\n\nTotal heterogeneity ($I^2_{\\text{Total}}$) quantifies the proportion of variance in the observed effect sizes that reflects true differences among effects rather than sampling error. In a multilevel model this total can be *partitioned* into the contribution of each random effect [@nakagawaMethodsTestingPublication2022]. Here the variance is split among four components: between-**study** differences, the residual **effect-size** (within-study) level, a **species** (non-phylogenetic) component, and a **phylogenetic** component that captures variance shared among species in proportion to their relatedness. We compute these partial $I^2$ values with `orchaRd::i2_ml()` for each uncorrected model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Human-readable labels for the i2_ml components (names are prefixed with \"I2_\")\ncomp_labels <- c(\n    Total                  = \"Total\",\n    identifierStudyId      = \"Study\",\n    identifierEffectSizeID = \"Effect size (residual)\",\n    taxonomySpecies        = \"Species (non-phylogenetic)\",\n    species_phylo          = \"Phylogeny\"\n)\n\n# Pull the partial I^2 vector from a fitted model into tidy long form\nget_i2 <- function(res, effect, model) {\n    if (is.null(res) || is.null(res$model)) {\n        return(NULL)\n    }\n    v <- tryCatch(orchaRd::i2_ml(res$model), error = function(e) NULL)\n    if (is.null(v)) {\n        return(NULL)\n    }\n    tibble::tibble(\n        Effect    = effect,\n        Model     = model,\n        Component = sub(\"^I2_\", \"\", names(v)),\n        I2        = as.numeric(v)\n    )\n}\n\ni2_long <- dplyr::bind_rows(\n    get_i2(res_hedges_new, \"Hedges' g\", \"New Only\"),\n    get_i2(res_hedges_orig, \"Hedges' g\", \"Original Only\"),\n    get_i2(res_hedges_comb, \"Hedges' g\", \"Combined\"),\n    get_i2(res_or_new, \"Log OR\", \"New Only\"),\n    get_i2(res_or_orig, \"Log OR\", \"Original Only\"),\n    get_i2(res_or_comb, \"Log OR\", \"Combined\")\n) %>%\n    mutate(ComponentLabel = dplyr::recode(Component, !!!comp_labels))\n\n# Lookup helper for inline narrative (returns NA if a component is absent)\ni2get <- function(effect, model, component) {\n    v <- i2_long$I2[i2_long$Effect == effect & i2_long$Model == model & i2_long$ComponentLabel == component]\n    if (length(v) == 0 || all(is.na(v))) NA_real_ else v[1]\n}\n```\n:::\n\n\n### Partial $I^2$ by Random Effect\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5aeee439b0e10866dfe9\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5aeee439b0e10866dfe9\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Partial I² (%) for each random effect across the uncorrected multilevel models. Total is the overall proportion of variance due to heterogeneity (vs. sampling error); the remaining columns partition that heterogeneity among the study, residual effect-size, non-phylogenetic species, and phylogenetic components.<\\/caption>\",\"data\":[[\"Hedges' g — New Only\",\"Hedges' g — Original Only\",\"Hedges' g — Combined\",\"Log OR — New Only\",\"Log OR — Original Only\",\"Log OR — Combined\"],[80.8,85.8,85.5,80.8,75.90000000000001,74.7],[0,4.1,10.5,0,0,4.3],[51.3,77.09999999999999,69.8,51.3,23.2,45.4],[29.4,0,1.9,29.5,45.6,23.9],[0,4.6,3.3,0,7.1,1.1]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Analysis<\\/th>\\n      <th>Total<\\/th>\\n      <th>Study<\\/th>\\n      <th>Effect size (residual)<\\/th>\\n      <th>Species (non-phylogenetic)<\\/th>\\n      <th>Phylogeny<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":12,\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Analysis\",\"targets\":0},{\"name\":\"Total\",\"targets\":1},{\"name\":\"Study\",\"targets\":2},{\"name\":\"Effect size (residual)\",\"targets\":3},{\"name\":\"Species (non-phylogenetic)\",\"targets\":4},{\"name\":\"Phylogeny\",\"targets\":5}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nWrote /Users/eduardosantos/Documents/Repos/mate_choice_meta/outputs/1_effect_size_calculation_pipeline/partial_i2_table.tex \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCopy this into the Overleaf tables/ folder.\n```\n\n\n:::\n:::\n\n\n### Interpreting the Heterogeneity {#sec-heterogeneity-narrative}\n\nThe combined models show that mate-choice copying effect sizes are **highly heterogeneous**: total $I^2$ reaches 85.5% for Hedges' $g$ and 74.7% for the log odds ratio. In other words, the large majority of the observed variation reflects genuine differences among effects rather than sampling error alone, so the pooled means should be read as averages over a broad distribution of true effects rather than as a single common effect.\n\nDecomposing that heterogeneity is where the phylogeny becomes informative. For the combined Hedges' $g$ model, the **phylogenetic** component accounts for 3.3% of the variance, the **non-phylogenetic species** component for 1.9%, between-**study** differences for 10.5%, and the residual **effect-size** level for 69.8%. The combined log-odds-ratio model partitions similarly: phylogeny 1.1%, species 23.9%, study 4.3%, and residual 45.4%.\n\nThe size of the phylogenetic component is the key new result. A substantial value would indicate that closely related species tend to show similar degrees of mate-choice copying — i.e., the trait carries a phylogenetic signal and effects are not independent across the tree — which would caution against treating species as exchangeable and would motivate phylogenetically informed interpretation. A small phylogenetic component, by contrast, indicates that relatedness explains little of the among-species variation: most of the species-level differences are idiosyncratic (captured by the non-phylogenetic species term) rather than inherited, and the earlier non-phylogenetic models were not materially biased by ignoring the tree. The contrast between the phylogenetic and non-phylogenetic species components is therefore the most direct readout of how much shared ancestry, as opposed to species-specific biology, structures the data.\n\nTwo further patterns are worth noting. First, the residual effect-size level typically absorbs a large share of the variance, reflecting heterogeneity among individual trials within studies (different paradigms, demonstrators, and conditions). Second, comparing the New-Only, Original-Only, and Combined columns shows whether the new extraction introduces or dilutes heterogeneity relative to the legacy datasets; where the new and original subsets allocate variance differently, the combined estimate reflects a weighted blend of the two. Because this high heterogeneity is the rule rather than the exception, it justifies the moderator and sub-group analyses pursued elsewhere in the workflow, and it is the reason the pooled estimates are reported with prediction intervals in addition to confidence intervals.\n\n---\n\n## Sensitivity Analysis: Impact of the VCV Structure\n\nTo evaluate the robustness of our meta-analytic results, we conduct a sensitivity analysis comparing the main multilevel models (which incorporate a Variance-Covariance [VCV] matrix with an assumed within-study correlation $\\rho = 0.5$) against simplified multilevel models that ignore this correlation (i.e., treating effect size variances as independent diagonal elements, $V = v_i$).\n\nIgnoring within-study correlation can lead to improper weighting of studies with multiple effect sizes and can bias the standard errors and confidence intervals of the pooled estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Define comparison function\ncompare_vcv_models <- function(dat, name, yi = \"yi\", vi = \"vi\", cluster_var = \"identifierStudyId\", obs_var = \"identifierEffectSizeID\", rho = 0.5) {\n    dat2 <- dat %>%\n        filter(!is.na(.data[[yi]]), !is.na(.data[[vi]]), .data[[vi]] > 0)\n\n    if (nrow(dat2) == 0) {\n        return(NULL)\n    }\n\n    # A. With VCV (rho = 0.5)\n    VCV <- metafor::vcalc(\n        vi = dat2[[vi]],\n        cluster = dat2[[cluster_var]],\n        obs = dat2[[obs_var]],\n        rho = rho,\n        data = dat2\n    )\n    mod_w_vcv <- metafor::rma.mv(\n        yi = dat2[[yi]],\n        V = VCV,\n        random = list(\n            ~ 1 | identifierStudyId,\n            ~ 1 | identifierEffectSizeID,\n            ~ 1 | taxonomySpecies\n        ),\n        test = \"t\",\n        dfs = \"contain\",\n        method = \"REML\",\n        sparse = TRUE,\n        data = dat2\n    )\n\n    # B. Without VCV (diagonal V = vi)\n    mod_no_vcv <- metafor::rma.mv(\n        yi = dat2[[yi]],\n        V = dat2[[vi]],\n        random = list(\n            ~ 1 | identifierStudyId,\n            ~ 1 | identifierEffectSizeID,\n            ~ 1 | taxonomySpecies\n        ),\n        test = \"t\",\n        dfs = \"contain\",\n        method = \"REML\",\n        sparse = TRUE,\n        data = dat2\n    )\n\n    # Combine results\n    data.frame(\n        Analysis = name,\n        Model_Type = c(\"With VCV (rho = 0.5)\", \"Without VCV (Independent)\"),\n        k = c(mod_w_vcv$k, mod_no_vcv$k),\n        Estimate = c(mod_w_vcv$b[1], mod_no_vcv$b[1]),\n        SE = c(mod_w_vcv$se[1], mod_no_vcv$se[1]),\n        CI_Lower = c(mod_w_vcv$ci.lb[1], mod_no_vcv$ci.lb[1]),\n        CI_Upper = c(mod_w_vcv$ci.ub[1], mod_no_vcv$ci.ub[1]),\n        p_val = c(mod_w_vcv$pval[1], mod_no_vcv$pval[1])\n    )\n}\n\n# 2. Run comparisons across all subsets\ncomp_hedges_new <- compare_vcv_models(db_hedges %>% filter(Dataset_Source == \"New Extraction (Santos)\"), \"Hedges' g (New Only)\")\ncomp_hedges_orig <- compare_vcv_models(db_hedges %>% filter(Dataset_Source == \"Original (Davies 2020)\"), \"Hedges' g (Original Only)\")\ncomp_hedges_comb <- compare_vcv_models(db_hedges, \"Hedges' g (Combined)\")\n\ncomp_or_new <- compare_vcv_models(db_or %>% filter(Dataset_Source == \"New Extraction (Santos)\"), \"Log OR (New Only)\")\ncomp_or_orig <- compare_vcv_models(db_or %>% filter(Dataset_Source == \"Original (Jones & DuVal 2019)\"), \"Log OR (Original Only)\")\ncomp_or_comb <- compare_vcv_models(db_or, \"Log OR (Combined)\")\n\n# 3. Bind all comparisons together\nvcv_comparison_results <- bind_rows(\n    comp_hedges_new, comp_hedges_orig, comp_hedges_comb,\n    comp_or_new, comp_or_orig, comp_or_comb\n)\n```\n:::\n\n\n### Sensitivity Comparison Table\n\nThe interactive table below compares the pool estimate, standard error (SE), 95% Confidence Intervals, and p-values for both models across all subsets.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c0eda95b1821c33d87f3\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c0eda95b1821c33d87f3\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"Hedges' g (New Only)\",\"Hedges' g (New Only)\",\"Hedges' g (Original Only)\",\"Hedges' g (Original Only)\",\"Hedges' g (Combined)\",\"Hedges' g (Combined)\",\"Log OR (New Only)\",\"Log OR (New Only)\",\"Log OR (Original Only)\",\"Log OR (Original Only)\",\"Log OR (Combined)\",\"Log OR (Combined)\"],[\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\",\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\",\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\",\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\",\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\",\"With VCV (rho = 0.5)\",\"Without VCV (Independent)\"],[69,69,158,158,227,227,69,69,103,103,172,172],[0.2068689242520383,0.2157068224949591,0.5841247362742467,0.6071498593241086,0.465526116079073,0.4834794808711216,0.3787579412757202,0.3953892257059317,0.786727529788425,0.8009438006200142,0.5999319490737961,0.6401539951639961],[0.1123508193308414,0.1194244112585397,0.07642811529498207,0.07612756997085335,0.07102935199350542,0.07279638836591346,0.2056285814824185,0.2181830051634766,0.2116093942215533,0.2097838693709813,0.1377460006923514,0.1488492512651848],[-0.03409961742540854,-0.040433064984778,0.4256225263333195,0.4492709422365765,0.3204648269138114,0.3348094219932087,-0.06227150294319245,-0.07256677929859434,0.3381356536131546,0.3562218642493315,0.3177720575018507,0.3352501258215166],[0.4478374659294851,0.4718467099746963,0.7426269462151738,0.7650287764116406,0.6105874052443345,0.6321495397490347,0.8197873854946327,0.8633452307104578,1.235319405963695,1.245665736990697,0.8820918406457414,0.9450578645064756],[0.08686678964066173,0.09242210894658981,1.249437298941754e-07,6.212336102911422e-08,2.997425130627138e-07,2.356629803527756e-07,0.08676276773894154,0.091454179579743,0.001870596899230365,0.001514299436139059,0.0001610173858046537,0.0001867542184954441]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Analysis<\\/th>\\n      <th>Model_Type<\\/th>\\n      <th>k<\\/th>\\n      <th>Estimate<\\/th>\\n      <th>SE<\\/th>\\n      <th>CI_Lower<\\/th>\\n      <th>CI_Upper<\\/th>\\n      <th>p_val<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":12,\"dom\":\"t\",\"columnDefs\":[{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatSignif(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 4, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"Analysis\",\"targets\":0},{\"name\":\"Model_Type\",\"targets\":1},{\"name\":\"k\",\"targets\":2},{\"name\":\"Estimate\",\"targets\":3},{\"name\":\"SE\",\"targets\":4},{\"name\":\"CI_Lower\",\"targets\":5},{\"name\":\"CI_Upper\",\"targets\":6},{\"name\":\"p_val\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Key Methodological Findings\n\n1. **Marginal Shifts in Pooled Estimates:** \n   Treating effect sizes as completely independent (Without VCV) causes very minor changes to the overall pooled estimates. For the combined dataset, the Hedges' $g$ estimate shifts from $0.47$ to $0.48$, while the Log Odds Ratio (lnOR) estimate shifts from $0.60$ to $0.64$. This indicates that the main directional conclusions of the meta-analyses are robust to VCV specification.\n\n2. **Standard Error Shifts:** \n   In this multilevel model specification (which partitions variance using nested random intercepts), omitting the VCV matrix and assuming independence leads to a *slight inflation* of the standard error and wider confidence intervals for the combined analyses:\n   * **Hedges' $g$ (Combined):** SE increases from $0.07$ to $0.07$ (CI width increases from $0.29$ to $0.30$).\n   * **Log Odds Ratio (Combined):** SE increases from $0.14$ to $0.15$ (CI width increases from $0.56$ to $0.61$).\n   \n   This demonstrates that accounting for known within-study covariance via `vcalc` yields more precise, correctly-weighted estimates.\n\n3. **Impact on Statistical Significance:**\n   For continuous outcomes (Hedges' $g$ Combined), the pooled estimate is statistically significant with the VCV matrix ($p < 0.0001$) and statistically significant without it ($p < 0.0001$). Binary outcomes (Log OR Combined) are statistically significant under both specifications ($p = 0.000$ with VCV; $p = 0.000$ without).\n\nTherefore, we conclude that while the overall direction and magnitude of the estimates are stable, **incorporating the VCV matrix** ensures appropriate weighting, controlling for within-study correlation, and obtaining accurate standard errors and statistical tests.\n\n---\n\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.0 (2026-04-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.5.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_CA/en_CA/en_CA/C/en_CA/en_CA\n\ntime zone: America/Edmonton\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] emmeans_2.0.3       clubSandwich_0.7.0  scales_1.4.0       \n [4] DT_0.34.0           patchwork_1.3.2     orchaRd_2.2.0      \n [7] metafor_5.0-1       numDeriv_2016.8-1.1 metadat_1.6-0      \n[10] Matrix_1.7-5        lubridate_1.9.5     forcats_1.0.1      \n[13] stringr_1.6.0       dplyr_1.2.1         purrr_1.2.2        \n[16] readr_2.2.0         tidyr_1.3.2         tibble_3.3.1       \n[19] ggplot2_4.0.3       tidyverse_2.0.0     readxl_1.5.0       \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1   vipor_0.4.7        farver_2.1.2       S7_0.2.2          \n [5] latex2exp_0.9.8    fastmap_1.2.0      TH.data_1.1-5      pacman_0.5.1      \n [9] mathjaxr_2.0-0     digest_0.6.39      estimability_1.5.1 timechange_0.4.0  \n[13] lifecycle_1.0.5    survival_3.8-6     magrittr_2.0.5     compiler_4.6.0    \n[17] rlang_1.2.0        sass_0.4.10        tools_4.6.0        yaml_2.3.12       \n[21] knitr_1.51         labeling_0.4.3     htmlwidgets_1.6.4  bit_4.6.0         \n[25] here_1.0.2         RColorBrewer_1.1-3 multcomp_1.4-30    withr_3.0.2       \n[29] grid_4.6.0         xtable_1.8-8       MASS_7.3-65        cli_3.6.6         \n[33] mvtnorm_1.4-1      rmarkdown_2.31     crayon_1.5.3       ragg_1.5.2        \n[37] generics_0.1.4     otel_0.2.0         tzdb_0.5.0         ggbeeswarm_0.7.3  \n[41] cachem_1.1.0       splines_4.6.0      parallel_4.6.0     cellranger_1.1.0  \n[45] vctrs_0.7.3        sandwich_3.1-1     jsonlite_2.0.0     hms_1.1.4         \n[49] bit64_4.8.2        beeswarm_0.4.0     systemfonts_1.3.2  crosstalk_1.2.2   \n[53] jquerylib_0.1.4    glue_1.8.1         codetools_0.2-20   stringi_1.8.7     \n[57] gtable_0.3.6       pillar_1.11.1      htmltools_0.5.9    R6_2.6.1          \n[61] textshaping_1.0.5  rprojroot_2.1.1    vroom_1.7.1        evaluate_1.0.5    \n[65] lattice_0.22-9     bslib_0.11.0       coda_0.19-4.1      nlme_3.1-169      \n[69] xfun_0.58          zoo_1.8-15         pkgconfig_2.0.3   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "overall_effect_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}